package com.courtstory.app;

import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Coach capture always names the subject explicitly; ownership never silently defaults to the coach. */
final class CoachWorkspace {
    static JSONObject record(MainActivity a,JSONObject player,String table){JSONObject r=a.newRecord(table);put(r,"playerID",player.optString("id"));put(r,"playerName",playerName(player));put(r,"sport",ProfileSetup.sport(a.store.player()));put(r,"enteredByCoachID",a.store.player().optString("id"));if(table.equals("matches"))ProfileSetup.matchDefaults(r,player,a.store.settings().optString("defaultMatchType","Singles"));return r;}
    static List<JSONObject> sessions(MainActivity a){
        JSONObject coach=a.store.player();String sport=ProfileSetup.sport(coach);Set<String> players=new HashSet<>();players.add(coach.optString("id"));for(JSONObject p:rows(a.store.table("players")))if(StoryTimeline.inRoster(p,coach)&&SportProfiles.plays(p,sport))players.add(p.optString("id"));
        List<JSONObject> sessions=new ArrayList<>();for(JSONObject r:rows(a.store.table("trainingSessions"))){if(!r.optString("sport","Tennis").equals(sport))continue;boolean included=r.optString("enteredByCoachID").equals(coach.optString("id"));for(String player:players)included|=CoachInsights.includes(r,player);if(included)sessions.add(r);}sessions.sort(Comparator.comparingLong(r->millis(r,"date")));return sessions;
    }
    static void schedule(MainActivity a){a.current=()->schedule(a);a.page("Coaching schedule",ProfileSetup.sport(a.store.player()));a.playerScreen("schedule",null);boolean any=false;for(JSONObject session:sessions(a))if(!status("trainingSessions",session).equals("Completed")){any=true;a.card(title("trainingSessions",session),session.optString("playerName")+"\n"+summary("trainingSessions",session),()->a.detail("trainingSessions",session));}if(!any)a.note("No planned or active sessions for this roster and sport.");a.navigation("Today");}
    static void capturePage(MainActivity a,JSONObject p){a.current=()->capturePage(a,p);a.page("Record a player chapter",playerName(p)+" • "+ProfileSetup.sport(a.store.player()));a.playerScreen("capture",p);AdaptiveRules.summary(a,p,ProfileSetup.sport(a.store.player()));capture(a,p);a.button("Back to overview",()->CoachInsights.player(a,p,30));}
    static void sectionsPage(MainActivity a,JSONObject p){a.current=()->sectionsPage(a,p);a.page("Player records",playerName(p)+" • "+ProfileSetup.sport(a.store.player()));a.playerScreen("records",p);sections(a,p);a.button("Back to overview",()->CoachInsights.player(a,p,30));}
    static void capture(MainActivity a,JSONObject p){a.heading("Add to this player’s story");a.primary("Record a match for "+playerName(p),()->a.edit("matches",record(a,p,"matches"),true));a.button("Record training for "+playerName(p),()->a.edit("trainingSessions",record(a,p,"trainingSessions"),true));a.button("Add this player’s tournament",()->a.edit("tournaments",record(a,p,"tournaments"),true));if(TrackingMode.guided(a.store))a.button(TrackingMode.power(a.store)?"Quick observation or drill assessment":"Quick coaching observation",()->journal(a,p));a.note("Use detailed forms, live scoring or the session timer. A supported Android keyboard can also dictate into note fields.");}
    static void sections(MainActivity a,JSONObject p){a.heading("Player workspace");a.button("Sessions and practice history",()->records(a,p,"trainingSessions"));a.button("Match record",()->records(a,p,"matches"));a.button("Tournament history",()->records(a,p,"tournaments"));if(TrackingMode.guided(a.store))a.button(TrackingMode.power(a.store)?"Observations and measured drills":"Coaching observations",()->journal(a,p));}
    static void records(MainActivity a,JSONObject p,String table){RecordListUI.forPlayer(a,p,table);}
    static void overview(MainActivity a){CoachRosterUI.show(a,true,"",0);}

    static void journal(MainActivity a,JSONObject source){if(!TrackingMode.guided(a.store)){CoachInsights.player(a,source,30);return;}JSONObject p=find(a.store.table("players"),source.optString("id"));String sport=ProfileSetup.sport(a.store.player());a.current=()->journal(a,p);a.page("Coaching journal",playerName(p)+" • "+sport);a.playerScreen("journal",p);a.primary("Add a quick observation",()->entry(a,p,false));if(TrackingMode.power(a.store))a.button("Record a measured drill",()->entry(a,p,true));List<JSONObject> notes=observations(p,sport,TrackingMode.power(a.store));boolean any=false;for(JSONObject note:notes)if(note.optString("sport","Tennis").equals(sport)&&(!note.optBoolean("measured")||TrackingMode.power(a.store))){any=true;a.heading(note.optString("title"));a.note(date(note,"date",true)+"\n"+note.optString("observation"));if(note.optBoolean("measured"))a.note(note.optInt("successful")+" successful from "+note.optInt("attempts")+" attempts • "+Math.round(note.optInt("successful")*100f/Math.max(1,note.optInt("attempts")))+"%\nConditions: "+note.optString("conditions","Not recorded"));a.note("Next action: "+note.optString("nextAction","Not recorded"));if(!note.optString("playerFeedback").trim().isEmpty())a.note("Player perspective: "+note.optString("playerFeedback"));JSONObject captured=note;if(!note.optString("nextAction").trim().isEmpty())a.button("Plan practice: "+note.optString("title"),()->planFromObservation(a,p,captured));a.button("Edit entry: "+note.optString("title"),()->entry(a,p,note.optBoolean("measured"),note));a.button("Delete entry: "+note.optString("title"),()->a.confirm("Delete journal entry?","This removes this observation or drill measurement.",()->{JSONObject next=copy(find(a.store.table("players"),p.optString("id")));JSONArray items=array(next,"coachingJournal");for(int i=items.length()-1;i>=0;i--)if(items.optJSONObject(i).optString("id").equals(captured.optString("id")))items.remove(i);if(a.saveRecord("players",next))journal(a,next);}));}if(!any)a.note("Keep a concise observation or record a repeatable drill. Measurements remain separate from coaching opinions.");a.button("Back to player",()->CoachInsights.player(a,p,30));}
    static void entry(MainActivity a,JSONObject p,boolean measured){entry(a,p,measured,null);} static void entry(MainActivity a,JSONObject p,boolean measured,JSONObject original){if(!TrackingMode.guided(a.store)||measured&&!TrackingMode.power(a.store)){CoachInsights.player(a,p,30);return;}JSONObject note=original==null?obj():copy(original);if(original==null){put(note,"id",id());put(note,"date",now());put(note,"sport",ProfileSetup.sport(a.store.player()));put(note,"measured",measured);}a.page(measured?"Measured drill":"Quick observation",playerName(p));a.draft=note;a.draftTable="journal";a.mediaPlayerID=p.optString("id");a.editing=true;a.editorReturn=()->journal(a,p);a.field(note,"title",measured?"Drill name":"Observation title",false);a.dateField(note,"date","Date");a.choice(note,"focus","Focus",SportRules.focus(note));if(measured){a.field(note,"successful","Successful attempts",true);a.field(note,"attempts","Total attempts",true);a.field(note,"conditions","Drill setup and conditions",false);a.note("Use a consistent drill and setup when comparing results. This is an observed success rate, not an automatic player rating.");}a.field(note,"observation","What happened and what it means",false);a.field(note,"playerFeedback","Player perspective (optional)",false);a.field(note,"nextAction","Next practice action",false);a.primary("Save journal entry",()->{if(note.optString("title").trim().isEmpty()||note.optString("observation").trim().isEmpty()){a.error("Add a title and observation.");return;}if(measured&&(note.optInt("attempts")<1||note.optInt("successful")<0||note.optInt("successful")>note.optInt("attempts"))){a.error("Total attempts must be positive; successful attempts must be between zero and the total.");return;}JSONObject latest=find(a.store.table("players"),p.optString("id"));if(latest==null){a.error("Player no longer exists.");return;}JSONObject next=copy(latest);JSONArray saved=array(next,"coachingJournal");for(int i=saved.length()-1;i>=0;i--)if(saved.optJSONObject(i).optString("id").equals(note.optString("id")))saved.remove(i);saved.put(note);if(a.saveRecord("players",next)){journal(a,next);a.announce("Player story updated");}});a.button("Cancel",a::onBackPressed);}
    static List<JSONObject> observations(JSONObject player,String sport,boolean power){
        List<JSONObject> notes=new ArrayList<>();
        for(JSONObject note:rows(array(player,"coachingJournal")))if(note.optString("sport","Tennis").equals(sport)&&(power||!note.optBoolean("measured")))notes.add(note);
        notes.sort(Comparator.comparingLong((JSONObject n)->millis(n,"date")).reversed());return notes;
    }
    static void planFromObservation(MainActivity a,JSONObject player,JSONObject note){
        if(!TrackingMode.guided(a.store)||note.optBoolean("measured")&&!TrackingMode.power(a.store))return;
        if(!note.optString("sport","Tennis").equals(ProfileSetup.sport(a.store.player()))){a.error("Switch to this observation’s sport before planning practice.");return;}
        JSONObject session=record(a,player,"trainingSessions");put(session,"trainingType",CustomScore.custom(session)?"Skills practice":"One-to-one coaching");
        put(session,"sessionObjectives",note.optString("nextAction"));put(session,"focus",note.optString("focus"));
        put(session,"notes","From observation: "+note.optString("title")+"\n"+date(note,"date",true)+"\n"+note.optString("observation")+(note.optString("playerFeedback").trim().isEmpty()?"":"\nPlayer perspective: "+note.optString("playerFeedback")));
        put(session,"sourceObservationID",note.optString("id"));a.edit("trainingSessions",session,true);
    }
    static void practicePriority(MainActivity a,JSONObject player,String sport){
        if(!TrackingMode.guided(a.store))return;
        for(JSONObject note:observations(player,sport,TrackingMode.power(a.store)))if(!note.optString("nextAction").trim().isEmpty()){
            a.heading("Next practice priority");a.note(note.optString("nextAction"));a.note("From "+note.optString("title")+" • "+date(note,"date",true));
            a.button("Plan practice from this observation",()->planFromObservation(a,player,note));break;
        }
    }
}
