package com.courtstory.app;
import android.content.*;
import android.app.*;
import android.appwidget.*;
import android.widget.RemoteViews;
import org.json.*;
import static com.courtstory.app.Domain.*;
public final class CourtWidget extends AppWidgetProvider {
    static final class Next {final String table;final JSONObject record;Next(String table,JSONObject record){this.table=table;this.record=record;}}
    static Next next(Store store){JSONObject owner=store.player();if(owner==null)return null;Next next=null;String sport=ProfileSetup.sport(owner);for(String table:new String[]{"matches","trainingSessions","tournaments"})for(JSONObject record:rows(store.table(table))){if(!record.optString("sport","Tennis").equals(sport))continue;boolean mine=CoachInsights.includes(record,owner.optString("id"));if(ProfileSetup.coach(owner))for(JSONObject player:rows(store.table("players")))if(StoryTimeline.inRoster(player,owner)&&SportProfiles.plays(player,sport)&&CoachInsights.includes(record,player.optString("id")))mine=true;if(!mine)continue;boolean underway=active(record),upcoming=(status(table,record).equals("Scheduled")||status(table,record).equals("Entered"))&&millis(record,"date")>=System.currentTimeMillis();if(!underway&&!upcoming)continue;if(next==null||underway&&!active(next.record)||underway==active(next.record)&&millis(record,"date")<millis(next.record,"date"))next=new Next(table,record);}return next;}
    public static void refresh(Context context){AppWidgetManager manager=AppWidgetManager.getInstance(context);new CourtWidget().onUpdate(context,manager,manager.getAppWidgetIds(new ComponentName(context,CourtWidget.class)));}
    @Override public void onUpdate(Context context,AppWidgetManager manager,int[] ids){if(ids.length==0)return;String text="Open your court story";Next next=null;try{next=next(new Store(context));text=next==null?"No upcoming activities. Plan your next session.":summary(next.table,next.record);}catch(Exception ignored){text="Open Court Story to check your library.";}for(int id:ids){RemoteViews views=new RemoteViews(context.getPackageName(),R.layout.court_widget);views.setTextViewText(R.id.widget_body,text);Intent intent=new Intent(context,MainActivity.class).setAction("courtstory.widget."+id);if(next!=null)intent.putExtra("table",next.table).putExtra("id",next.record.optString("id"));PendingIntent tap=PendingIntent.getActivity(context,id,intent,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);views.setOnClickPendingIntent(R.id.widget_body,tap);views.setOnClickPendingIntent(R.id.widget_title,tap);manager.updateAppWidget(id,views);}}
}
