package com.courtstory.app;
import android.widget.*;
import android.view.*;
import android.os.*;
import org.json.*;
import java.util.*;
import java.util.function.Consumer;
import static com.courtstory.app.Domain.*;
/** Native labelled controls and stable focus targets for custom numeric scoreboards. */
final class CustomScoreUI {
    static void form(MainActivity a,JSONObject event){CustomScore.defaults(event);a.heading(event.optString("sport")+" event");a.field(event,"eventName","Event name (optional)",false);a.choice(event,"status","Status",split("Scheduled|In progress|Completed"));a.scheduleFields(event);a.choice(event,"customKind","Sides are",split("Teams|Players"));a.field(event,"customUnit","Score label, such as Points or Goals",false);a.heading("Players and teams");JSONArray sides=array(event,"customTeams");for(int i=0;i<sides.length();i++){final int index=i;JSONObject side=sides.optJSONObject(i);a.field(side,"name","Side "+(i+1)+" name",false);a.field(side,"members","Side "+(i+1)+" player names (optional)",false);a.field(side,"score","Side "+(i+1)+" recorded score",true);if(sides.length()>2)a.button("Remove side "+(i+1),()->a.confirm("Remove this side?","This removes its score from this event when you save.",()->{sides.remove(index);put(event,"customOwnerSide",0);event.remove("customHistory");a.edit("matches",event,true);}));}
        a.button("Add another player or team",()->{JSONObject side=obj();put(side,"id",id());put(side,"name",(event.optString("customKind").equals("Players")?"Player ":"Team ")+(sides.length()+1));put(side,"score",0);sides.put(side);event.remove("customHistory");a.edit("matches",event,true);});
        a.button("Represented side: "+sides.optJSONObject(Math.max(0,Math.min(sides.length()-1,event.optInt("customOwnerSide")))).optString("name"),()->{String[] names=new String[sides.length()];for(int i=0;i<names.length;i++)names[i]=sides.optJSONObject(i).optString("name");new android.app.AlertDialog.Builder(a).setTitle("Which side does this profile represent?").setSingleChoiceItems(names,event.optInt("customOwnerSide"),(d,w)->{put(event,"customOwnerSide",w);d.dismiss();a.edit("matches",event,true);}).setNegativeButton("Cancel",null).show();});
        a.heading("Scoring and timing");a.choice(event,"customWinningRule","Finish rule",split("Target score|Lead by|Manual finish"));a.field(event,"customTarget","Target score or required lead",true);a.field(event,"customWinBy","Winning margin for target-score games",true);a.field(event,"customPeriods","Number of periods",true);a.field(event,"customPeriodMinutes","Minutes per period",true);
        a.note("Numeric scores start at zero. Add as many named sides as your session needs. The represented side determines this profile's win, loss or draw.");
        AdaptiveRules.matchForm(a,event);a.optional("Reflection",()->{a.field(event,"matchStory","Event reflection",false);a.field(event,"nextPracticeFocus","Next practice focus",false);});
    }
    static void score(MainActivity a,JSONObject source){final JSONObject[] current={copy(source)};CustomScore.defaults(current[0]);a.current=()->score(a,current[0]);a.page(source.optString("sport")+" scoreboard",source.optString("eventName","Numeric scoring"));a.screenName="Live score";a.screenTable="matches";a.screenRecord=source.optString("id");a.note(TermsPolicy.SAFETY);
        TextView status=a.text("",16,true),clock=a.text("",17,true);a.body.addView(status,a.lp());a.body.addView(clock,a.lp());List<TextView> totals=new ArrayList<>();List<Button> scoring=new ArrayList<>();final Runnable[] refresh={null};Consumer<Consumer<JSONObject>> change=mutation->{JSONObject next=copy(current[0]);mutation.accept(next);if(a.saveRecord("matches",next)){current[0]=next;refresh[0].run();if(!a.store.settings().optString("scoreAnnouncementMode","Automatic").equals("Off"))a.speak(CustomScore.summary(next)+(next.optString("status").equals("Completed")?". Event complete.":""));}};
        JSONArray sides=array(current[0],"customTeams");for(int i=0;i<sides.length();i++){final int index=i;JSONObject side=sides.optJSONObject(i);TextView total=a.text("0",20,true);total.setPadding(0,a.dp(12),0,0);a.body.addView(total,a.lp());totals.add(total);scoring.add(a.primary("Add 1 to "+side.optString("name"),()->change.accept(next->CustomScore.add(next,index,1))));scoring.add(a.button("Subtract 1 from "+side.optString("name"),()->change.accept(next->CustomScore.add(next,index,-1))));}
        refresh[0]=()->{JSONObject event=current[0];status.setText(event.optString("status","Scheduled")+" • "+event.optString("customUnit","Points"));JSONArray teams=array(event,"customTeams");for(int i=0;i<totals.size();i++){JSONObject team=teams.optJSONObject(i);totals.get(i).setText(team.optString("name")+": "+team.optInt("score"));scoring.get(i*2).setEnabled(!event.optString("status").equals("Completed"));scoring.get(i*2+1).setEnabled(!event.optString("status").equals("Completed")&&team.optInt("score")>0);}long seconds=CustomScore.remaining(event)/1000;clock.setText("Period "+event.optInt("customPeriod",1)+" of "+event.optInt("customPeriods",1)+" • "+String.format(Locale.UK,"%02d:%02d",seconds/60,seconds%60)+(event.has("customClockStartedAt")?" running":" paused"));};
        a.button("Undo last scoring action",()->change.accept(CustomScore::undo));a.button("Hear all scores",()->a.speak(CustomScore.summary(current[0])));
        a.button("Start period clock",()->change.accept(CustomScore::start));a.button("Pause period clock",()->change.accept(CustomScore::pause));a.button("Read remaining time",()->a.speak(clock.getText().toString()));
        a.button("Next period",()->{JSONObject event=current[0];if(event.optString("status").equals("Completed")){a.announce("This event is complete. Undo the last score to reopen it.");return;}if(event.optInt("customPeriod",1)>=event.optInt("customPeriods",1)){a.announce("This is the final period. Use Finish event when ready.");return;}a.confirm("Move to the next period?","Scores carry forward. The next period's clock starts paused.",()->change.accept(next->{CustomScore.checkpoint(next);CustomScore.pause(next);put(next,"customPeriod",next.optInt("customPeriod",1)+1);put(next,"customClockRemainingMs",next.optInt("customPeriodMinutes",10)*60000L);}));});
        a.button("Finish event",()->a.confirm("Finish this event?","Save all scores and the represented side's result.",()->change.accept(CustomScore::finish)));a.button("Save and leave scoreboard",()->a.detail("matches",current[0]));
        Handler handler=new Handler(Looper.getMainLooper());Runnable tick=new Runnable(){public void run(){if(!clock.isAttachedToWindow())return;JSONObject event=current[0];if(event.has("customClockStartedAt")&&CustomScore.remaining(event)==0){JSONObject next=copy(event);CustomScore.pause(next);if(a.saveRecord("matches",next)){current[0]=next;a.announce("Period time finished. Scores are saved.");}}refresh[0].run();handler.postDelayed(this,1000);}};clock.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewAttachedToWindow(View view){handler.post(tick);}public void onViewDetachedFromWindow(View view){handler.removeCallbacks(tick);}});refresh[0].run();handler.postDelayed(tick,1000);
    }
}