package com.courtstory.app;

import org.json.*;
import java.time.*;
import java.time.format.*;
import java.util.*;

/** Domain functions retain the iOS v11 library keys and preserve unknown fields. */
public final class Domain {
    private Domain() {}
    public static JSONObject obj() { return new JSONObject(); }
    public static JSONObject copy(JSONObject o) { try { return new JSONObject(o.toString()); } catch (JSONException e) { throw new IllegalArgumentException(e); } }
    public static void put(JSONObject o,String k,Object v) { try { if(v == null) o.remove(k); else o.put(k,v); } catch(JSONException e) { throw new IllegalArgumentException(e); } }
    public static JSONObject object(JSONObject o,String k) { JSONObject n=o.optJSONObject(k); if(n==null){n=obj();put(o,k,n);} return n; }
    public static JSONArray array(JSONObject o,String k) { JSONArray n=o.optJSONArray(k); if(n==null){n=new JSONArray();put(o,k,n);} return n; }
    public static List<JSONObject> rows(JSONArray a) { List<JSONObject> r=new ArrayList<>(); for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o!=null)r.add(o);} return r; }
    public static JSONObject find(JSONArray a,String id) { for(JSONObject o:rows(a))if(o.optString("id").equals(id))return o; return null; }
    public static String id(){return UUID.randomUUID().toString().toUpperCase(Locale.ROOT);}
    public static String now(){return Instant.now().truncatedTo(java.time.temporal.ChronoUnit.SECONDS).toString();}
    public static long millis(JSONObject o,String key){Object x=o.opt(key);if(x==null||x==JSONObject.NULL)return 0;if(x instanceof Number)return (long)((((Number)x).doubleValue()+978307200)*1000);String value=String.valueOf(x);if(value.trim().isEmpty())return 0;if(value.length()==10&&value.charAt(4)=='-'&&value.charAt(7)=='-'){try{return LocalDate.parse(value).atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();}catch(Exception ignored){return 0;}}try{return Instant.parse(value).toEpochMilli();}catch(Exception ignored){}try{return OffsetDateTime.parse(value).toInstant().toEpochMilli();}catch(Exception ignored){}try{return LocalDate.parse(value).atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();}catch(Exception ignored){}return 0;}
    public static String date(JSONObject o,String key,boolean time){long t=millis(o,key);return t==0?"Not recorded":DateTimeFormatter.ofPattern(time?"EEE d MMM yyyy, HH:mm":"EEE d MMM yyyy").format(Instant.ofEpochMilli(t).atZone(ZoneId.systemDefault()));}
    public static String playerName(JSONObject p){return p==null?"Player":p.optString("preferredName","").trim().isEmpty()?p.optString("name","Player"):p.optString("preferredName");}
    public static String title(String table,JSONObject r){return switch(table){case "settings"->"App settings";case "matches"->CustomScore.custom(r)?(r.optString("eventName").trim().isEmpty()?r.optString("sport","Custom sport")+" event":r.optString("eventName")):r.optString("playerName","Player")+" vs "+r.optString("opponentName","Opponent");case "trainingSessions"->r.optString("trainingType","Training");default->r.optString("name","Untitled");};}
    public static String status(String table,JSONObject r){if(table.equals("trainingSessions")){if(millis(r,"actualStart")>0&&millis(r,"actualFinish")==0)return "In progress";return r.optBoolean("androidScheduled",!r.has("actualStart")&&millis(r,"date")>System.currentTimeMillis())?"Scheduled":"Completed";}if(table.equals("tournaments"))return r.optString("finalResult","Entered");return r.optString("status","Scheduled");}
    public static String summary(String table,JSONObject r){String s=title(table,r)+". "+status(table,r)+". "+date(r,"date",r.optBoolean("hasStartTime"));if(table.equals("tournaments"))s+=" to "+date(r,"endDate",false);if(!r.optString("venue").trim().isEmpty())s+=". "+r.optString("venue");if(!r.optString("location").trim().isEmpty())s+=", "+r.optString("location");if(table.equals("matches")&&r.optString("matchType").equals("Doubles"))s+=". Partners: "+r.optString("partnerName")+" and "+r.optString("opponent2Name");if(table.equals("matches")&&status(table,r).equals("Completed"))s+=". "+r.optString("result","Result not recorded")+". "+r.optString("customScoreSummary",r.optString("setScores","Score not recorded"));if(table.equals("trainingSessions"))s+=". "+durationText(durationSeconds(r));return s;}
    public static long durationSeconds(JSONObject r){if(r.optString("durationSource").equals("manual")&&r.optInt("durationMinutes")>0)return r.optLong("durationMinutes")*60;JSONObject workout=r.optJSONObject("workout");if(workout!=null&&workout.has("durationSeconds")){double seconds=workout.optDouble("durationSeconds",Double.NaN);if(Double.isFinite(seconds)&&seconds>=0)return (long)Math.min(315360000,seconds);}long start=millis(r,"actualStart"),finish=millis(r,"actualFinish");if(start>0&&finish>=start)return (finish-start)/1000;return Math.max(0,r.optLong("durationMinutes",60))*60;}
    public static String durationText(long seconds){long value=Math.max(0,seconds),h=value/3600,m=value%3600/60,sec=value%60;List<String> parts=new ArrayList<>();if(h>0)parts.add(h+(h==1?" hour":" hours"));if(m>0)parts.add(m+(m==1?" minute":" minutes"));if(sec>0||parts.isEmpty())parts.add(sec+(sec==1?" second":" seconds"));return String.join(" ",parts);}
    public static int duration(JSONObject r){if(r.optString("durationSource").equals("manual"))return r.optInt("durationMinutes",60);JSONObject workout=r.optJSONObject("workout");if(workout!=null&&workout.has("durationSeconds"))return (int)Math.max(1,Math.round(workout.optDouble("durationSeconds")/60));long a=millis(r,"actualStart"),b=millis(r,"actualFinish");return a>0&&b>a?(int)Math.max(1,Math.round((b-a)/60000.0)):r.optInt("durationMinutes",60);}
    public static boolean active(JSONObject r){return millis(r,"actualStart")>0&&millis(r,"actualFinish")==0||r.optString("status").equals("In progress");}
    public static JSONObject newLibrary(){JSONObject d=obj();put(d,"dataVersion",11);put(d,"libraryID",id());put(d,"onboardingCompleted",false);put(d,"deletedRecordIDs",new JSONArray());for(String k:new String[]{"players","matches","trainingSessions","tournaments"})put(d,k,new JSONArray());JSONObject setup=object(d,"setup");for(String k:new String[]{"coaches","venues","locations","tournamentTemplates"})put(setup,k,new JSONArray());JSONObject s=object(d,"settings");put(s,"theme","Tennis");put(s,"trackingMode","Basic");put(s,"scoreAnnouncementMode","Automatic");put(s,"hapticsEnabled",true);return d;}
    public static JSONArray table(JSONObject d,String name){return array(new java.util.HashSet<>(java.util.Arrays.asList("coaches","venues","locations","tournamentTemplates")).contains(name)?object(d,"setup"):d,name);}
    public static void upsert(JSONObject d,String table,JSONObject r){JSONArray a=table(d,table);put(r,"modifiedAt",now());JSONObject existing=find(a,r.optString("id"));put(r,"revision",Math.max(r.optLong("revision"),existing==null?0:existing.optLong("revision"))+1);for(int i=0;i<a.length();i++)if(a.optJSONObject(i).optString("id").equals(r.optString("id"))){try{a.put(i,r);}catch(JSONException e){throw new IllegalArgumentException(e);}return;}a.put(r);}
    public static String validate(JSONObject d,boolean migration){if(d.optInt("dataVersion")<10||d.optInt("dataVersion")>11)return "This backup needs a supported Court Story library version (10 or 11).";if(d.optJSONObject("settings")==null||d.optJSONObject("setup")==null||d.optJSONArray("deletedRecordIDs")==null)return "The backup is incomplete.";Set<String> all=new HashSet<>();Map<String,Set<String>> ids=new HashMap<>();for(String t:new String[]{"players","matches","trainingSessions","tournaments","coaches","venues","locations","tournamentTemplates"}){Object parent=new java.util.HashSet<>(java.util.Arrays.asList("coaches","venues","locations","tournamentTemplates")).contains(t)?d.optJSONObject("setup"):d;JSONArray a=((JSONObject)parent).optJSONArray(t);if(a==null)return "The backup is missing "+t;Set<String> group=new HashSet<>();ids.put(t,group);if(rows(a).size()!=a.length())return "A backup table contains invalid records.";for(JSONObject r:rows(a)){String id=r.optString("id");try{UUID.fromString(id);}catch(Exception e){return "Invalid record identifier.";}if(!all.add(id))return "Duplicate record identifier.";group.add(id);if(migration&&active(r))return "Finish active activities before importing a migration backup.";}}
        for(String t:new String[]{"matches","trainingSessions","tournaments"})for(JSONObject r:rows(table(d,t))){if(!ids.get("players").contains(r.optString("playerID")))return "An activity refers to a missing player.";for(String[] ref:new String[][]{{"partnerID","players"},{"opponentID","players"},{"opponent2ID","players"},{"tournamentID","tournaments"},{"trainingSessionID","trainingSessions"},{"venueID","venues"},{"templateID","tournamentTemplates"}})if(r.has(ref[0])&&!r.isNull(ref[0])&&!ids.get(ref[1]).contains(r.optString(ref[0])))return "An activity has a missing linked record.";JSONObject c=r.optJSONObject("context");if(c!=null){for(String[] ref:new String[][]{{"coachIDs","coaches"},{"participantIDs","players"}}){JSONArray a=c.optJSONArray(ref[0]);if(a!=null)for(int j=0;j<a.length();j++)if(!ids.get(ref[1]).contains(a.optString(j)))return "A training session has a missing linked person.";}}}
        String selected=d.optString("selectedPlayerID","");if(!selected.isEmpty()&&!ids.get("players").contains(selected))return "The selected player is missing.";
        for(JSONObject c:rows(table(d,"coaches")))if(c.has("playerID")&&!c.isNull("playerID")&&!ids.get("players").contains(c.optString("playerID")))return "A coach refers to a missing player.";
        for(JSONObject t:rows(table(d,"tournamentTemplates")))if(t.has("venueID")&&!t.isNull("venueID")&&!ids.get("venues").contains(t.optString("venueID")))return "A template refers to a missing venue.";
        for(JSONObject r:rows(table(d,"trainingSessions"))){JSONObject c=r.optJSONObject("context");if(c!=null){for(String[] ref:new String[][]{{"venueID","venues"},{"tournamentID","tournaments"}})if(c.has(ref[0])&&!c.isNull(ref[0])&&!ids.get(ref[1]).contains(c.optString(ref[0])))return "A session refers to a missing activity or venue.";}JSONObject p=r.optJSONObject("practiceResult");if(p!=null)for(String key:new String[]{"partnerID","opponentID","opponent2ID"})if(p.has(key)&&!p.isNull(key)&&!ids.get("players").contains(p.optString(key)))return "A practice result refers to a missing player.";}
        JSONArray deleted=d.optJSONArray("deletedRecordIDs");for(int i=0;i<deleted.length();i++)if(ids.get("matches").contains(deleted.optString(i))||ids.get("trainingSessions").contains(deleted.optString(i))||ids.get("tournaments").contains(deleted.optString(i)))return "The backup contains an activity also marked as deleted.";
        return null;}
    public static String[] split(String values){return values.split("\\|",-1);}
}





