package com.courtstory.app;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.net.Uri;
import android.view.View;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Private, described player media. Nothing is uploaded or shared automatically. */
final class MediaLibrary {
    static File file(Context c,String name)throws IOException{if(!name.matches("[A-Fa-f0-9-]{36}\\.bin"))throw new IOException("Invalid media reference.");File dir=new File(c.getFilesDir(),"media");if(!dir.exists()&&!dir.mkdirs())throw new IOException("Could not create media storage.");return new File(dir,name);}
    static void show(MainActivity a,JSONObject person){if(!TrackingMode.guided(a.store)){a.home();return;}JSONObject p=find(a.store.table("players"),person.optString("id"));if(p==null){a.error("Player no longer exists.");return;}a.current=()->show(a,p);a.page("Player media",playerName(p)+" • Photos, clips and coaching feedback");a.playerScreen("media",p);a.primary("Add a photo or video",()->{a.mediaPlayerID=p.optString("id");Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).addCategory(Intent.CATEGORY_OPENABLE).setType("*/*").putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/*","video/*"});a.launchDocument(pick,401);});a.note("Media stays privately on this device and is included in a full backup. Add a description of what matters in each image or clip, so the coaching point is available without seeing it.");JSONObject query=obj();EditText search=a.field(query,"search","Search titles, descriptions or tags",false);search.setSingleLine(true);LinearLayout results=a.column();a.body.addView(results);Runnable render=()->{results.removeAllViews();LinearLayout previous=a.body;a.body=results;List<JSONObject> media=rows(array(p,"androidMedia"));Collections.reverse(media);int shown=0;String q=search.getText().toString().trim().toLowerCase(Locale.ROOT);for(JSONObject m:media){if(!m.optString("sport","Tennis").equals(ProfileSetup.sport(a.store.player())))continue;if(!(m.optString("title")+m.optString("description")+m.optString("tags")).toLowerCase(Locale.ROOT).contains(q))continue;shown++;a.card(m.optString("title"),m.optString("mime").startsWith("video/")?"Video • "+m.optString("description"):"Photo • "+m.optString("description"),()->detail(a,p,m));}if(shown==0)a.note("No matching media yet.");a.body=previous;};render.run();search.addTextChangedListener(a.watcher(s->render.run()));a.button(ProfileSetup.coach(a.store.player())?"Back to player":"Back to my tracking",()->{if(ProfileSetup.coach(a.store.player()))CoachInsights.player(a,p,30);else a.track();});}
    static void importFile(MainActivity a,Uri uri){String player=a.mediaPlayerID;JSONObject p=find(a.store.table("players"),player);if(p==null){a.error("Choose a player before adding media.");return;}String mime=a.getContentResolver().getType(uri);if(mime==null||!(mime.startsWith("image/")||mime.startsWith("video/"))){a.error("Choose a supported photo or video.");return;}BackupOperation.get(a).importMedia(uri,mime,player,ProfileSetup.sport(a.store.player()));}
    static void feedbackDraft(MainActivity a,JSONObject p,JSONObject preview){
        if(p==null){a.home();return;}a.page("Share feedback","Review before opening Android sharing.");a.draft=preview;a.draftTable="mediaFeedback";a.mediaPlayerID=p.optString("id");a.editing=true;a.editorReturn=()->show(a,p);
        EditText text=a.field(preview,"text","Editable feedback",false);text.setMaxLines(Integer.MAX_VALUE);a.primary("Share reviewed text",()->a.share(preview.optString("text")));a.button("Back to media library",a::handleBackPressed);
    }
    static void edit(MainActivity a,JSONObject p,JSONObject original){JSONObject m=copy(original);a.page("Describe this moment",playerName(p));a.mediaPlayerID=p.optString("id");a.draft=m;a.draftTable="media";a.editing=true;a.editorReturn=()->show(a,p);a.field(m,"title","Title",false);a.field(m,"description","Visual description and coaching purpose",false);a.note("Describe the relevant position, movement and outcome. This text is read by TalkBack; a title alone cannot explain the visual information.");a.field(m,"transcript","Spoken words or transcript (if relevant)",false);a.field(m,"tags","Tags, such as serve, return or footwork",false);a.field(m,"feedback","Coaching feedback and next practice action",false);a.field(m,"permissionNotes","Permission and permitted use notes (optional)",false);a.field(m,"reviewDate","Review or removal date (optional)",false);a.note("For children’s media, obtain the appropriate child and parent or carer permission before recording, following your organisation’s policy.");a.primary("Save described media",()->{if(m.optString("title").trim().isEmpty()||m.optString("description").trim().isEmpty()){a.error("Add a title and a useful visual description.");return;}JSONObject fresh=find(a.store.table("players"),p.optString("id"));if(fresh==null){a.error("Player no longer exists.");return;}JSONObject next=copy(fresh);JSONArray items=array(next,"androidMedia");boolean found=false;for(int i=0;i<items.length();i++)if(items.optJSONObject(i).optString("id").equals(m.optString("id"))){try{items.put(i,m);}catch(JSONException e){throw new IllegalStateException(e);}found=true;break;}if(!found)items.put(m);if(a.saveRecord("players",next)){a.editing=false;a.draft=null;detail(a,next,m);a.announce("Media and description saved");}});a.button("Cancel changes",a::onBackPressed);}
    static void detail(MainActivity a,JSONObject p,JSONObject m){a.current=()->detail(a,p,m);a.page(m.optString("title"),playerName(p)+" • "+m.optString("sport","Tennis"));a.screenTable="media";a.screenRecord=m.optString("id");a.mediaPlayerID=p.optString("id");a.heading("Description");a.note(m.optString("description"));if(!m.optString("transcript").trim().isEmpty()){a.heading("Transcript");a.note(m.optString("transcript"));}try{File local=file(a,m.optString("fileName"));if(!local.exists())throw new IOException("The media file is unavailable. Restore a full backup containing this media.");if(m.optString("mime").startsWith("image/")){BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeFile(local.getAbsolutePath(),bounds);bounds.inSampleSize=Math.max(1,Math.max(bounds.outWidth,bounds.outHeight)/1400);bounds.inJustDecodeBounds=false;Bitmap bitmap=BitmapFactory.decodeFile(local.getAbsolutePath(),bounds);if(bitmap==null)throw new IOException("This image format cannot be displayed on this phone.");ImageView image=new ImageView(a);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);image.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);a.body.addView(image,a.lp());}else video(a,p,m,local);}catch(Exception e){a.note(e.getMessage());}a.heading("Coaching feedback");a.note(m.optString("feedback","No feedback added yet."));if(find(a.store.table("players"),p.optString("id"))==null){a.button("Back to player history",()->ProfileHistory.player(a,p));return;}a.button("Edit description and feedback",()->edit(a,p,m));a.button("Preview feedback for sharing",()->{JSONObject preview=obj();put(preview,"text",m.optString("title")+"\n"+m.optString("description")+"\n\n"+m.optString("feedback"));feedbackDraft(a,p,preview);});a.button("Delete this media",()->a.confirm("Delete this media?","Remove the photo or clip and its feedback from this player’s library.",()->{JSONObject fresh=find(a.store.table("players"),p.optString("id"));JSONObject next=copy(fresh);JSONArray items=array(next,"androidMedia");for(int i=items.length()-1;i>=0;i--)if(items.optJSONObject(i).optString("id").equals(m.optString("id")))items.remove(i);if(a.saveRecord("players",next)){try{file(a,m.optString("fileName")).delete();}catch(IOException ignored){}show(a,next);}}));a.button("Back to media library",()->show(a,p));}
    static void discardDraft(MainActivity a,JSONObject draft){
        if(draft==null)return;String name=draft.optString("fileName");
        for(JSONObject person:ProfileHistory.all(a.store.data))for(JSONObject item:rows(array(person,"androidMedia")))if(item.optString("fileName").equals(name))return;
        try{file(a,name).delete();}catch(IOException ignored){}
    }
    static void moment(MainActivity a,JSONObject p,JSONObject source,int position){
        JSONObject next=copy(source),cue=object(next,"pendingMoment");if(!cue.has("seconds"))put(cue,"seconds",position);
        a.page("Key moment","Timestamped feedback");a.draft=next;a.draftTable="mediaMoment";a.mediaPlayerID=p.optString("id");a.editing=true;a.editorReturn=()->detail(a,p,source);
        a.field(cue,"seconds","Position in seconds",true);a.field(cue,"description","What happens and what to work on",false);
        a.primary("Save key moment",()->{if(cue.optString("description").trim().isEmpty()||cue.optInt("seconds",-1)<0){a.error("Add a description and a valid playback position.");return;}JSONObject committed=copy(next);array(committed,"moments").put(copy(cue));committed.remove("pendingMoment");JSONObject latest=find(a.store.table("players"),p.optString("id"));if(latest==null){a.error("Player no longer exists.");return;}JSONObject updated=copy(latest);JSONArray media=array(updated,"androidMedia");boolean found=false;for(int i=0;i<media.length();i++)if(media.optJSONObject(i).optString("id").equals(next.optString("id"))){try{media.put(i,committed);}catch(JSONException e){throw new IllegalStateException(e);}found=true;break;}if(!found){a.error("This media no longer exists.");return;}if(a.saveRecord("players",updated)){a.editing=false;a.draft=null;detail(a,updated,committed);a.announce("Key moment saved");}});a.button("Cancel",a::onBackPressed);
    }
    static void video(MainActivity a,JSONObject p,JSONObject m,File file){if(!m.optString("id").equals(a.playbackMediaID)){a.playbackPosition=0;a.playbackSpeed=1f;}a.playbackMediaID=m.optString("id");VideoView video=new VideoView(a);a.activeVideo=video;video.setImportantForAccessibility(View.IMPORTANT_FOR_ACCESSIBILITY_NO);a.body.addView(video,new LinearLayout.LayoutParams(-1,a.dp(200)));video.setVideoPath(file.getAbsolutePath());final android.media.MediaPlayer[] engine={null};video.setOnPreparedListener(player->{engine[0]=player;video.seekTo(Math.min(Math.max(1,a.playbackPosition),Math.max(1,video.getDuration()-1)));if(a.playbackSpeed!=1f){player.setPlaybackParams(player.getPlaybackParams().setSpeed(a.playbackSpeed));video.pause();}});video.setOnErrorListener((player,what,extra)->{a.error("This clip cannot be played on this phone. Its description and feedback are still available.");return true;});a.primary("Play video",()->video.start());a.button("Pause video",video::pause);a.button("Back 5 seconds",()->{video.seekTo(Math.max(0,video.getCurrentPosition()-5000));a.announce("Position "+video.getCurrentPosition()/1000+" seconds");});a.button("Forward 5 seconds",()->{video.seekTo(Math.min(video.getDuration(),video.getCurrentPosition()+5000));a.announce("Position "+video.getCurrentPosition()/1000+" seconds");});a.button("Read playback position",()->a.announce(video.getCurrentPosition()/1000+" seconds of "+video.getDuration()/1000));a.button("Playback speed",()->new AlertDialog.Builder(a).setTitle("Playback speed").setItems(new String[]{"Half speed","Normal speed","One and a half speed"},(d,w)->{if(engine[0]!=null)try{boolean wasPlaying=video.isPlaying();a.playbackSpeed=new float[]{.5f,1f,1.5f}[w];engine[0].setPlaybackParams(engine[0].getPlaybackParams().setSpeed(a.playbackSpeed));if(!wasPlaying)video.pause();}catch(Exception e){a.error("This video format does not support speed changes.");}}).setNegativeButton("Cancel",null).show());a.heading("Key moments");for(JSONObject cue:rows(array(m,"moments"))){a.button("At "+cue.optInt("seconds")+" seconds: "+cue.optString("description"),()->{video.pause();video.seekTo(cue.optInt("seconds")*1000);a.announce(cue.optString("description"));});}if(find(a.store.table("players"),p.optString("id"))!=null)a.button("Add feedback at this moment",()->{int position=Math.max(0,video.getCurrentPosition()/1000);video.pause();moment(a,p,m,position);});video.addOnAttachStateChangeListener(new View.OnAttachStateChangeListener(){public void onViewAttachedToWindow(View v){}public void onViewDetachedFromWindow(View v){video.stopPlayback();}});}
}
