package com.courtstory.app;
import android.app.Activity;
import android.content.Intent;
import android.net.Uri;
import android.widget.Toast;
/** Same policy content as the public Play/Health Connect policy page. */
final class PrivacyPolicy {
    static final String URL="https://sidneytambin-maker.github.io/court-story-privacy/";
    static final String CONTACT="Sidney.Tambin@googlemail.com";
    static final String[][] SECTIONS={
        {"Developer and contact","Court Story for Android is provided by Sidney Tambin. For support or privacy questions, email Sidney.Tambin@googlemail.com. This policy was last updated on 8 October 2026."},
        {"Your records stay on your device","Court Story does not require an online account. The app stores your records in its private storage on your Android device. Sidney Tambin does not receive or collect those records through the app. Court Story has no developer-operated record server, advertising or analytics, and does not sell your data. Optional watch synchronisation is described separately below."},
        {"Optional Wear OS connection","Off by default. If you enable phone/watch synchronisation, the library you choose to send is delivered to Court Story on your paired device using Google Play services. That library can contain health summaries, access preferences and coaching information. Google manages encrypted transport, which can pass through Google-owned servers when Bluetooth is unavailable. Court Story does not receive it on a developer-operated server. Photos and video files are not transferred; descriptive library metadata may be included. Incoming records are reviewed before merging; conflicting versions are retained for review. You can disable the connection and use each device independently. Previously delivered copies remain on the other device until removed there."},
        {"Optional watch-face summaries","Watch-face shortcuts contain no personal details by default. If you enable detailed summaries in Court Story and select a Court Story complication on your watch face, that face receives the selected activity summary, such as scores, scheduled activities or weekly totals. The watch face may retain or display this information while the watch is locked and handles it under its own privacy practices. Choose a face you trust. Turning details off requests an update; remove the complication from your face to remove its display immediately. No summary is sent to a Court Story developer server."},
        {"What you can store","You choose what to enter: player and coach names, sport and access preferences, disability-related preferences if you supply them, goals, match and tournament results, training records, coaching observations, player feedback, and optional photos, videos, descriptions and transcripts. Optional Health Connect measurements can be attached to your own training records. These items are processed locally to provide the features you use."},
        {"Optional Health Connect access","Health Connect is optional and core Court Story features work without it. When you choose Save workout to Health Connect, Court Story requests permission to write your own completed exercise session, including its time, duration, activity type and title. It does not write a coached athlete’s workout into the coach’s personal Health Connect profile. When you choose Attach my Health Connect workout, the app requests exercise-reading permission and lets you select a workout and review its summary. If you grant the optional permissions, available heart rate, active energy, distance and step measurements from that workout’s source and time interval can be attached. Unavailable or declined measurements stay unrecorded. The app does not read health data in the background or use it for advertising."},
        {"Optional watch measurements","On Wear OS, starting a workout with measurements uses Health Services and an ongoing foreground notification. Activity recognition is requested for that workout; heart rate is a separate optional permission. Only available measurements are recorded, and training without sensors remains available. Measurements belong to the watch wearer, not a coached athlete. Pausing or finishing controls the workout service; interrupted recordings retain available measurements. Watch records stay in private local storage unless you enable and use the optional phone connection."},
        {"Your choices to export or share","Court Story does not automatically upload your library. You can deliberately export a backup or report, share a report, create a calendar entry, or save a workout to Health Connect. Android lets you choose the destination or approve the relevant access. A destination can be another app, a local folder or a cloud provider you choose; it then handles the data under its own terms. A full backup contains your profiles, activity records, coaching information, attached health summaries and media. Court Story backup ZIP files are not separately encrypted, so choose a private destination and protect any copies."},
        {"Permissions and reminders","Notifications are optional and support the reminders you configure. Court Story uses Android’s file picker for imports and exports; it does not request broad access to your photos or files. This version does not request microphone, camera, contacts or location permission. Any voice input supplied by your Android keyboard is handled by that keyboard under its own settings and privacy policy."},
        {"Retention, deletion and revoking access","Local records remain until you delete them, clear Court Story’s app storage in Android Settings, or uninstall the app. Keep a backup first if you want to retain them. Android automatic cloud backup is disabled for Court Story. Copies that you deliberately export or share remain at their destinations until you remove them there. Revoke Health Connect permissions in its settings whenever you wish. Revocation stops future access but does not remove summaries already attached to a local record; delete the relevant Court Story session to remove its attached summary. Delete workouts you exported to Health Connect through Health Connect’s own data controls; deleting a local session does not automatically erase an exported workout. There is no developer-held account or record database to delete."},
        {"Coaching other people","Coaches should obtain the appropriate permission before recording or sharing another person’s information, photos or videos, especially where children are involved. Court Story’s local permission notes are a record-keeping aid and do not replace your club’s or organisation’s consent and safeguarding arrangements. The app does not publish player profiles or provide a public messaging service."},
        {"Support and this policy website","If you choose to email support, the information in your email is received by Sidney Tambin and the email services involved so that the enquiry can be answered. Do not send private player or health records unless they are necessary and you intend to share them. This public policy page is hosted on GitHub Pages. Visiting it in your browser is separate from using the offline app; GitHub may process connection information to operate its hosting service under the GitHub Privacy Statement. The page adds no cookies, analytics scripts or third-party fonts."},
        {"Changes to this policy","If Court Story’s data practices change, this policy and its updated date will be revised. New data uses or permissions will be explained before they are introduced. Contact Sidney.Tambin@googlemail.com with any questions about this policy."}
    };
    static void open(Activity activity){try{activity.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(URL)));}catch(android.content.ActivityNotFoundException e){Toast.makeText(activity,"No browser is available. The complete privacy policy is shown here.",Toast.LENGTH_LONG).show();}}
}
