package com.courtstory.app;
import android.app.AlertDialog;
import android.view.View;
import android.widget.*;
import org.json.*;
import static com.courtstory.app.Domain.*;

/** Sport and role are profile preferences, not disability-based feature restrictions. */
public final class ProfileSetup {
    public static final String[] SPORTS=split("Tennis|Padel|Pickleball|Badminton|Squash|Table tennis|Racquetball|Racketlon|Beach tennis|Platform tennis|Custom");
    public static final String[] TYPES=split("Sighted|Visually impaired|Wheelchair|Deaf|Learning disability|Custom");
    public static String sport(JSONObject p){if(p==null)return "Tennis";return p.optString("sport","Tennis").equals("Custom")?p.optString("customSport","Custom sport"):p.optString("sport","Tennis");}
    public static boolean coach(JSONObject p){return p!=null&&p.optString("role","Player").equals("Coach");}
    static void matchDefaults(JSONObject match,JSONObject player,String fallbackType){
        if(player==null)player=obj();else if(!sport(player).equals(match.optString("sport","Tennis")))player=SportProfiles.forSport(player,match.optString("sport","Tennis"));
        put(match,"matchType",player.optString("preferredMatchType",fallbackType));
        put(match,"matchFormat",player.optString("defaultMatchFormat",match.optString("sport","Tennis").equals("Tennis")?"1 set":"Best of 3"));
        if(player.has("preferredSurface"))put(match,"courtSurface",player.optString("preferredSurface"));
        String classification=player.optString("sightLevel",MainActivity.CLASSIFICATIONS[5]);
        put(match,"sightLevel",classification);
        String type=player.optString("playerType",player.optString("playerMode").contains("Blind")?"Visually impaired":"Sighted");
        int bounces=type.equals("Wheelchair")?2:type.equals("Visually impaired")?(classification.startsWith("B1")||classification.startsWith("B2")?3:classification.startsWith("B3")?2:1):1;
        int override=player.optInt("bounceAllowance",0);put(match,"allowedBounces",override>0?override:bounces);
        put(match,"suddenDeathDeuce",match.optString("sport").equals("Beach tennis")||match.optString("sport").equals("Tennis")&&type.equals("Visually impaired"));
        AdaptiveRules.apply(match,player);
    }
    public static void form(MainActivity a,JSONObject r){SportProfiles.select(r,ProfileSetup.sport(r));if(!r.has("playerType"))put(r,"playerType",r.optString("playerMode").startsWith("Blind")?"Visually impaired":"Sighted");a.heading("Your court identity");a.field(r,"name","Name",false);a.field(r,"preferredName","Preferred name",false);LinearLayout host=a.body;LinearLayout conditional=a.column();
        Button sport=a.button("Sport: "+(sport(r).isEmpty()?"Custom":sport(r)),()->{});Button role=a.button("I am a: "+r.optString("role","Player"),()->{});host.addView(conditional);
        Runnable render=()->{conditional.removeAllViews();LinearLayout previous=a.body;a.body=conditional;String selected=r.optString("sport","Tennis");if(selected.equals("Custom"))a.field(r,"customSport","Your court or racket sport",false);if(coach(r)){a.heading("Coaching profile");a.choice(r,"coachLevel","Coaching level",split("Assistant coach|Club coach|Qualified coach|Senior coach|Performance coach|High-performance coach|Head coach|Independent coach|Custom"));a.field(r,"customCoachLevel","Other coaching level or title (optional)",false);a.field(r,"qualifications","Qualifications and awarding bodies",false);a.field(r,"coachingOrganisation","Club or coaching organisation",false);a.field(r,"coachingExperienceYears","Years of coaching experience",true);a.choice(r,"coachingAudience","Players you coach",split("All levels|Beginners|Recreational players|Club competitors|Performance athletes|Children and young people|Adults|Inclusive and adaptive sport|Mixed groups|Custom"));a.field(r,"coachingSpecialisms","Coaching specialisms",false);if(TrackingMode.guided(a.store)){a.field(r,"coachingFocus","Current coaching priorities",false);a.field(r,"coachingSessionGoals","Session and development goals",false);}a.field(r,"qualificationRenewal","Qualification renewal notes",false);a.field(r,"safeguardingTraining","Safeguarding training / renewal (optional)",false);a.note("Your home screen will highlight your roster, upcoming coaching sessions and development plans. You can still record your own play.");a.optional("My access preferences (optional)",()->PlayerCategory.controls(a,r,true));}else {a.heading("Player category");PlayerCategory.controls(a,r,true);}a.heading("Your preferences");a.choice(r,"trackingMode","Detail level",split("Basic|Standard|Power"));if(!CustomScore.custom(sport(r))){a.choice(r,"preferredMatchType","Preferred match type",split("Singles|Doubles"));if(!r.has("defaultMatchFormat"))put(r,"defaultMatchFormat",sport(r).equals("Tennis")?"1 set":"Best of 3");if(!SportRules.racketPoints(r))a.choice(r,"defaultMatchFormat","Default match format",split("1 set|Best of 3|Best of 5|Custom"));a.toggle(r,"isRegularPartner","Regular doubles partner",false);}a.field(r,"club","Club",false);if(TrackingMode.guided(a.store)){a.field(r,"primaryGoal","Main goal",false);if(!coach(r))a.field(r,"coachingFocus","Coaching priority",false);a.choice(r,"preferredSurface","Preferred surface",a.SURFACES);}a.optional("More profile details",()->{a.field(r,"surname","Surname",false);a.field(r,"nationality","Nationality",false);a.field(r,"ltaNumber","National player / LTA number",false);a.field(r,"itfNumber","International / ITF number",false);a.field(r,"age","Age (optional)",true);a.choice(r,"playingHand","Playing hand",split("Not recorded|Right|Left|Ambidextrous"));a.field(r,"playingStyle","Playing style",false);a.field(r,"profileNotes","Profile notes",false);a.field(r,"accessibilityPreferences","Accessibility preferences (optional)",false);});a.body=previous;};
        sport.setOnClickListener(v->new AlertDialog.Builder(a).setTitle("Choose your racket sport").setSingleChoiceItems(SPORTS,java.util.Arrays.asList(SPORTS).indexOf(r.optString("sport","Tennis")),(d,w)->{SportProfiles.select(r,SPORTS[w]);sport.setText("Sport: "+(sport(r).isEmpty()?"Custom":sport(r)));d.dismiss();render.run();}).setNegativeButton("Cancel",null).show());
        role.setOnClickListener(v->new AlertDialog.Builder(a).setTitle("Your main role").setSingleChoiceItems(new String[]{"Player","Coach"},coach(r)?1:0,(d,w)->{put(r,"role",w==0?"Player":"Coach");put(object(r,"sportModes"),sport(r),r.optString("role"));role.setText("I am a: "+r.optString("role"));d.dismiss();render.run();}).setNegativeButton("Cancel",null).show());render.run();}
    public static void coachHome(MainActivity a){a.current=()->coachHome(a);a.page("Coach’s court",sport(a.store.player())+" • "+playerName(a.store.player())+" • "+TrackingMode.current(a.store));SportProfiles.controls(a);int rosterSize=0;for(JSONObject person:rows(a.store.table("players")))if(!coach(SportProfiles.forSport(person,sport(a.store.player())))&&StoryTimeline.inRoster(person,a.store.player())&&SportProfiles.plays(person,sport(a.store.player())))rosterSize++;a.hero("Your players",rosterSize==0?"Build your roster. Keep each player’s records together.":rosterSize+(rosterSize==1?" player":" players")+" · Sessions, plans and progress.",()->roster(a));a.primary("Plan a coaching session",()->{JSONObject r=a.newRecord("trainingSessions");put(r,"trainingType","One-to-one coaching");a.edit("trainingSessions",r,false);});a.button("Coaching schedule",()->CoachWorkspace.schedule(a));a.heading("Next sessions");boolean any=false;for(JSONObject r:CoachWorkspace.sessions(a))if(!status("trainingSessions",r).equals("Completed")){any=true;a.card(title("trainingSessions",r),summary("trainingSessions",r),()->a.detail("trainingSessions",r));}if(!any)a.note("Your next coaching session starts here. Add a plan, select your participants and capture their next steps.");StoryTimeline.show(a,true);a.heading("My own game");a.button("My matches",()->a.list("matches"));a.button("My training",()->a.list("trainingSessions"));a.button("My tournaments",()->a.list("tournaments"));a.button("My performance reports",a::reports);a.button("Switch player or coach profile",a::choosePlayer);a.button("Edit coaching profile",()->a.edit("players",a.store.player(),false));a.navigation("Today");}
    public static void roster(MainActivity a){CoachInsights.roster(a);}
    public static void athlete(MainActivity a,JSONObject p){if(!TrackingMode.guided(a.store)){CoachInsights.player(a,p,30);return;}a.current=()->athlete(a,p);a.page(playerName(p),"Player development");a.playerScreen("development",p);JSONObject scoped=SportProfiles.forSport(p,sport(a.store.player()));a.note("Goal: "+scoped.optString("primaryGoal","Not recorded"));a.note("Development notes: "+scoped.optString("developmentNotes","Not recorded"));a.button("Edit profile and goals",()->a.edit("players",p,false));a.button("Update development plan",()->development(a,p,SportProfiles.forSport(p,sport(a.store.player()))));a.heading("Coaching history");for(JSONObject s:rows(a.store.table("trainingSessions"))){if(!s.optString("sport","Tennis").equals(sport(a.store.player())))continue;boolean linked=s.optString("playerID").equals(p.optString("id"));JSONArray ids=array(object(s,"context"),"participantIDs");for(int i=0;i<ids.length();i++)linked|=ids.optString(i).equals(p.optString("id"));if(linked)a.card(title("trainingSessions",s),summary("trainingSessions",s),()->a.detail("trainingSessions",s));}a.button("Plan session for this player",()->{JSONObject s=CoachWorkspace.record(a,p,"trainingSessions");put(s,"trainingType","One-to-one coaching");a.edit("trainingSessions",s,false);});a.navigation("More");}
    static JSONObject saveDevelopment(JSONObject latest,JSONObject draft){
        String originalSport=sport(latest);JSONObject next=SportProfiles.forSport(latest,sport(draft));
        for(String key:new String[]{"primaryGoal","developmentNotes","nextReviewDate"}){next.remove(key);if(draft.has(key))put(next,key,draft.opt(key));}
        SportProfiles.select(next,originalSport);return next;
    }
    static void development(MainActivity a,JSONObject p,JSONObject draft){
        if(!TrackingMode.guided(a.store)){CoachInsights.player(a,p,30);return;}
        a.page("Development plan",playerName(p));a.draft=draft;a.draftTable="development";a.mediaPlayerID=p.optString("id");a.editing=true;a.editorReturn=()->athlete(a,p);
        a.field(draft,"primaryGoal","Main goal",false);a.field(draft,"developmentNotes","Development plan and coaching notes",false);a.field(draft,"nextReviewDate","Next review date (YYYY-MM-DD)",false);
        a.primary("Save development plan",()->{String due=draft.optString("nextReviewDate").trim();if(!due.isEmpty())try{java.time.LocalDate.parse(due);}catch(java.time.DateTimeException e){a.error("Use a valid review date in YYYY-MM-DD format, or leave it empty.");return;}JSONObject latest=find(a.store.table("players"),p.optString("id"));if(latest==null){a.error("This player is no longer available.");return;}JSONObject next=saveDevelopment(latest,draft);if(a.saveRecord("players",next)){athlete(a,next);a.announce("Development plan saved for "+sport(draft));}});a.button("Cancel",a::onBackPressed);
    }
}



