package com.courtstory.app;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;
/** Removed profiles retain their ownership and coaching history outside the active roster. */
final class ProfileHistory {
    static final String KEY="androidRemovedProfiles";
    static JSONArray removed(JSONObject data){JSONArray value=data.optJSONArray(KEY);return value==null?new JSONArray():value;}
    static List<JSONObject> all(JSONObject data){List<JSONObject> profiles=rows(table(data,"players"));profiles.addAll(rows(removed(data)));return profiles;}
    static boolean has(JSONObject data){return removed(data).length()>0;}
    static void retain(JSONObject data,JSONObject profile){JSONArray saved=array(data,KEY);for(JSONObject p:rows(saved))if(p.optString("id").equals(profile.optString("id")))return;saved.put(copy(profile));}
    static boolean empty(JSONObject data){if(has(data))return false;for(String t:new String[]{"players","matches","trainingSessions","tournaments","coaches","venues","locations","tournamentTemplates"})if(table(data,t).length()>0)return false;return true;}
    static void merge(JSONObject result,JSONObject local,JSONObject remote){JSONArray merged=new JSONArray();Set<String> seen=new HashSet<>();for(JSONObject source:new JSONObject[]{local,remote})for(JSONObject p:rows(removed(source))){String id=p.optString("id");if(find(table(result,"players"),id)==null&&seen.add(id))merged.put(copy(p));}put(result,KEY,merged);}
    static void show(MainActivity a){a.current=()->show(a);a.page("Retained player history","Profiles removed from the active roster");a.note("Saved profiles, activities and coaching records are retained here and in your private backups. They are no longer offered for new activity.");for(JSONObject p:rows(removed(a.store.data)))a.button(playerName(p),()->player(a,p));a.button("Export full private backup",a::backup);a.button("Back to Court Story",a::home);}
    static void player(MainActivity a,JSONObject p){a.current=()->player(a,p);a.page(playerName(p),"Retained history");a.screenTable="removedPlayer";a.screenRecord=p.optString("id");RecordDetails.show(a,"players",p);for(String table:new String[]{"matches","trainingSessions","tournaments"}){int count=0;for(JSONObject r:rows(a.store.table(table)))if(r.optString("playerID").equals(p.optString("id")))count++;if(count>0)a.button(a.plural(table)+" ("+count+")",()->activities(a,p,table,0));}if(TrackingMode.guided(a.store)){for(JSONObject entry:rows(array(p,"coachingJournal")))if(!entry.optBoolean("measured")||TrackingMode.power(a.store)){a.heading(entry.optString("title","Coaching note"));a.note(entry.optString("sport","Tennis")+" • "+date(entry,"date",true));a.note(entry.optString("observation"));a.note("Next action: "+entry.optString("nextAction","Not recorded"));if(entry.optBoolean("measured"))a.note(entry.optInt("successful")+" successful attempts from "+entry.optInt("attempts"));}for(JSONObject media:rows(array(p,"androidMedia")))a.card(media.optString("title","Saved media"),media.optString("description"),()->MediaLibrary.detail(a,p,media));}a.button("Export full private backup",a::backup);a.button("Back to retained history",()->show(a));}
    static void activities(MainActivity a,JSONObject p,String table,int offset){a.current=()->activities(a,p,table,offset);a.page(a.plural(table),playerName(p)+" • Retained history");a.screenTable="removedList:"+table;a.screenRecord=p.optString("id");a.screenDays=offset;List<JSONObject> records=new ArrayList<>();for(JSONObject r:rows(a.store.table(table)))if(r.optString("playerID").equals(p.optString("id")))records.add(r);records.sort((x,y)->RecordChronology.compare(y,x));int start=Math.min(Math.max(0,offset),records.size()),end=Math.min(start+50,records.size());a.note("Showing "+(records.isEmpty()?0:start+1)+" to "+end+" of "+records.size());for(JSONObject r:records.subList(start,end))a.card(title(table,r),summary(table,r),()->record(a,p,table,r));if(start>0)a.button("Previous records",()->activities(a,p,table,Math.max(0,start-50)));if(end<records.size())a.button("Next records",()->activities(a,p,table,end));a.button("Back to player history",()->player(a,p));}
    static void record(MainActivity a,JSONObject p,String table,JSONObject r){a.current=()->record(a,p,table,r);a.page(title(table,r),playerName(p)+" • Retained history");a.screenTable="removedRecord:"+table;a.screenRecord=r.optString("id");a.note(summary(table,r));RecordDetails.show(a,table,r);WorkoutSummary.show(a,r);a.button("Back to player history",()->player(a,p));}
    static boolean restore(MainActivity a,android.os.Bundle saved){String screen=saved.getString("screenName",""),table=saved.getString("screenTable",""),id=saved.getString("screenRecord","");if(screen.equals("Retained player history")){show(a);return true;}if(table.equals("removedPlayer")){JSONObject p=find(removed(a.store.data),id);if(p!=null){player(a,p);return true;}}if(table.startsWith("removedList:")){JSONObject p=find(removed(a.store.data),id);if(p!=null){activities(a,p,table.substring(12),saved.getInt("screenDays",0));return true;}}if(table.startsWith("removedRecord:")){String type=table.substring(14);JSONObject r=find(a.store.table(type),id);JSONObject p=r==null?null:find(removed(a.store.data),r.optString("playerID"));if(p!=null){record(a,p,type,r);return true;}}if(table.equals("media")){JSONObject p=find(removed(a.store.data),saved.getString("mediaPlayerID",""));JSONObject m=p==null?null:find(array(p,"androidMedia"),id);if(m!=null){MediaLibrary.detail(a,p,m);return true;}}return false;}
}
