package com.courtstory.app;

import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Court Story's chronological journey connects existing records, rather than duplicating data. */
final class StoryTimeline {
    static final class Chapter {long when;java.util.function.Supplier<String> title,detail;Runnable open;Chapter(long when,String title,String detail,Runnable open){this(when,()->title,()->detail,open);}Chapter(long when,java.util.function.Supplier<String> title,java.util.function.Supplier<String> detail,Runnable open){this.when=when;this.title=title;this.detail=detail;this.open=open;}}
    static boolean inRoster(JSONObject person,JSONObject coach){return person.optString("coachProfileID").isEmpty()||person.optString("coachProfileID").equals(coach.optString("id"))||person.optString("id").equals(coach.optString("id"));}
    static void show(MainActivity a,boolean coaching){JSONObject owner=a.store.player();String sport=ProfileSetup.sport(owner);List<Chapter> chapters=new ArrayList<>();Set<String> people=new HashSet<>();for(JSONObject p:rows(a.store.table("players")))if(p.optString("id").equals(owner.optString("id"))||coaching&&inRoster(p,owner)&&SportProfiles.plays(p,sport)){people.add(p.optString("id"));for(JSONObject entry:rows(array(p,"coachingJournal")))if(TrackingMode.guided(a.store)&&(!entry.optBoolean("measured")||TrackingMode.power(a.store))&&entry.optString("sport","Tennis").equals(sport))chapters.add(new Chapter(millis(entry,"date"),playerName(p)+" • "+entry.optString("title"),"Coaching observation\n"+entry.optString("observation"),()->CoachWorkspace.journal(a,p)));for(JSONObject media:rows(array(p,"androidMedia")))if(TrackingMode.guided(a.store)&&media.optString("sport","Tennis").equals(sport))chapters.add(new Chapter(millis(media,"createdAt"),playerName(p)+" • "+media.optString("title"),"Coaching moment\n"+media.optString("description"),()->MediaLibrary.detail(a,p,media)));}
        for(String table:new String[]{"matches","trainingSessions","tournaments"})for(JSONObject r:rows(a.store.table(table))){if(!r.optString("sport","Tennis").equals(sport)||!people.contains(r.optString("playerID"))||!status(table,r).equals("Completed"))continue;long when=millis(r,"actualFinish")>0?millis(r,"actualFinish"):millis(r,"date");if(when>System.currentTimeMillis())continue;chapters.add(new Chapter(when,()->title(table,r),()->summary(table,r),()->a.detail(table,r)));}chapters.sort((x,y)->Long.compare(y.when,x.when));a.heading(coaching?"Your coaching story":"Your court story");if(chapters.isEmpty())a.note("Your story begins with the next session. Results, practice and described coaching moments will come together here.");else for(Chapter chapter:chapters.subList(0,Math.min(5,chapters.size())))a.card(chapter.title.get(),chapter.detail.get(),()->a.go(chapter.open));
        if(coaching&&TrackingMode.guided(a.store)){List<JSONObject> review=new ArrayList<>();String today=java.time.LocalDate.now().toString();for(JSONObject p:rows(a.store.table("players")))if(!ProfileSetup.coach(SportProfiles.forSport(p,sport))&&inRoster(p,owner)&&SportProfiles.plays(p,sport)){JSONObject scoped=SportProfiles.forSport(p,sport);String due=scoped.optString("nextReviewDate");if(due.matches("\\d{4}-\\d{2}-\\d{2}")&&due.compareTo(today)<=0)review.add(scoped);}if(!review.isEmpty()){a.heading("Development reviews due");for(JSONObject p:review)a.card(playerName(p),"Review date: "+p.optString("nextReviewDate")+"\nGoal: "+p.optString("primaryGoal","Not set"),()->CoachInsights.player(a,p,30));}}
    }
}
