package com.courtstory.app;
/** Accessible offline terms, matching the public policy site. */
final class TermsPolicy {
    static final String VERSION="2026-10-07";
    static final String SAFETY="Record after play, in a safe place. Stop playing before using these controls.";
    static final String[][] SECTIONS={
        {"About these terms","These terms govern Court Story for Android, provided by Sidney Tambin as a personal independent project. Contact: Sidney.Tambin@googlemail.com. Version: 7 October 2026. Court Story is not affiliated with or endorsed by a sports governing body. The app’s privacy policy explains its separate data practices."},
        {"Record after play, in a safe place","Court Story is designed to help you record and review results, progress and observations after sporting activity, while the details are fresh in your mind. Stop playing and move to a safe place before looking at the screen, entering information or operating any control. Do not use the app while playing a sport, running, moving around an active court, driving, cycling or doing anything that requires your attention for safety. Do not allow spoken feedback, headphones, notifications or vibration to distract you from other people, balls, equipment or your surroundings. If you use scoring or timer tools, operate them only after play has stopped or have a separate, safely positioned non-playing observer operate them. Accessibility features do not remove these safety requirements."},
        {"Your sporting decisions","You remain responsible for deciding when it is safe to use your device and for following venue rules, safeguarding requirements and the instructions of responsible coaches and officials. Court Story does not supervise activity, assess whether a location is safe or monitor emergencies. Stop an activity and obtain appropriate assistance when needed. Do not rely on the app as a safety system, official umpire, medical device or substitute for qualified advice."},
        {"Records, scores and coaching information","Check the records you enter, imported measurements and calculated results before relying on or sharing them. Rule presets and statistics are record-keeping aids; competition organisers may use different rules and you should confirm the applicable format. Coaching notes and plans reflect the information entered by the user, not an assessment or recommendation by Sidney Tambin. The app does not promise a particular sporting result, player ranking, selection outcome or improvement."},
        {"Permission to use the app","You may use Court Story for lawful personal sporting records and legitimate coaching work. You receive a non-exclusive licence to use the app; ownership of its software and branding is not transferred. Do not redistribute the app as your own, misrepresent its origin, interfere with its operation or use it to violate another person’s rights. Rights expressly allowed by applicable law, including relevant software-interoperability rights, are not removed."},
        {"Your content and other people","You retain your rights in the records and media you create. You must have the necessary permission to record, import or share another person’s information or image and to use any third-party material. Coaches are responsible for their own professional duties and for appropriate consent and safeguarding, particularly for children and vulnerable people. If you cannot legally agree to these terms yourself, involve a parent, guardian or other authorised representative before using the app."},
        {"Device storage, backups and other services","Your library is stored locally. Keep suitable private backups, particularly before changing devices, clearing storage or uninstalling. Do not assume that data you delete can be recovered. You choose whether to use Health Connect, Android sharing, calendar apps or a file/cloud provider; those services have their own terms and availability. Court Story does not operate those services or automatically send your library to the developer."},
        {"Our responsibility and limits","Sidney Tambin will exercise reasonable care and skill in providing Court Story. We are not responsible for loss caused solely by your use contrary to the clear safe-use instructions above, inaccurate information you supply, or an independent third-party service where we have not caused or contributed to that loss. We are not responsible for losses that were not reasonably foreseeable when you began using the app. These provisions do not excuse our own negligence or breach of duties imposed by law. Nothing in these terms excludes or limits liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any other liability that the law does not allow to be excluded or limited. Your mandatory consumer rights and remedies remain unaffected."},
        {"Updates and availability","Updates may correct defects, improve accessibility, adapt to Android or sport-rule changes, or add features. Reasonable steps will be taken to explain material changes and avoid unnecessary loss of your records. No update removes rights you already have under applicable law. Any future paid offering will be clearly described before you choose to purchase it; these terms do not authorise an automatic charge. A test build may contain defects, so retain backups and report problems through the support contact."},
        {"Stopping use and changes to these terms","You may stop using Court Story at any time. Export any records you wish to keep before uninstalling or clearing storage. Material changes to these terms will be brought to your attention and identified by an updated version/date; they will not retrospectively take away accrued rights. Where agreement is needed, you will have an opportunity to review the revised terms. A licence may be ended for serious unlawful misuse, with reasonable notice and an opportunity to remedy it where appropriate; this does not authorise remote deletion of your local records."},
        {"Questions and disputes","Please contact Sidney.Tambin@googlemail.com so that a concern can be investigated and a reasonable resolution sought. You do not have to give up any right to seek advice, complain to a competent authority or bring proceedings in a court available to you under applicable law. Mandatory consumer protections in the place where you live remain applicable. If a provision cannot lawfully be enforced, that does not remove the remaining lawful provisions or your statutory rights."}
    };
    static void show(MainActivity a,Runnable back){a.current=()->show(a,back);a.page("Terms and safe use","Court Story · Sidney Tambin · 7 October 2026");for(String[] section:SECTIONS){a.heading(section[0]);a.note(section[1]);}a.button("Back",back);}
    static void showSetup(MainActivity a,org.json.JSONObject profile,int step){show(a,()->Onboarding.show(a,profile,step));a.editing=true;a.draft=profile;a.draftTable="termsOnboarding";a.setupStep=step;}
    static boolean accepted(org.json.JSONObject profile){return profile.optBoolean("androidTermsAgreed");}
}
