package com.courtstory.app;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

final class TrainingProgress {
    static List<String> focus(JSONObject session){Map<String,String> unique=new LinkedHashMap<>();List<String> values=new ArrayList<>();values.add(session.optString("focus"));JSONArray extra=session.optJSONArray("additionalFocus");if(extra!=null)for(int i=0;i<extra.length();i++)values.add(extra.optString(i));for(String value:values){String name=value.trim();if(!name.isEmpty()&&!name.equalsIgnoreCase("Not specified")&&!name.equalsIgnoreCase("Not recorded"))unique.putIfAbsent(name.toLowerCase(Locale.ROOT),name);}return new ArrayList<>(unique.values());}
    static void count(Map<String,Integer> totals,JSONObject session){List<String> names=focus(session);if(names.isEmpty())names=Collections.singletonList("No focus selected");for(String name:names)totals.put(name,totals.getOrDefault(name,0)+1);}
    static JSONObject latestReview(List<JSONObject> matches){JSONObject latest=null;for(JSONObject m:matches)if(status("matches",m).equals("Completed")&&millis(m,"date")<=System.currentTimeMillis()&&(!m.optString("nextPracticeFocus").trim().isEmpty()||!m.optString("matchNeedsWork").trim().isEmpty())&&(latest==null||millis(m,"date")>millis(latest,"date")))latest=m;return latest;}
    static String review(JSONObject match){return match.optString("nextPracticeFocus").trim().isEmpty()?match.optString("matchNeedsWork"):match.optString("nextPracticeFocus");}
    static void dashboard(MainActivity a){if(!TrackingMode.guided(a.store))return;a.heading("Training and goals");JSONObject p=a.store.player();for(String[] f:new String[][]{{"primaryGoal","Your goal"},{"coachingFocus","Coaching priority"}})if(!p.optString(f[0]).trim().isEmpty())a.card(f[1],p.optString(f[0]),()->a.edit("players",p,false));JSONObject review=latestReview(a.mine("matches"));if(review!=null)a.card("From your latest match review",review(review),()->a.edit("matches",review,false));Map<String,Integer> focus=new LinkedHashMap<>();Map<String,long[]> focusTime=new LinkedHashMap<>(),types=new LinkedHashMap<>();JSONObject missing=null;long cutoff=java.time.LocalDate.now().minusDays(30).atStartOfDay(java.time.ZoneId.systemDefault()).toInstant().toEpochMilli();for(JSONObject s:a.mine("trainingSessions")){long when=millis(s,"actualStart")>0?millis(s,"actualStart"):millis(s,"date");if(status("trainingSessions",s).equals("Completed")&&when>=cutoff&&when<=System.currentTimeMillis()){count(focus,s);List<String> names=focus(s);if(names.isEmpty())names=Collections.singletonList("No focus selected");for(String name:names)addDuration(focusTime,name,s);String type=s.optString("trainingType","Training");List<String> coaches=new ArrayList<>();JSONArray ids=array(object(s,"context"),"coachIDs");for(int i=0;i<ids.length();i++){JSONObject coach=find(a.store.table("coaches"),ids.optString(i));if(coach!=null)coaches.add(coach.optString("name"));}if(!coaches.isEmpty())type+=", coaches: "+String.join(", ",coaches);addDuration(types,type,s);if(focus(s).isEmpty())missing=s;}}if(!types.isEmpty()){a.heading("Training, last 30 days");showBreakdown(a,types);}if(!focusTime.isEmpty()){a.heading("Focus, last 30 days");showBreakdown(a,focusTime);}if(missing!=null){JSONObject session=missing;a.button("Choose training focus",()->a.edit("trainingSessions",session,false));}a.button("Edit goals and priorities",()->a.edit("players",p,false));a.button("Review a match",()->a.list("matches"));a.button("Plan next training session",()->a.edit("trainingSessions",null,false));if(TrackingMode.power(a.store))a.button("Preview coach summary",()->a.coachSummary(30));}
    static void addDuration(Map<String,long[]> values,String key,JSONObject session){long[] total=values.computeIfAbsent(key,k->new long[2]);total[0]++;total[1]+=durationSeconds(session);}
    static void showBreakdown(MainActivity a,Map<String,long[]> values){List<Map.Entry<String,long[]>> sorted=new ArrayList<>(values.entrySet());sorted.sort((x,y)->{int count=Long.compare(y.getValue()[0],x.getValue()[0]);return count!=0?count:x.getKey().compareToIgnoreCase(y.getKey());});for(Map.Entry<String,long[]> entry:sorted){long[] totals=entry.getValue();a.note(entry.getKey()+": "+totals[0]+(totals[0]==1?" session, ":" sessions, ")+durationText(totals[1]));}}
}
