package com.courtstory.app;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

final class TrainingProgress {
    static List<String> focus(JSONObject session){Map<String,String> unique=new LinkedHashMap<>();List<String> values=new ArrayList<>();values.add(session.optString("focus"));JSONArray extra=session.optJSONArray("additionalFocus");if(extra!=null)for(int i=0;i<extra.length();i++)values.add(extra.optString(i));for(String value:values){String name=value.trim();if(!name.isEmpty()&&!name.equalsIgnoreCase("Not specified")&&!name.equalsIgnoreCase("Not recorded"))unique.putIfAbsent(name.toLowerCase(Locale.ROOT),name);}return new ArrayList<>(unique.values());}
    static void count(Map<String,Integer> totals,JSONObject session){List<String> names=focus(session);if(names.isEmpty())names=Collections.singletonList("No focus selected");for(String name:names)totals.put(name,totals.getOrDefault(name,0)+1);}
    static JSONObject latestReview(List<JSONObject> matches){JSONObject latest=null;for(JSONObject m:matches)if(status("matches",m).equals("Completed")&&millis(m,"date")<=System.currentTimeMillis()&&(!m.optString("nextPracticeFocus").trim().isEmpty()||!m.optString("matchNeedsWork").trim().isEmpty())&&(latest==null||millis(m,"date")>millis(latest,"date")))latest=m;return latest;}
    static String review(JSONObject match){return match.optString("nextPracticeFocus").trim().isEmpty()?match.optString("matchNeedsWork"):match.optString("nextPracticeFocus");}
    static void dashboard(MainActivity a){if(!TrackingMode.guided(a.store))return;a.heading("Training and goals");JSONObject p=a.store.player();for(String[] f:new String[][]{{"primaryGoal","Your goal"},{"coachingFocus","Coaching priority"}})if(!p.optString(f[0]).trim().isEmpty())a.card(f[1],p.optString(f[0]),()->a.edit("players",p,false));JSONObject review=latestReview(a.mine("matches"));if(review!=null)a.card("From your latest match review",review(review),()->a.edit("matches",review,false));Map<String,Integer> focus=new LinkedHashMap<>();JSONObject missing=null;long cutoff=System.currentTimeMillis()-30*86400000L;for(JSONObject s:a.mine("trainingSessions")){long when=millis(s,"actualStart")>0?millis(s,"actualStart"):millis(s,"date");if(status("trainingSessions",s).equals("Completed")&&when>=cutoff&&when<=System.currentTimeMillis()){count(focus,s);if(focus(s).isEmpty())missing=s;}}for(Map.Entry<String,Integer> f:focus.entrySet())a.note(f.getKey()+": "+f.getValue()+" sessions in the last 30 days");if(missing!=null){JSONObject session=missing;a.button("Choose training focus",()->a.edit("trainingSessions",session,false));}a.button("Edit goals and priorities",()->a.edit("players",p,false));a.button("Plan next training session",()->a.edit("trainingSessions",null,false));if(TrackingMode.power(a.store))a.button("Preview coach summary",()->a.coachSummary(30));}
}
