package com.courtstory.app;

import android.app.AlertDialog;
import android.widget.*;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Draft-only participant creation and match links commit together with their session. */
final class TrainingLinks {
    static List<JSONObject> people(MainActivity a,JSONObject session){List<JSONObject> people=rows(a.store.table("players"));people.addAll(rows(array(session,"androidPendingPlayers")));return people;}
    static String participantLabel(MainActivity a,JSONObject session){List<String> names=new ArrayList<>();JSONArray ids=array(object(session,"context"),"participantIDs");for(JSONObject p:people(a,session))for(int i=0;i<ids.length();i++)if(p.optString("id").equals(ids.optString(i)))names.add(playerName(p));return names.isEmpty()?"Participants: None selected":"Participants: "+String.join(", ",names);}
    static void addParticipant(MainActivity a,JSONObject session,String name){String clean=name.trim();if(clean.isEmpty())throw new IllegalArgumentException("Enter a participant name.");JSONObject person=obj();put(person,"id",id());put(person,"name",clean);put(person,"role","Player");put(person,"playerType","Sighted");put(person,"sightLevel","Not known");put(person,"trackingMode","Basic");put(person,"sport",session.optString("sport","Tennis"));SportProfiles.select(person,session.optString("sport","Tennis"));if(ProfileSetup.coach(a.store.player()))put(person,"coachProfileID",a.store.player().optString("id"));array(session,"androidPendingPlayers").put(person);array(object(session,"context"),"participantIDs").put(person.optString("id"));}
    static void participants(MainActivity a,JSONObject session){
        Button choose=a.button(participantLabel(a,session),()->{});
        choose.setOnClickListener(v->{List<JSONObject> people=people(a,session);people.removeIf(p->p.optString("id").equals(session.optString("playerID")));JSONArray existing=array(object(session,"context"),"participantIDs");Set<String> selected=new LinkedHashSet<>();for(int i=0;i<existing.length();i++)selected.add(existing.optString(i));String[] labels=new String[people.size()];boolean[] checks=new boolean[people.size()];for(int i=0;i<people.size();i++){labels[i]=playerName(people.get(i));checks[i]=selected.contains(people.get(i).optString("id"));}new AlertDialog.Builder(a).setTitle("Players present").setMultiChoiceItems(labels,checks,(d,w,on)->{String id=people.get(w).optString("id");if(on)selected.add(id);else selected.remove(id);}).setNegativeButton("Cancel",null).setPositiveButton("Use selection",(d,w)->{put(object(session,"context"),"participantIDs",new JSONArray(selected));choose.setText(participantLabel(a,session));}).show();});
        a.button("Add a participant profile",()->{EditText input=new EditText(a);input.setHint("Participant name");input.setContentDescription("Participant name");input.setSingleLine(true);input.setMinHeight(a.dp(48));AlertDialog dialog=new AlertDialog.Builder(a).setTitle("New participant").setMessage("This player profile is created when you save the session. You can add their playing and access preferences afterward.").setView(input).setNegativeButton("Cancel",null).setPositiveButton("Add to session",null).create();dialog.setOnShowListener(x->dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{addParticipant(a,session,input.getText().toString());choose.setText(participantLabel(a,session));dialog.dismiss();}catch(IllegalArgumentException error){input.setError(error.getMessage());}}));dialog.show();});
        a.toggle(object(session,"context"),"participantsNeedDetails","More participants still to add",false);
    }
    static boolean eligible(JSONObject match,JSONObject session){if(!match.optString("sport","Tennis").equals(session.optString("sport","Tennis")))return false;if(match.optString("trainingSessionID").equals(session.optString("id"))||match.optString("playerID").equals(session.optString("playerID")))return true;JSONArray participants=array(object(session,"context"),"participantIDs");for(int i=0;i<participants.length();i++)if(participants.optString(i).equals(match.optString("playerID")))return true;return false;}
    static void matches(MainActivity a,JSONObject session){a.optional("Linked practice matches",()->{if(!session.has("androidLinkedMatchIDs")){JSONArray selected=new JSONArray();for(JSONObject match:rows(a.store.table("matches")))if(match.optString("trainingSessionID").equals(session.optString("id")))selected.put(match.optString("id"));put(session,"androidLinkedMatchIDs",selected);}Button choose=a.button("Choose linked matches",()->{});choose.setOnClickListener(v->{List<JSONObject> matches=new ArrayList<>();for(JSONObject match:rows(a.store.table("matches")))if(eligible(match,session))matches.add(match);if(matches.isEmpty()){a.error("No matches are available for this session’s players and sport. You can also link a match from its details.");return;}JSONArray saved=array(session,"androidLinkedMatchIDs");Set<String> selected=new LinkedHashSet<>();for(int i=0;i<saved.length();i++)selected.add(saved.optString(i));String[] labels=new String[matches.size()];boolean[] checks=new boolean[matches.size()];for(int i=0;i<matches.size();i++){JSONObject match=matches.get(i);labels[i]=title("matches",match)+" · "+date(match,"date",false);checks[i]=selected.contains(match.optString("id"));}new AlertDialog.Builder(a).setTitle("Practice matches").setMultiChoiceItems(labels,checks,(d,w,on)->{String id=matches.get(w).optString("id");if(on)selected.add(id);else selected.remove(id);}).setNegativeButton("Cancel",null).setPositiveButton("Use selection",(d,w)->{put(session,"androidLinkedMatchIDs",new JSONArray(selected));choose.setText("Linked matches: "+selected.size());}).show();});a.note("Links update only when you save this session. Selecting a match moves it from any previous linked session. Practice matches remain separate from competitive match totals.");});}
}
