package com.courtstory.app;
import org.json.*;
import java.io.*;
import static com.courtstory.app.Domain.*;

final class WatchConnection {
    static void show(MainActivity a){a.current=()->show(a);a.page(a.getPackageManager().hasSystemFeature("android.hardware.type.watch")?"Phone connection":"Watch connection","Court Story on phone and watch");a.note("Optional synchronisation copies your records between your paired devices. Google Play services manages encrypted delivery and may use Google servers when Bluetooth is unavailable. Court Story has no developer-run account or storage server. Photos and videos stay on the phone.");
        boolean enabled=WatchTransport.enabled(a);a.button(enabled?"Disable watch connection":"Enable encrypted watch connection",()->{if(enabled){a.getSharedPreferences("watch-connection",0).edit().putBoolean("enabled",false).apply();show(a);}else a.confirm("Enable watch connection?","Your Court Story library, including any recorded health and access information, will be sent to the app on your paired device using Google's encrypted transport. This can pass through Google servers. You can continue using both apps separately without enabling it.",()->{a.getSharedPreferences("watch-connection",0).edit().putBoolean("enabled",true).apply();show(a);});});
        if(enabled)a.button("Send my latest records",()->WatchTransport.send(a,message->a.runOnUiThread(()->a.announce(message))));
        a.note(a.getSharedPreferences("watch-connection",0).getString("status","No incoming transfer yet."));
        if(WatchTransport.inbox(a).exists())a.button("Review and merge incoming records",()->a.confirm("Merge incoming records?","Matching records are reconciled with the last connection. Conflicting edits are retained for review. A different existing library is never replaced.",()->{try{for(String t:new String[]{"trainingSessions","matches"})for(JSONObject record:rows(a.store.table(t)))if(active(record))throw new IOException("Finish active scoring and training before merging incoming records.");if(array(a.store.data,"androidWatchConflicts").length()>0)throw new IOException("Review existing conflicting versions first.");JSONObject incoming=WatchTransport.read(WatchTransport.inbox(a)),baseline=WatchTransport.read(WatchTransport.baseline(a));Store latest=new Store(a);JSONObject merged=WatchMerge.merge(latest.data,incoming,baseline);latest.data=merged;latest.save();WatchTransport.write(WatchTransport.baseline(a),merged);a.store=latest;if(!WatchTransport.inbox(a).delete())throw new IOException("Records merged; incoming transfer could not be dismissed.");a.getSharedPreferences("watch-connection",0).edit().putString("status","Records merged. Any conflicting versions remain available below.").apply();show(a);}catch(Exception e){a.error(e.getMessage()==null?"Incoming records could not be merged.":e.getMessage());}}));
        if(a.store!=null)for(JSONObject conflict:rows(array(a.store.data,"androidWatchConflicts"))){String table=conflict.optString("table");JSONObject local=conflict.optJSONObject("local"),incoming=conflict.optJSONObject("incoming");a.heading("Conflicting "+title(table,local));a.note("This device: "+summary(table,local)+"\nIncoming: "+(incoming==null?"Deleted on the other device":summary(table,incoming)));a.button("Keep this device's version",()->resolve(a,conflict,false));a.button("Use incoming version",()->a.confirm("Use incoming version?","The other version is retained in the local sync history for recovery.",()->resolve(a,conflict,true)));}
        a.button("Back to Court Story",()->{if(a.store!=null&&a.store.player()!=null)a.home();else a.welcome();});
    }
    static void resolve(MainActivity a,JSONObject conflict,boolean incoming){try{JSONObject next=copy(a.store.data);array(next,"androidWatchResolvedHistory").put(copy(conflict));JSONArray items=array(next,"androidWatchConflicts");for(int i=items.length()-1;i>=0;i--)if(items.optJSONObject(i).optString("id").equals(conflict.optString("id")))items.remove(i);if(incoming){JSONObject value=conflict.optJSONObject("incoming");if(value==null)throw new IOException("Delete this record from its normal details screen after reviewing linked records.");upsert(next,conflict.optString("table"),copy(value));}String issue=validate(next,false);if(issue!=null)throw new IOException(issue);JSONObject previous=a.store.data;a.store.data=next;if(!a.save()){a.store.data=previous;return;}WatchTransport.write(WatchTransport.baseline(a),next);show(a);}catch(Exception e){a.error(e.getMessage());}}
}
