package com.courtstory.app;
import android.app.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;
import com.google.android.apps.common.testing.accessibility.framework.*;
import com.google.android.apps.common.testing.accessibility.framework.uielement.AccessibilityHierarchyAndroid;

/** Populated player/coach regression scenarios in the isolated application only. */
public class AuditFlowTest extends DeviceFlowTest {
    public void testCoachWorkspaceKeepsPlayerAndPeriodAfterRecreation() throws Exception {
        seed();final String[] owner={null};ui(()->{owner[0]=a.store.player().optString("id");JSONObject coach=profile("QA Continuity Coach","Coach");put(coach,"trackingMode","Power");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));a.save();});
        for(String section:new String[]{"roster","schedule","overview","player","capture","records","journal","development","media"}){
            ui(()->{Bundle state=new Bundle();state.putString("screenTable","workspace:"+section);state.putString("screenRecord",owner[0]);state.putInt("screenDays",90);assertTrue(a.restoreScreen(state));});
            recreateScreen();ui(()->{assertEquals("workspace:"+section,a.screenTable);if(!Arrays.asList("roster","schedule","overview").contains(section))assertEquals(owner[0],a.screenRecord);if(section.equals("player"))assertNotNull(findButton(a.root,"Period: 90 days"));});
        }
    }
    public void testPlayerReportAndMediaFeedbackRetainEditedWords() throws Exception {
        seed();ui(()->{mode("Coach","Power");CoachInsights.report(a,a.store.player(),90,CoachInsights.metrics(a.store,a.store.player(),90));fill("text","QA Carefully edited player report");});recreateScreen();
        ui(()->{assertEquals("playerReport",a.draftTable);assertEquals(90,a.draft.optInt("days"));assertEquals("QA Carefully edited player report",a.draft.optString("text"));JSONObject preview=obj();put(preview,"text","QA Personalised clip feedback");MediaLibrary.feedbackDraft(a,a.store.player(),preview);});recreateScreen();
        ui(()->{assertEquals("mediaFeedback",a.draftTable);assertEquals("QA Personalised clip feedback",a.draft.optString("text"));assertNotNull(findButton(a.root,"Share reviewed text"));});
    }
    public void testPolicyReadingPositionSurvivesRecreation() throws Exception {
        seed();ui(a::privacy);final int[] position={0};ui(()->{a.scroll.scrollTo(0,700);position[0]=a.scroll.getScrollY();assertTrue(position[0]>0);});recreateScreen();ui(()->{assertEquals("Privacy",a.screenName);assertEquals(position[0],a.scroll.getScrollY());});
    }
    void agreeToSetupTerms(){for(int i=0;i<a.body.getChildCount();i++)if(a.body.getChildAt(i) instanceof Switch&&((Switch)a.body.getChildAt(i)).getText().toString().startsWith("I agree"))((Switch)a.body.getChildAt(i)).setChecked(true);assertTrue(TermsPolicy.accepted(a.draft));}
    void mode(String role,String mode){JSONObject p=copy(a.store.player());put(p,"role",role);put(p,"trackingMode",mode);assertTrue(a.saveRecord("players",p));}
    void fill(String key,String value){for(Map<String,EditText> fields:a.boundFields.values())if(fields.containsKey(key)){fields.get(key).setText(value);return;}fail("Missing field "+key);}
    void snapshot(String name){try{android.graphics.Bitmap image=android.graphics.Bitmap.createBitmap(a.root.getWidth(),a.root.getHeight(),android.graphics.Bitmap.Config.ARGB_8888);a.root.draw(new android.graphics.Canvas(image));try(java.io.FileOutputStream stream=new java.io.FileOutputStream(new java.io.File(a.getExternalFilesDir(null),name+".png"))){image.compress(android.graphics.Bitmap.CompressFormat.PNG,100,stream);}image.recycle();}catch(Exception e){throw new AssertionError(e);}}
    void accessibility(){AccessibilityHierarchyAndroid h=accessibilityHierarchy();List<String> errors=new ArrayList<>();for(AccessibilityHierarchyCheck check:AccessibilityCheckPreset.getAccessibilityHierarchyChecksForPreset(AccessibilityCheckPreset.LATEST))for(AccessibilityHierarchyCheckResult result:check.runCheckOnHierarchy(h))if(result.getType()==AccessibilityCheckResult.AccessibilityCheckResultType.ERROR)errors.add(check.getClass().getSimpleName()+": "+result.getMessage(Locale.UK));assertTrue(errors.toString(),errors.isEmpty());}
    void populate(){JSONObject player=a.store.player();for(int i=0;i<6;i++){JSONObject m=a.newRecord("matches");put(m,"opponentName","Demo opponent "+i);put(m,"status","Completed");put(m,"date",java.time.Instant.now().minusSeconds(i*86400L).toString());put(m,"setScores",i%2==0?"6-4":"4-6");put(m,"aces",i+1);put(m,"notes","Private reflection from Power");a.commit("matches",m);JSONObject t=a.newRecord("trainingSessions");put(t,"date",java.time.Instant.now().minusSeconds(i*604800L).toString());put(t,"androidScheduled",false);put(t,"durationMinutes",30+i*10);put(t,"focus","Serving");put(t,"energyLevel","High");a.commit("trainingSessions",t);}JSONObject tournament=a.newRecord("tournaments");put(tournament,"name","Demo Club Open");put(tournament,"finishingPosition",3);put(tournament,"finalResult","Completed");a.commit("tournaments",tournament);}
    public void testAllSixModeRoleCombinations(){seed();ui(this::populate);for(String role:new String[]{"Player","Coach"})for(String tier:new String[]{"Basic","Standard","Power"}){boolean guided=!tier.equals("Basic"),power=tier.equals("Power");ui(()->{mode(role,tier);a.home();audit(a.root);a.edit("matches",null,false);assertEquals(guided,findButtonPrefix(a.root,"Reflection")!=null);assertEquals(power,findButtonPrefix(a.root,"Advanced match statistics")!=null);assertNotNull(findButtonPrefix(a.root,"Recorded result"));assertEquals("Not recorded",a.draft.optString("result"));a.edit("trainingSessions",null,false);assertEquals(guided,findButtonPrefix(a.root,"Focus and reflection")!=null);assertEquals(power,findButtonPrefix(a.root,"Wellness")!=null);assertEquals(guided&&role.equals("Coach"),findButtonPrefix(a.root,"Coaching plan")!=null);a.reports();assertEquals(power,findText(a.root,"Advanced match totals"));assertEquals(guided,findText(a.root,"Focus balance"));a.detail("matches",a.store.table("matches").optJSONObject(0));assertEquals(power,findText(a.root,"Aces: 1"));assertEquals(guided,findText(a.root,"Notes: Private reflection from Power"));a.home();});accessibility();ui(()->snapshot("audit-"+role+"-"+tier));}}
    public void testCoachTiersAndSubjectScope(){seed();ui(this::populate);ui(()->{JSONObject athlete=copy(a.store.player());JSONObject coach=profile("DEMO Coach Morgan","Coach");put(coach,"trackingMode","Power");put(coach,"sports",new JSONArray(Arrays.asList("Tennis","Padel")));a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));for(String tier:new String[]{"Basic","Standard","Power"}){mode("Coach",tier);CoachInsights.player(a,athlete,30);assertEquals(tier.equals("Power"),findText(a.root,"Recorded match statistics"));assertEquals(tier.equals("Power"),findText(a.root,"Training rhythm"));assertEquals(!tier.equals("Basic"),findText(a.root,"Development plan"));CoachWorkspace.capturePage(a,athlete);assertEquals(!tier.equals("Basic"),findButtonPrefix(a.root,"Quick")!=null);if(!tier.equals("Basic")){CoachWorkspace.journal(a,athlete);assertEquals(tier.equals("Power"),findButton(a.root,"Record a measured drill")!=null);}}mode("Coach","Power");JSONObject current=copy(a.store.player());SportProfiles.select(current,"Padel");a.saveRecord("players",current);CoachInsights.player(a,athlete,30);findButton(a.root,"Plan this player's next session").performClick();assertEquals("Padel",a.draft.optString("sport"));assertEquals(athlete.optString("id"),a.draft.optString("playerID"));assertEquals(0,CoachInsights.metrics(a.store,athlete,30,"Padel").matches);});}
    public void testModeSettingsAndProfileStayConsistent() throws Exception {seed();ui(()->{mode("Player","Power");a.settings();assertEquals("Power",a.draft.optString("trackingMode"));put(a.draft,"trackingMode","Basic");findButton(a.root,"Save settings").performClick();assertEquals("Basic",a.store.player().optString("trackingMode"));JSONObject second=profile("DEMO Standard player","Player");put(second,"trackingMode","Standard");a.saveRecord("players",second);put(a.store.data,"selectedPlayerID",second.optString("id"));a.save();assertEquals("Standard",TrackingMode.current(a.store));a.settings();assertEquals("Standard",a.draft.optString("trackingMode"));});Store loaded=new Store(getInstrumentation().getTargetContext());assertEquals("Standard",TrackingMode.current(loaded));}
    public void testDowngradePreservesStatisticsAndFinishingPosition(){seed();ui(()->{mode("Player","Power");populate();JSONObject match=a.store.table("matches").optJSONObject(0),tournament=a.store.table("tournaments").optJSONObject(0);mode("Player","Basic");a.edit("matches",match,false);fill("opponentName","Updated opponent");findButton(a.root,"Save record").performClick();assertEquals(1,find(a.store.table("matches"),match.optString("id")).optInt("aces"));assertEquals("Private reflection from Power",find(a.store.table("matches"),match.optString("id")).optString("notes"));a.edit("tournaments",tournament,false);findButton(a.root,"Save record").performClick();assertEquals(3,find(a.store.table("tournaments"),tournament.optString("id")).optInt("finishingPosition"));mode("Player","Power");a.detail("matches",find(a.store.table("matches"),match.optString("id")));assertTrue(findText(a.root,"Aces: 1"));});}
    public void testBlankNumericIsUnknownAndResultNotInvented(){seed();ui(()->{mode("Player","Power");a.edit("matches",null,false);fill("opponentName","DEMO Unknown result");put(a.draft,"status","Completed");fill("aces","5");fill("aces","");assertFalse(a.draft.has("aces"));findButton(a.root,"Save record").performClick();JSONObject m=a.store.table("matches").optJSONObject(0);assertEquals("Not recorded",m.optString("result"));assertFalse(m.has("aces"));CoachInsights.Metrics metrics=CoachInsights.metrics(a.store,a.store.player(),0);assertEquals(1,metrics.matches);assertEquals(0,metrics.wins);assertEquals("Not recorded",metrics.winRate());a.reports();assertTrue(findText(a.root,"No advanced statistics recorded yet."));});}
    public void testCoachJournalSurvivesActivityRecreation() throws Exception {seed();ui(()->{mode("Coach","Power");CoachWorkspace.entry(a,a.store.player(),true);fill("title","DEMO Serve target");fill("observation","Controlled contact above shoulder");fill("successful","7");fill("attempts","10");});Instrumentation.ActivityMonitor monitor=getInstrumentation().addMonitor(MainActivity.class.getName(),null,false);ui(()->a.recreate());Activity recreated=monitor.waitForActivityWithTimeout(10000);getInstrumentation().removeMonitor(monitor);assertNotNull("Activity recreated",recreated);a=(MainActivity)recreated;setActivity(a);awaitOpened();ui(()->{assertEquals("journal",a.draftTable);assertEquals("DEMO Serve target",a.draft.optString("title"));assertEquals(7,a.draft.optInt("successful"));findButton(a.root,"Save journal entry").performClick();assertEquals(1,array(a.store.player(),"coachingJournal").length());});}
    public void testAccessibilityAcrossCoachModesAndThemes(){seed();for(String mode:new String[]{"Basic","Standard","Power"})for(String theme:new String[]{"Tennis","Classic","High Contrast"}){ui(()->{mode("Coach",mode);put(a.store.settings(),"theme",theme);a.palette();CoachInsights.player(a,a.store.player(),30);});accessibility();ui(()->a.edit("trainingSessions",null,false));accessibility();}}
    public void testEverySportAllModesPreservesCoreRecording(){seed();for(String tier:new String[]{"Basic","Standard","Power"})for(String sport:ProfileSetup.SPORTS)ui(()->{mode("Player",tier);JSONObject player=copy(a.store.player());SportProfiles.select(player,sport.equals("Custom")?"DEMO Court sport":sport);a.saveRecord("players",player);a.edit("matches",null,false);fill(sport.equals("Custom")?"eventName":"opponentName","DEMO Rival");String id=a.draft.optString("id");findButton(a.root,"Save record").performClick();assertNotNull(find(a.store.table("matches"),id));a.edit("trainingSessions",null,false);id=a.draft.optString("id");findButton(a.root,"Save record").performClick();assertNotNull(find(a.store.table("trainingSessions"),id));a.edit("tournaments",null,false);fill("name","DEMO "+sport+" tournament");id=a.draft.optString("id");findButton(a.root,"Save record").performClick();assertNotNull(find(a.store.table("tournaments"),id));});}
    void recreateScreen() throws Exception {Instrumentation.ActivityMonitor monitor=getInstrumentation().addMonitor(MainActivity.class.getName(),null,false);ui(()->a.recreate());Activity next=monitor.waitForActivityWithTimeout(10000);getInstrumentation().removeMonitor(monitor);assertNotNull(next);a=(MainActivity)next;setActivity(a);awaitOpened();}
    public void testLiveScoreAndReportSurviveRecreation() throws Exception {seed();ui(()->{JSONObject match=a.newRecord("matches");put(match,"opponentName","DEMO Rival");a.saveRecord("matches",match);a.scorer(match);findButton(a.root,"Point to QA Player").performClick();});recreateScreen();ui(()->{assertTrue(findText(a.root,"Live score"));assertNotNull(findButton(a.root,"Point to QA Player"));assertEquals(1,object(a.store.table("matches").optJSONObject(0),"liveScore").optInt("playerPoints"));a.reportsRange(30);});recreateScreen();ui(()->assertNotNull(findButton(a.root,"Period: 30 days")));}
    public void testMediaDoesNotCrossSportOrMode(){seed();ui(()->{mode("Player","Standard");JSONObject person=copy(a.store.player());JSONObject tennis=obj(),padel=obj();put(tennis,"id",id());put(tennis,"sport","Tennis");put(tennis,"title","DEMO Tennis serve");put(padel,"id",id());put(padel,"sport","Padel");put(padel,"title","DEMO Padel volley");array(person,"androidMedia").put(tennis).put(padel);a.saveRecord("players",person);MediaLibrary.show(a,person);assertNotNull(findButtonPrefix(a.root,"DEMO Tennis serve"));assertNull(findButtonPrefix(a.root,"DEMO Padel volley"));mode("Player","Basic");MediaLibrary.show(a,a.store.player());assertTrue(findText(a.root,"Today"));a.settings();assertNull(findButton(a.root,"Coach roster"));});}
    public void testFutureRecordsExcludedFromProgress(){seed();ui(()->{JSONObject match=a.newRecord("matches");put(match,"opponentName","DEMO Future opponent");put(match,"date",java.time.Instant.now().plusSeconds(86400).toString());put(match,"status","Completed");put(match,"result","Win");a.saveRecord("matches",match);JSONObject session=a.newRecord("trainingSessions");put(session,"date",java.time.Instant.now().plusSeconds(86400).toString());put(session,"androidScheduled",false);a.saveRecord("trainingSessions",session);CoachInsights.Metrics metrics=CoachInsights.metrics(a.store,a.store.player(),0);assertEquals(0,metrics.matches);assertEquals(0,metrics.sessions);assertEquals(0,ProgressCharts.workload(a.store,a.store.player(),"Tennis").get(5).minutes);});}
    public void testZZDemonstrationLibrary(){seed();ui(()->{String coachID="";for(String tier:new String[]{"Basic","Standard","Power"}){JSONObject coach=profile("DEMO Coach "+tier,"Coach");put(coach,"trackingMode",tier);put(coach,"coachLevel","Performance coach");if(tier.equals("Power")){PlayerCategory.select(coach,"Visually impaired");put(coach,"sightLevel",MainActivity.CLASSIFICATIONS[0]);coach.remove("bounceAllowance");}else if(tier.equals("Standard"))PlayerCategory.select(coach,"Wheelchair");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));populate();JSONObject player=profile("DEMO Player "+tier,"Player");put(player,"trackingMode",tier);put(player,"coachProfileID",coach.optString("id"));put(player,"primaryGoal","Improve first-serve placement");if(tier.equals("Power")){PlayerCategory.select(player,"Visually impaired");put(player,"sightLevel",MainActivity.CLASSIFICATIONS[2]);}else if(tier.equals("Standard")){PlayerCategory.select(player,"Deaf");put(player,"communicationPreferences","Use a visual ready signal and written session notes.");}a.saveRecord("players",player);put(a.store.data,"selectedPlayerID",player.optString("id"));populate();coachID=coach.optString("id");
        JSONObject customCoach=profile("DEMO Goalball Coach "+tier,"Coach");SportProfiles.select(customCoach,"Goalball");put(customCoach,"trackingMode",tier);a.saveRecord("players",customCoach);
        JSONObject customPlayer=profile("DEMO Goalball Player "+tier,"Player");SportProfiles.select(customPlayer,"Goalball");put(customPlayer,"trackingMode",tier);put(customPlayer,"coachProfileID",customCoach.optString("id"));a.saveRecord("players",customPlayer);
        for(JSONObject who:new JSONObject[]{customCoach,customPlayer}){put(a.store.data,"selectedPlayerID",who.optString("id"));for(int i=0;i<3;i++){JSONObject event=goalball();put(event,"eventName","DEMO Goalball "+(i==0?"live practice":"recorded game "+i));put(array(event,"customTeams").optJSONObject(0),"score",i+3);put(array(event,"customTeams").optJSONObject(1),"score",i+1);if(i>0){put(event,"status","Completed");put(event,"date",java.time.Instant.now().minusSeconds(i*86400L).toString());}a.commit("matches",event);}JSONObject practice=a.newRecord("trainingSessions");put(practice,"trainingType","Team practice");put(practice,"androidScheduled",false);put(practice,"focus","Defending");a.commit("trainingSessions",practice);}}
        put(a.store.data,"selectedPlayerID",coachID);a.save();a.home();assertEquals(13,a.store.table("players").length());assertEquals(54,a.store.table("matches").length());assertEquals(42,a.store.table("trainingSessions").length());assertEquals(6,a.store.table("tournaments").length());});ui(()->snapshot("demo-coach-dashboard"));}
    JSONObject goalball(){JSONObject e=a.newRecord("matches");put(e,"sport","Goalball");CustomScore.defaults(e);put(e,"customUnit","Goals");put(e,"customWinningRule","Lead by");put(e,"customTarget",10);put(e,"customPeriods",2);put(e,"customPeriodMinutes",12);put(array(e,"customTeams").optJSONObject(0),"name","DEMO Falcons");put(array(e,"customTeams").optJSONObject(1),"name","DEMO Owls");return e;}
    public void testCustomSportAllRolesAndTiers(){seed();assertFalse(Arrays.asList(ProfileSetup.SPORTS).contains("Goalball"));for(String role:new String[]{"Player","Coach"})for(String tier:new String[]{"Basic","Standard","Power"}){ui(()->{mode(role,tier);JSONObject p=copy(a.store.player());SportProfiles.select(p,"Goalball");a.saveRecord("players",p);JSONObject e=goalball();a.edit("matches",e,true);assertNull(findButtonPrefix(a.root,"Scoring rules"));assertNotNull(findButton(a.root,"Add another player or team"));findButton(a.root,"Add another player or team").performClick();assertEquals(3,array(a.draft,"customTeams").length());findButton(a.root,"Save record").performClick();JSONObject saved=find(a.store.table("matches"),e.optString("id"));assertNotNull(saved);a.scorer(saved);findButton(a.root,"Add 1 to DEMO Falcons").performClick();findButton(a.root,"Add 1 to Team 3").performClick();findButton(a.root,"Undo last scoring action").performClick();JSONObject scored=find(a.store.table("matches"),e.optString("id"));assertEquals(1,array(scored,"customTeams").optJSONObject(0).optInt("score"));assertEquals(0,array(scored,"customTeams").optJSONObject(2).optInt("score"));assertFalse(findText(a.root,"Love"));});accessibility();}}
    public void testCustomScoreRecreationAndBackup() throws Exception {seed();final String[] id={""};ui(()->{JSONObject e=goalball();id[0]=e.optString("id");a.saveRecord("matches",e);a.scorer(e);findButton(a.root,"Add 1 to DEMO Falcons").performClick();findButton(a.root,"Start period clock").performClick();});recreateScreen();ui(()->{assertNotNull(findButton(a.root,"Add 1 to DEMO Falcons"));findButton(a.root,"Pause period clock").performClick();snapshot("custom-goalball-scoreboard");});java.io.ByteArrayOutputStream backup=new java.io.ByteArrayOutputStream();BackupArchive.write(a,copy(a.store.data),backup);BackupArchive.Staged staged=BackupArchive.read(a,new java.io.ByteArrayInputStream(backup.toByteArray()));JSONObject event=find(table(staged.library,"matches"),id[0]);assertEquals(1,array(event,"customTeams").optJSONObject(0).optInt("score"));assertEquals(2,event.optInt("customPeriods"));assertEquals("Lead by",event.optString("customWinningRule"));BackupArchive.discard(staged.directory);}

    public void testCoachScheduleIncludesSubjectOwnedSessions(){seed();ui(()->{JSONObject athlete=copy(a.store.player()),coach=profile("DEMO Schedule Coach","Coach");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));JSONObject session=CoachWorkspace.record(a,athlete,"trainingSessions");put(session,"date",java.time.Instant.now().plusSeconds(86400).toString());a.commit("trainingSessions",session);assertEquals(1,CoachWorkspace.sessions(a).size());a.home();assertNotNull(findButtonPrefix(a.root,title("trainingSessions",session)));JSONObject changed=copy(a.store.player());SportProfiles.select(changed,"Padel");a.saveRecord("players",changed);assertEquals(0,CoachWorkspace.sessions(a).size());});}
    public void testPartialStatisticsRemainUnknown(){seed();ui(()->{mode("Coach","Power");populate();CoachInsights.Metrics metrics=CoachInsights.metrics(a.store,a.store.player(),30);assertEquals(6,metrics.acesRecorded);assertEquals(0,metrics.errorsRecorded);CoachInsights.player(a,a.store.player(),30);assertTrue(findTextContaining(a.root,"Unforced errors: Not recorded"));a.reports();assertTrue(findTextContaining(a.root,"Unforced errors: Not recorded"));});}
    public void testMediaMomentSavesImmediatelyAndSurvivesRecreation() throws Exception {seed();ui(()->{mode("Coach","Power");JSONObject player=copy(a.store.player()),media=obj();put(media,"id",id());put(media,"fileName",media.optString("id")+".bin");put(media,"mime","image/png");put(media,"title","DEMO Serve frame");put(media,"description","A sample frame for testing feedback");array(player,"androidMedia").put(media);a.saveRecord("players",player);MediaLibrary.moment(a,player,media,4);fill("description","Finish balanced after contact");});recreateScreen();ui(()->{assertEquals("mediaMoment",a.draftTable);findButton(a.root,"Save key moment").performClick();JSONObject saved=array(a.store.player(),"androidMedia").optJSONObject(0);assertEquals(1,array(saved,"moments").length());assertEquals(4,array(saved,"moments").optJSONObject(0).optInt("seconds"));assertFalse(saved.has("pendingMoment"));});}
    static boolean findTextContaining(View view,String value){if(view instanceof TextView&&((TextView)view).getText().toString().contains(value))return true;if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++)if(findTextContaining(g.getChildAt(i),value))return true;}return false;}
    java.io.File syntheticClip() throws Exception {
        java.io.File output=new java.io.File(a.getCacheDir(),"DEMO-video.mp4");android.media.MediaCodec codec=android.media.MediaCodec.createEncoderByType("video/avc");
        android.media.MediaFormat format=android.media.MediaFormat.createVideoFormat("video/avc",160,120);format.setInteger(android.media.MediaFormat.KEY_COLOR_FORMAT,android.media.MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420Flexible);format.setInteger(android.media.MediaFormat.KEY_BIT_RATE,100000);format.setInteger(android.media.MediaFormat.KEY_FRAME_RATE,5);format.setInteger(android.media.MediaFormat.KEY_I_FRAME_INTERVAL,1);
        codec.configure(format,null,null,android.media.MediaCodec.CONFIGURE_FLAG_ENCODE);codec.start();android.media.MediaMuxer muxer=new android.media.MediaMuxer(output.getAbsolutePath(),android.media.MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);boolean muxing=false,done=false;int frame=0,track=-1;long deadline=System.currentTimeMillis()+15000;android.media.MediaCodec.BufferInfo info=new android.media.MediaCodec.BufferInfo();
        try{while(!done&&System.currentTimeMillis()<deadline){if(frame<=30){int input=codec.dequeueInputBuffer(10000);if(input>=0){if(frame==30)codec.queueInputBuffer(input,0,0,frame*200000L,android.media.MediaCodec.BUFFER_FLAG_END_OF_STREAM);else{java.nio.ByteBuffer bytes=codec.getInputBuffer(input);bytes.clear();byte[] pixels=new byte[160*120*3/2];Arrays.fill(pixels,0,160*120,(byte)(40+frame*5));Arrays.fill(pixels,160*120,pixels.length,(byte)128);bytes.put(pixels);codec.queueInputBuffer(input,0,pixels.length,frame*200000L,0);}frame++;}}
            int index=codec.dequeueOutputBuffer(info,10000);if(index==android.media.MediaCodec.INFO_OUTPUT_FORMAT_CHANGED){track=muxer.addTrack(codec.getOutputFormat());muxer.start();muxing=true;}else if(index>=0){java.nio.ByteBuffer data=codec.getOutputBuffer(index);if(info.size>0&&(info.flags&android.media.MediaCodec.BUFFER_FLAG_CODEC_CONFIG)==0){assertTrue(muxing);data.position(info.offset);data.limit(info.offset+info.size);muxer.writeSampleData(track,data,info);}done=(info.flags&android.media.MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0;codec.releaseOutputBuffer(index,false);}}
            assertTrue("Synthetic video encoded",done);
        }finally{codec.stop();codec.release();if(muxing)muxer.stop();muxer.release();}return output;
    }
    static VideoView videoView(View view){if(view instanceof VideoView)return (VideoView)view;if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++){VideoView video=videoView(g.getChildAt(i));if(video!=null)return video;}}return null;}
    public void testRealVideoPlaybackControlsAndDescribedBackup() throws Exception {
        seed();ui(()->mode("Coach","Power"));java.io.File clip=syntheticClip();JSONObject media=obj();put(media,"id",id());put(media,"fileName",media.optString("id")+".bin");put(media,"mime","video/mp4");put(media,"sport","Tennis");put(media,"title","DEMO Synthetic clip");put(media,"description","Synthetic changing grey frames to test playback. No player footage.");java.nio.file.Files.copy(clip.toPath(),MediaLibrary.file(a,media.optString("fileName")).toPath(),java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        ui(()->{JSONObject person=copy(a.store.player());array(person,"androidMedia").put(media);a.saveRecord("players",person);MediaLibrary.detail(a,person,media);assertTrue(findText(a.root,media.optString("description")));});
        java.util.concurrent.atomic.AtomicInteger duration=new java.util.concurrent.atomic.AtomicInteger();for(int i=0;i<100&&duration.get()<=0;i++){ui(()->duration.set(videoView(a.root).getDuration()));Thread.sleep(50);}assertTrue("Real video prepared",duration.get()>4000);
        ui(()->findButton(a.root,"Play video").performClick());Thread.sleep(650);ui(()->{assertTrue(videoView(a.root).getCurrentPosition()>0);findButton(a.root,"Pause video").performClick();assertFalse(videoView(a.root).isPlaying());findButton(a.root,"Forward 5 seconds").performClick();findButton(a.root,"Back 5 seconds").performClick();findButton(a.root,"Read playback position").performClick();});
        ui(()->videoView(a.root).seekTo(2200));Thread.sleep(600);ui(()->assertTrue("Paused seek completed before recreation: "+videoView(a.root).getCurrentPosition(),videoView(a.root).getCurrentPosition()>=1500));recreateScreen();
        java.util.concurrent.atomic.AtomicInteger restoredPosition=new java.util.concurrent.atomic.AtomicInteger();
        for(int wait=0;wait<100&&restoredPosition.get()<1500;wait++){ui(()->{assertEquals("media",a.screenTable);assertNotNull(videoView(a.root));restoredPosition.set(videoView(a.root).getCurrentPosition());});Thread.sleep(50);}
        assertTrue("Playback position restored after recreation: saved="+a.playbackPosition+", actual="+restoredPosition.get(),restoredPosition.get()>=1500);ui(()->assertFalse(videoView(a.root).isPlaying()));
        java.io.ByteArrayOutputStream backup=new java.io.ByteArrayOutputStream();BackupArchive.write(a,copy(a.store.data),backup);BackupArchive.Staged staged=BackupArchive.read(a,new java.io.ByteArrayInputStream(backup.toByteArray()));assertEquals(clip.length(),new java.io.File(staged.directory,media.optString("fileName")).length());BackupArchive.discard(staged.directory);
    }
 public void testCategoryDescriptionChangesForEverySportAndChoice(){seed();for(String sport:ProfileSetup.SPORTS)ui(()->{JSONObject p=copy(a.store.player());SportProfiles.select(p,sport.equals("Custom")?"DEMO Adaptive court sport":sport);a.page("Profile category test",sport);java.util.function.Consumer<String> select=PlayerCategory.controls(a,p,true);for(String category:ProfileSetup.TYPES){select.accept(category);assertEquals(category,p.optString("playerType"));assertNotNull(findButton(a.root,"Player type: "+category));assertTrue(findText(a.root,PlayerCategory.description(p)));assertFalse(findText(a.root,"Sighted is the default. Choose the category that suits you; all core tracking features remain available."));if(category.equals("Custom")){fill("customPlayerType","DEMO Individual category");assertTrue(findText(a.root,PlayerCategory.description(p)));}if(category.equals("Visually impaired"))assertFalse(p.optString("sightLevel").startsWith("Fully Sighted"));}PlayerCategory.select(p,"Visually impaired");a.saveRecord("players",p);a.edit("players",p,false);assertNotNull(findButton(a.root,"Player type: Visually impaired"));assertTrue(findText(a.root,PlayerCategory.description(p)));});}
 public void testOnboardingCategorySurvivesRecreationAndProfileSwitch() throws Exception {seed();final String[] selected={""};ui(()->{Onboarding.start(a,"Player");put(a.draft,"sport","Badminton");findButton(a.root,"Continue").performClick();fill("name","DEMO Adaptive player");PlayerCategory.select(a.draft,"Visually impaired");Onboarding.show(a,a.draft,1);assertNotNull(findButton(a.root,"Player type: Visually impaired"));assertTrue(findText(a.root,PlayerCategory.description(a.draft)));});recreateScreen();ui(()->{assertNotNull(findButton(a.root,"Player type: Visually impaired"));findButton(a.root,"Continue").performClick();assertEquals("Not known",a.draft.optString("sightLevel"));assertNull(findButtonPrefix(a.root,"Sight classification"));agreeToSetupTerms();findButton(a.root,"Enter my court").performClick();selected[0]=a.store.player().optString("id");JSONObject other=profile("DEMO Sighted profile","Player");a.saveRecord("players",other);put(a.store.data,"selectedPlayerID",other.optString("id"));a.home();put(a.store.data,"selectedPlayerID",selected[0]);a.save();a.edit("players",a.store.player(),false);assertNotNull(findButton(a.root,"Player type: Visually impaired"));});Store loaded=new Store(getInstrumentation().getTargetContext());assertEquals("Visually impaired",loaded.player().optString("playerType"));}
 public void testCoachAccessPreferencesAndPlayerRuleIndependence(){seed();ui(()->{mode("Coach","Power");JSONObject coach=copy(a.store.player());PlayerCategory.select(coach,"Wheelchair");put(coach,"bounceAllowance",4);put(coach,"adaptivePreferences","Step-free court access");a.saveRecord("players",coach);a.edit("players",coach,false);assertNotNull(findButtonPrefix(a.root,"My access preferences (optional)"));assertNotNull(findButton(a.root,"Access profile: Wheelchair"));JSONObject player=profile("DEMO Deaf athlete","Player");put(player,"playerType","Deaf");put(player,"communicationPreferences","Hand signal for ready");a.saveRecord("players",player);JSONObject own=a.newRecord("matches"),subject=CoachWorkspace.record(a,player,"matches");assertEquals(4,own.optInt("allowedBounces"));assertEquals(1,subject.optInt("allowedBounces"));assertEquals("Hand signal for ready",subject.optString("communicationPreferences"));assertFalse(subject.has("adaptivePreferences"));a.edit("matches",subject,false);fill("opponentName","DEMO Rival");fill("allowedBounces","3");findButton(a.root,"Save record").performClick();assertEquals(3,find(a.store.table("matches"),subject.optString("id")).optInt("allowedBounces"));assertFalse(player.has("bounceAllowance"));});}
 public void testOptionalCoachCategorySetup(){ui(()->{Onboarding.start(a,"Coach");findButton(a.root,"Continue").performClick();assertNotNull(findButtonPrefix(a.root,"My access preferences (optional)"));assertNotNull(findButton(a.root,"Access profile: Sighted"));fill("name","DEMO VI Coach");PlayerCategory.select(a.draft,"Visually impaired");findButton(a.root,"Continue").performClick();assertNotNull(findButton(a.root,"Access profile: Visually impaired"));assertEquals("Not known",a.draft.optString("sightLevel"));agreeToSetupTerms();findButton(a.root,"Enter my court").performClick();assertEquals("Coach",a.store.player().optString("role"));assertEquals("Visually impaired",a.store.player().optString("playerType"));});}
 public void testViCoachAndViPlayerSameDifferentAndPerMatchBouncePreferences(){seed();ui(()->{
 mode("Coach","Power");JSONObject coach=copy(a.store.player());PlayerCategory.select(coach,"Visually impaired");put(coach,"sightLevel",MainActivity.CLASSIFICATIONS[0]);put(coach,"bounceAllowance",4);a.saveRecord("players",coach);
 JSONObject player=profile("DEMO B3 athlete","Player");PlayerCategory.select(player,"Visually impaired");put(player,"sightLevel",MainActivity.CLASSIFICATIONS[2]);a.saveRecord("players",player);
 JSONObject classified=CoachWorkspace.record(a,player,"matches");assertEquals("Player B3 default is two, not coach override four",2,classified.optInt("allowedBounces"));assertEquals("B3 classification remains attached to player",MainActivity.CLASSIFICATIONS[2],classified.optString("sightLevel"));
 for(int preference:new int[]{4,5,0}){put(player,"bounceAllowance",preference);a.saveRecord("players",player);JSONObject subject=CoachWorkspace.record(a,player,"matches");assertEquals("Use subject preference even when same, different, or zero",preference,subject.optInt("allowedBounces",-1));assertEquals("Coach own play keeps its separate preference",4,a.newRecord("matches").optInt("allowedBounces"));}
 JSONObject event=CoachWorkspace.record(a,player,"matches");a.edit("matches",event,false);fill("opponentName","DEMO Mixed-allowance rival");fill("allowedBounces","3");fill("opponentAllowedBounces","1");findButton(a.root,"Save record").performClick();JSONObject saved=find(a.store.table("matches"),event.optString("id"));assertNotNull(saved);assertEquals(3,saved.optInt("allowedBounces"));assertEquals(1,saved.optInt("opponentAllowedBounces"));assertEquals(0,find(a.store.table("players"),player.optString("id")).optInt("bounceAllowance",-1));assertEquals(4,a.store.player().optInt("bounceAllowance"));assertEquals(0,CoachWorkspace.record(a,find(a.store.table("players"),player.optString("id")),"matches").optInt("allowedBounces",-1));
 JSONObject reloaded=find(newStore().table("matches"),event.optString("id"));assertEquals(3,reloaded.optInt("allowedBounces"));assertEquals(1,reloaded.optInt("opponentAllowedBounces"));
 });}
 Store newStore(){try{return new Store(getInstrumentation().getTargetContext());}catch(Exception e){throw new AssertionError(e);}}
 public void testCoachDefaultOneB1ThreeAndOnlyExplicitOverrides(){seed();ui(()->{mode("Coach","Basic");JSONObject coach=copy(a.store.player());PlayerCategory.select(coach,"Sighted");coach.remove("bounceAllowance");a.saveRecord("players",coach);assertEquals("Sighted coach tennis default",1,a.newRecord("matches").optInt("allowedBounces"));PlayerCategory.select(coach,"Visually impaired");put(coach,"sightLevel",MainActivity.CLASSIFICATIONS[0]);a.saveRecord("players",coach);assertEquals("B1 coach default without override",3,a.newRecord("matches").optInt("allowedBounces"));assertFalse(a.store.player().has("bounceAllowance"));put(coach,"bounceAllowance",4);a.saveRecord("players",coach);assertEquals("Four requires an explicit saved override",4,a.newRecord("matches").optInt("allowedBounces"));coach.remove("bounceAllowance");a.saveRecord("players",coach);assertEquals("Removing override restores B1 default",3,a.newRecord("matches").optInt("allowedBounces"));});}
    public void testEditedCoachSummarySurvivesRotation() throws Exception {seed();ui(()->{put(a.store.player(),"trackingMode","Power");a.save();a.coachSummary(90);fill("summaryText","QA Personalised coaching feedback");put(a.draft,"includeNotes",true);});recreateScreen();ui(()->{assertEquals("coachSummary",a.draftTable);assertEquals(90,a.draft.optInt("days"));assertTrue(a.draft.optBoolean("includeNotes"));assertEquals("QA Personalised coaching feedback",a.draft.optString("summaryText"));findButton(a.root,"Refresh preview with selected details").performClick();assertEquals("QA Personalised coaching feedback",a.draft.optString("summaryText"));});getInstrumentation().sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);}
    public void testPendingReportExportSurvivesRecreation() throws Exception {seed();byte[] expected="Type,Title\r\nMatch,QA report\r\n".getBytes(java.nio.charset.StandardCharsets.UTF_8);ui(()->{a.reports();a.exportBytes=expected;try{ExportDraft.stage(a);}catch(java.io.IOException e){throw new AssertionError(e);}});String file=a.pendingExportName;recreateScreen();assertEquals(file,a.pendingExportName);java.io.ByteArrayOutputStream out=new java.io.ByteArrayOutputStream();ExportDraft.writeTo(a,a.pendingExportName,out);assertTrue(java.util.Arrays.equals(expected,out.toByteArray()));ui(()->ExportDraft.discard(a));assertFalse(ExportDraft.file(a,file).exists());}

    void awaitBackup(BackupOperation.State expected) throws Exception {
        long deadline=android.os.SystemClock.uptimeMillis()+15000;
        final BackupOperation.State[] actual={null};
        do{ui(()->actual[0]=BackupOperation.get(a).state);if(actual[0]==expected)return;Thread.sleep(50);}while(android.os.SystemClock.uptimeMillis()<deadline);
        assertEquals(expected,actual[0]);
    }
    public void testBackupRestoreConfirmationSurvivesRotation() throws Exception {
        seed();java.io.File source=new java.io.File(a.getCacheDir(),"QA-rotation-backup.zip");
        try(java.io.OutputStream out=new java.io.FileOutputStream(source)){BackupArchive.write(a,copy(a.store.data),out);}
        ui(()->{a.store.data=newLibrary();a.save();a.welcome();BackupArchive.restore(a,android.net.Uri.fromFile(source));});
        awaitBackup(BackupOperation.State.READY);final BackupOperation[] before={null};ui(()->before[0]=BackupOperation.get(a));
        recreateScreen();ui(()->{assertSame(before[0],BackupOperation.get(a));assertEquals(BackupOperation.State.READY,BackupOperation.get(a).state);BackupOperation.get(a).commit();});
        awaitBackup(BackupOperation.State.IDLE);ui(()->{assertEquals("QA Player",playerName(a.store.player()));assertTrue(findText(a.root,"Today"));});
        assertEquals(1,new Store(a).table("players").length());source.delete();
    }
    public void testBackupExportSurvivesRotation() throws Exception {
        seed();java.io.File destination=new java.io.File(a.getCacheDir(),"QA-export-rotation.zip");
        ui(()->BackupArchive.export(a,android.net.Uri.fromFile(destination)));recreateScreen();awaitBackup(BackupOperation.State.IDLE);
        BackupArchive.Staged restored;try(java.io.InputStream in=new java.io.FileInputStream(destination)){restored=BackupArchive.read(a,in);}
        assertEquals("QA Player",playerName(table(restored.library,"players").optJSONObject(0)));BackupArchive.discard(restored.directory);destination.delete();
    }

    public void testMediaImportKeepsOwnerAndSportAcrossRotation() throws Exception {
        seed();java.io.File source=new java.io.File(a.getCacheDir(),"QA-import-rotation.bin");byte[] bytes=new byte[]{1,2,3,4,5};java.nio.file.Files.write(source.toPath(),bytes);
        String player=a.store.player().optString("id");ui(()->BackupOperation.get(a).importMedia(android.net.Uri.fromFile(source),"video/mp4",player,"Padel"));recreateScreen();awaitBackup(BackupOperation.State.IDLE);
        ui(()->{assertEquals("media",a.draftTable);assertEquals(player,a.mediaPlayerID);assertEquals("Padel",a.draft.optString("sport"));assertEquals("video/mp4",a.draft.optString("mime"));});
        java.io.File imported=MediaLibrary.file(a,a.draft.optString("fileName"));assertTrue(java.util.Arrays.equals(bytes,java.nio.file.Files.readAllBytes(imported.toPath())));assertEquals(0,array(a.store.player(),"androidMedia").length());imported.delete();source.delete();
    }

    void awaitOpened() throws Exception {long deadline=android.os.SystemClock.uptimeMillis()+15000;while(!a.libraryReady&&android.os.SystemClock.uptimeMillis()<deadline)Thread.sleep(25);assertTrue("Restored library opens",a.libraryReady);getInstrumentation().waitForIdleSync();}
    public void testLargeHistoryPaginationSearchAndRotation() throws Exception {
        seed();ui(()->{for(int i=0;i<125;i++){JSONObject match=a.newRecord("matches");put(match,"opponentName",String.format(java.util.Locale.ROOT,"QA Archive Rival %03d",i));put(match,"status","Completed");put(match,"setScores","6-4");upsert(a.store.data,"matches",match);}a.save();a.list("matches");assertTrue(findText(a.root,"Showing 1–50 of 125 records"));assertNotNull(findButton(a.root,"Next 50 records"));findButton(a.root,"Next 50 records").performClick();assertTrue(findText(a.root,"Showing 51–100 of 125 records"));});
        recreateScreen();ui(()->{assertEquals(50,a.listOffset);assertTrue(findText(a.root,"Showing 51–100 of 125 records"));EditText search=findSearch(a.root);assertNotNull(search);search.setText("Rival 124");assertTrue(findText(a.root,"Showing 1–1 of 1 records"));assertNull(findButton(a.root,"Next 50 records"));});
        recreateScreen();ui(()->{assertEquals("Rival 124",a.listQuery);assertTrue(findText(a.root,"Showing 1–1 of 1 records"));findSearch(a.root).setText("No such rival");assertTrue(findText(a.root,"No matching records. Try a different search."));});
    }
    EditText findSearch(View v){if(v instanceof EditText&&String.valueOf(((EditText)v).getHint()).startsWith("Search "))return (EditText)v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){EditText found=findSearch(((ViewGroup)v).getChildAt(i));if(found!=null)return found;}return null;}

    public void testConcurrentLibraryReadAndAtomicWrite() throws Exception {
        seed();Store writer=new Store(a);java.util.concurrent.atomic.AtomicReference<Throwable> error=new java.util.concurrent.atomic.AtomicReference<>();java.util.concurrent.CountDownLatch start=new java.util.concurrent.CountDownLatch(1);
        Thread save=new Thread(()->{try{start.await();for(int i=0;i<20;i++){put(writer.player(),"profileNotes","QA concurrent snapshot "+i+" "+"x".repeat(4096));writer.save();}}catch(Throwable t){error.set(t);}});
        Thread read=new Thread(()->{try{start.await();for(int i=0;i<40;i++){Store snapshot=new Store(a);assertEquals(1,snapshot.table("players").length());assertEquals("QA Player",playerName(snapshot.player()));assertNull(validate(snapshot.data,false));}}catch(Throwable t){error.set(t);}});
        save.start();read.start();start.countDown();save.join(15000);read.join(15000);assertFalse("Writes complete",save.isAlive());assertFalse("Reads complete",read.isAlive());if(error.get()!=null)throw new AssertionError(error.get());assertTrue(new Store(a).player().optString("profileNotes").startsWith("QA concurrent snapshot 19"));
    }

    public void testCoachedHistoryPaginationKeepsAthleteOwnership() throws Exception {
        seed();String[] owner={"",""};ui(()->{JSONObject athlete=copy(a.store.player());owner[0]=athlete.optString("id");for(int i=0;i<55;i++){JSONObject match=a.newRecord("matches");put(match,"opponentName","QA Coached Rival "+i);put(match,"status","Completed");put(match,"setScores","6-4");upsert(a.store.data,"matches",match);}JSONObject coach=profile("QA History Coach","Coach");owner[1]=coach.optString("id");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));a.save();JSONObject own=a.newRecord("matches");put(own,"opponentName","QA Coach Own Rival");a.saveRecord("matches",own);CoachWorkspace.records(a,athlete,"matches");assertTrue(findText(a.root,"Showing 1–50 of 55 records"));findButton(a.root,"Next 5 records").performClick();});
        recreateScreen();ui(()->{assertEquals(owner[0],a.listSubjectID);assertTrue(findText(a.root,"Showing 51–55 of 55 records"));findButton(a.root,"Add match").performClick();assertEquals(owner[0],a.draft.optString("playerID"));assertEquals(owner[1],a.draft.optString("enteredByCoachID"));});
    }

    public void testFilePickerResultSurvivesLoadingRecreation() throws Exception {
        seed();java.io.File source=new java.io.File(a.getCacheDir(),"QA-deferred-backup.zip");try(java.io.OutputStream out=new java.io.FileOutputStream(source)){BackupArchive.write(a,copy(a.store.data),out);}
        ui(()->{a.store.data=newLibrary();a.save();a.welcome();a.libraryReady=false;a.onActivityResult(202,Activity.RESULT_OK,new android.content.Intent().setData(android.net.Uri.fromFile(source)));assertEquals(1,a.deferredResults.size());assertEquals(BackupOperation.State.IDLE,BackupOperation.get(a).state);});
        recreateScreen();awaitBackup(BackupOperation.State.READY);ui(()->{assertEquals(0,a.deferredResults.size());BackupOperation.get(a).commit();});awaitBackup(BackupOperation.State.IDLE);assertEquals("QA Player",playerName(a.store.player()));source.delete();
    }
    public void testLegacyJsonBackupUsesRetainedRestoreFlow() throws Exception {
        seed();java.io.File source=new java.io.File(a.getCacheDir(),"QA-json-backup.json");java.nio.file.Files.write(source.toPath(),a.store.data.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));
        ui(()->{a.store.data=newLibrary();a.save();a.welcome();a.onActivityResult(202,Activity.RESULT_OK,new android.content.Intent().setData(android.net.Uri.fromFile(source)));});awaitBackup(BackupOperation.State.READY);recreateScreen();ui(()->BackupOperation.get(a).commit());awaitBackup(BackupOperation.State.IDLE);assertEquals("QA Player",playerName(a.store.player()));source.delete();
    }

    public void testExternalActionDuringLoadingKeepsUnsavedDraft() throws Exception {
        seed();ui(()->{a.edit("trainingSessions",null,false);put(a.draft,"notes","QA retained before shortcut");a.libraryReady=false;a.onNewIntent(new android.content.Intent(a,MainActivity.class).putExtra("courtAction","match"));assertEquals(1,a.deferredResults.size());});recreateScreen();ui(()->{assertEquals("trainingSessions",a.draftTable);assertEquals("QA retained before shortcut",a.draft.optString("notes"));assertEquals(0,a.deferredResults.size());});getInstrumentation().sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);
    }
    public void testTimelineKeepsLatestFiveAndSubjectScope(){seed();ui(()->{for(int i=0;i<7;i++){JSONObject m=a.newRecord("matches");put(m,"opponentName","QA Timeline Rival "+i);put(m,"status","Completed");put(m,"date",java.time.Instant.now().minusSeconds((i+1)*86400L).toString());put(m,"setScores","6-4");upsert(a.store.data,"matches",m);}JSONObject other=profile("QA Timeline Other","Player");a.saveRecord("players",other);JSONObject foreign=a.newRecord("matches");put(foreign,"playerID",other.optString("id"));put(foreign,"opponentName","QA Foreign Rival");put(foreign,"status","Completed");put(foreign,"date",java.time.Instant.now().minusSeconds(60).toString());put(foreign,"setScores","6-4");upsert(a.store.data,"matches",foreign);a.save();a.page("QA Timeline","");StoryTimeline.show(a,false);for(int i=0;i<5;i++)assertTrue(findTextContaining(a.root,"QA Timeline Rival "+i));assertFalse(findTextContaining(a.root,"QA Timeline Rival 5"));assertFalse(findTextContaining(a.root,"QA Timeline Rival 6"));assertFalse(findTextContaining(a.root,"QA Foreign Rival"));});}

    public void testSemanticFeedbackKeepsControlAndAccessibilityFocus(){seed();ui(()->{
        a.page("Feedback test","QA");Button control=a.button("Record point",()->{});
        control.performAccessibilityAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_ACCESSIBILITY_FOCUS,null);
        boolean wasFocused=control.isAccessibilityFocused();View root=a.root;
        a.announce("Point saved. 15–0.");assertSame(root,a.root);assertEquals(View.VISIBLE,a.feedback.getVisibility());
        assertEquals(View.ACCESSIBILITY_LIVE_REGION_POLITE,a.feedback.getAccessibilityLiveRegion());
        assertEquals("Point saved. 15–0.",a.feedback.getText().toString());if(wasFocused)assertTrue(control.isAccessibilityFocused());
        a.announce("Point saved. 15–0.");a.home();assertEquals(View.GONE,a.feedback.getVisibility());
    });getInstrumentation().waitForIdleSync();ui(()->assertEquals("",a.feedback.getText().toString()));accessibility();}
    public void testHistorySearchKeepsEditableValueAndAnnouncesResultCount(){seed();ui(()->{
        a.list("matches");EditText input=firstEditable(a.root);assertNotNull(input);assertNull(input.getContentDescription());
        input.setText("QA no matching match");android.view.accessibility.AccessibilityNodeInfo node=input.createAccessibilityNodeInfo();
        assertEquals("QA no matching match",node.getText().toString());node.recycle();boolean labelled=false;for(int i=0;i<a.body.getChildCount();i++)labelled|=a.body.getChildAt(i).getLabelFor()==input.getId();assertTrue("Search retains a persistent field label",labelled);
        assertTrue(findText(a.root,"No records yet. Add your first one above."));
    });accessibility();}
    private static EditText firstEditable(View view){if(view instanceof EditText)return (EditText)view;if(view instanceof ViewGroup){ViewGroup group=(ViewGroup)view;for(int i=0;i<group.getChildCount();i++){EditText input=firstEditable(group.getChildAt(i));if(input!=null)return input;}}return null;}
    public void testObservationBecomesEditableAthleteOwnedPractice(){seed();ui(()->{
        JSONObject athlete=profile("QA Practice athlete","Player");assertTrue(a.saveRecord("players",athlete));mode("Coach","Standard");
        JSONObject note=obj();put(note,"id",id());put(note,"date",now());put(note,"sport","Tennis");put(note,"title","Serve placement");put(note,"focus","Serve");put(note,"observation","First serve lands too centrally");put(note,"nextAction","Aim ten serves at wide targets");put(note,"playerFeedback","I rush the toss");
        int before=a.store.table("trainingSessions").length();CoachWorkspace.planFromObservation(a,athlete,note);
        assertEquals(before,a.store.table("trainingSessions").length());assertEquals(athlete.optString("id"),a.draft.optString("playerID"));assertEquals(a.store.player().optString("id"),a.draft.optString("enteredByCoachID"));assertEquals("Aim ten serves at wide targets",a.draft.optString("sessionObjectives"));assertTrue(a.draft.optString("notes").contains("I rush the toss"));
        fill("sessionObjectives","Editable targets agreed with player");findButton(a.root,"Save record").performClick();JSONObject saved=a.store.table("trainingSessions").optJSONObject(before);assertNotNull(saved);assertEquals("Editable targets agreed with player",saved.optString("sessionObjectives"));assertEquals(note.optString("id"),saved.optString("sourceObservationID"));
        mode("Coach","Basic");a.home();CoachWorkspace.planFromObservation(a,athlete,note);assertFalse(a.editing);
        mode("Coach","Standard");put(note,"measured",true);CoachWorkspace.planFromObservation(a,athlete,note);assertFalse(a.editing);
    });}
    public void testCoachingObservationsAreChronologicalAndSportScoped(){seed();ui(()->{
        JSONObject player=copy(a.store.player());JSONArray notes=array(player,"coachingJournal");
        for(String date:new String[]{"2024-03-01","2024-01-01","2024-02-01"}){JSONObject note=obj();put(note,"id",id());put(note,"date",date);put(note,"sport","Tennis");put(note,"title",date);notes.put(note);}
        JSONObject other=obj();put(other,"date","2025-01-01");put(other,"sport","Padel");notes.put(other);
        JSONObject measured=obj();put(measured,"date","2025-02-01");put(measured,"sport","Tennis");put(measured,"measured",true);notes.put(measured);
        List<JSONObject> standard=CoachWorkspace.observations(player,"Tennis",false);assertEquals(3,standard.size());assertEquals("2024-03-01",standard.get(0).optString("date"));assertEquals("2024-01-01",standard.get(2).optString("date"));assertEquals(4,CoachWorkspace.observations(player,"Tennis",true).size());assertEquals(1,CoachWorkspace.observations(player,"Padel",true).size());
        mode("Coach","Standard");CoachWorkspace.entry(a,player,false);fill("title","QA Player voice");fill("observation","Changed contact timing");fill("playerFeedback","The shorter cue helped");fill("nextAction","Repeat slowly");findButton(a.root,"Save journal entry").performClick();assertEquals("The shorter cue helped",array(a.store.player(),"coachingJournal").optJSONObject(0).optString("playerFeedback"));
    });}

    public void testTermsRequireExplicitSetupAgreementAndSurviveRecreation() throws Exception {
        ui(()->{Onboarding.start(a,"Player");put(a.draft,"name","QA Terms player");Onboarding.show(a,a.draft,2);assertFalse(TermsPolicy.accepted(a.draft));findButton(a.root,"Read terms and safe use").performClick();assertEquals("termsOnboarding",a.draftTable);assertEquals("QA Terms player",a.draft.optString("name"));});
        Instrumentation.ActivityMonitor monitor=getInstrumentation().addMonitor(MainActivity.class.getName(),null,false);ui(()->a.recreate());Activity recreated=monitor.waitForActivityWithTimeout(10000);getInstrumentation().removeMonitor(monitor);assertNotNull(recreated);a=(MainActivity)recreated;setActivity(a);awaitOpened();
        ui(()->{assertEquals("termsOnboarding",a.draftTable);assertEquals("Terms and safe use",a.screenName);a.handleBackPressed();assertEquals(2,a.setupStep);assertEquals("QA Terms player",a.draft.optString("name"));assertFalse(TermsPolicy.accepted(a.draft));for(int i=0;i<a.body.getChildCount();i++)if(a.body.getChildAt(i) instanceof Switch&&((Switch)a.body.getChildAt(i)).getText().toString().startsWith("I agree"))((Switch)a.body.getChildAt(i)).setChecked(true);assertTrue(TermsPolicy.accepted(a.draft));findButton(a.root,"Enter my court").performClick();assertEquals(TermsPolicy.VERSION,a.store.player().optString("acceptedTermsVersion"));assertFalse(a.store.player().has("androidTermsAgreed"));});
    }
    public void testPublicPolicyAndTermsAreAvailableOfflineAndAccessible(){seed();ui(()->{a.privacy();assertNotNull(findButton(a.root,"Open public privacy policy"));assertTrue(findText(a.root,"Developer and contact"));assertTrue(PrivacyPolicy.SECTIONS[0][1].contains("Sidney.Tambin@googlemail.com"));});accessibility();ui(()->TermsPolicy.show(a,a::more));accessibility();ui(()->{assertTrue(findText(a.root,"Record after play, in a safe place"));assertNotNull(findButton(a.root,"Back"));assertTrue(TermsPolicy.SECTIONS[7][1].contains("Nothing in these terms excludes"));});}
}
