package com.courtstory.app;

import android.app.*;
import android.content.*;
import android.os.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Release acceptance scenarios in the separate QA app, never the owner's library. */
public class BusinessAuditTest extends AuditFlowTest {
    public void testSelectedNavigationLabelsFitWithoutBrokenWords() throws Exception {
        seed();for(String selected:new String[]{"Today","Players","Progress","More"}){ui(()->{mode("Coach","Power");a.page("QA Navigation","");a.navigation(selected);});getInstrumentation().waitForIdleSync();accessibilityHierarchy();ui(()->{for(int i=0;i<a.nav.getChildCount();i++){android.view.ViewGroup row=(android.view.ViewGroup)a.nav.getChildAt(i);for(int j=0;j<row.getChildCount();j++){TextView tab=(TextView)row.getChildAt(j);assertNotNull(tab.getLayout());assertEquals("Navigation must not split a word: "+tab.getText(),1,tab.getLineCount());}}});}
    }

    public void testCoachingAchievementsSeparateSportCoachAndPersonalPractice() throws Exception {
        seed();ui(()->{mode("Coach","Power");JSONObject coach=a.store.player();String cid=coach.optString("id");List<JSONObject> people=new ArrayList<>();for(int i=0;i<3;i++){JSONObject p=profile("QA Award athlete "+i,"Player");a.saveRecord("players",p);people.add(p);}
            for(int i=0;i<10;i++){JSONObject r=CoachWorkspace.record(a,people.get(0),"trainingSessions");put(r,"date","2026-01-01T12:00:00Z");put(r,"androidScheduled",false);put(r,"durationMinutes",45);if(i==0)for(JSONObject p:people)array(object(r,"context"),"participantIDs").put(p.optString("id")).put(p.optString("id"));a.saveRecord("trainingSessions",r);}
            JSONObject personal=a.newRecord("trainingSessions");put(personal,"date","2026-01-01T12:00:00Z");put(personal,"androidScheduled",false);put(personal,"durationMinutes",30);put(personal,"enteredByCoachID",cid);a.saveRecord("trainingSessions",personal);
            for(int i=0;i<4;i++){JSONObject r=CoachWorkspace.record(a,people.get(0),"trainingSessions");put(r,"date","2026-01-01T12:00:00Z");put(r,"androidScheduled",false);put(r,"durationMinutes",30);if(i==0)put(r,"sport","Padel");if(i==1)put(r,"enteredByCoachID","another-coach");if(i==2)put(r,"androidScheduled",true);if(i==3)put(r,"date","2099-01-01T12:00:00Z");a.saveRecord("trainingSessions",r);}
            Map<String,Integer> counts=Achievements.counts(a);assertEquals(Integer.valueOf(10),counts.get("coachedSessions"));assertEquals(Integer.valueOf(3),counts.get("coachedPlayers"));assertEquals(Integer.valueOf(1),counts.get("training"));
            for(String tier:new String[]{"Basic","Standard","Power"}){mode("Coach",tier);Achievements.show(a);assertTrue(visibleText(a.root).contains("Earned. Your first coached session"));assertTrue(visibleText(a.root).contains("Earned. Ten coached sessions"));assertEquals(tier.equals("Basic")?"All 21 milestones":"All 25 milestones",Achievements.collectionLabel(a));}
            mode("Player","Power");Achievements.show(a);assertFalse(visibleText(a.root).contains("A Coaching Beginning"));assertEquals("All 22 milestones",Achievements.collectionLabel(a));mode("Coach","Power");a.save();
        });recreateScreen();ui(()->{assertEquals(Integer.valueOf(10),Achievements.counts(a).get("coachedSessions"));JSONObject p=copy(a.store.player());SportProfiles.select(p,"Goalball");put(p,"role","Coach");a.saveRecord("players",p);Achievements.show(a);assertEquals(Integer.valueOf(0),Achievements.counts(a).get("coachedSessions"));assertTrue(visibleText(a.root).contains("A Coaching Beginning"));assertFalse(visibleText(a.root).toLowerCase(Locale.ROOT).contains("tennis"));});accessibility();
    }
    public void testAllTwentyFiveBadgesHaveDistinctArtworkAndTextAlternatives() throws Exception {
        seed();ui(()->{mode("Coach","Power");try{assertEquals(25,Achievements.catalog(a).size());}catch(IOException e){throw new AssertionError(e);}Set<Integer> designs=new HashSet<>();android.graphics.Bitmap gallery=android.graphics.Bitmap.createBitmap(750,850,android.graphics.Bitmap.Config.ARGB_8888);android.graphics.Canvas canvas=new android.graphics.Canvas(gallery);canvas.drawColor(0xffddff28);android.graphics.Paint label=new android.graphics.Paint(3);label.setColor(0xff143127);label.setTextSize(15);label.setTextAlign(android.graphics.Paint.Align.CENTER);
            for(int i=0;i<25;i++){AchievementBadge badge=new AchievementBadge(a,i,true);assertEquals(android.view.View.IMPORTANT_FOR_ACCESSIBILITY_NO,badge.getImportantForAccessibility());badge.layout(0,0,130,130);android.graphics.Bitmap icon=android.graphics.Bitmap.createBitmap(130,130,android.graphics.Bitmap.Config.ARGB_8888);badge.draw(new android.graphics.Canvas(icon));int[] pixels=new int[16900];icon.getPixels(pixels,0,130,0,0,130,130);assertTrue("Artwork must be unique: "+i,designs.add(Arrays.hashCode(pixels)));canvas.drawBitmap(icon,(i%5)*150+10,(i/5)*170+5,null);try{String title=Achievements.catalog(a).get(i)[1];String[] words=title.split(" ");int middle=(words.length+1)/2;canvas.drawText(String.join(" ",Arrays.copyOfRange(words,0,middle)),(i%5)*150+75,(i/5)*170+148,label);canvas.drawText(String.join(" ",Arrays.copyOfRange(words,middle,words.length)),(i%5)*150+75,(i/5)*170+165,label);}catch(IOException e){throw new AssertionError(e);}icon.recycle();}
            try(OutputStream out=new FileOutputStream(new File(a.getCacheDir(),"achievement-gallery.png"))){gallery.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}catch(IOException e){throw new AssertionError(e);}gallery.recycle();Achievements.show(a);assertTrue(visibleText(a.root).contains("0 of 25 earned"));assertTrue(visibleText(a.root).contains("0 of 1. Complete your first recorded coaching session"));
        });accessibility();
    }
    public void testOpeningAppRestoresPersistedReminderSchedule() throws Exception {seed();ReminderReceiver.awaitIdle();ui(()->{put(a.store.settings(),"weeklySummaryEnabled",true);try{a.store.save();}catch(IOException e){throw new AssertionError(e);}});recreateScreen();ReminderReceiver.awaitIdle();assertTrue(a.getSharedPreferences("alarms",0).getStringSet("ids",Collections.emptySet()).contains("weekly"));ui(()->{put(a.store.settings(),"weeklySummaryEnabled",false);a.save();});ReminderReceiver.awaitIdle();}
    public void testEarnedMilestonesRemainEarnedOutsideReportPeriod(){seed();ui(()->{JSONObject match=a.newRecord("matches");put(match,"date","2020-01-01T12:00:00Z");put(match,"status","Completed");put(match,"result","Not recorded");a.saveRecord("matches",match);a.reportsRange(7);assertTrue(visibleText(a.root).contains("0 completed competitive matches"));assertTrue(findText(a.root,"Earned — Game On"));Achievements.show(a);assertTrue(visibleText(a.root).contains("Earned. Your first match is logged."));});}
    public void testCoachingPaneAnnouncementsDistinguishPlayerScreens(){seed();ui(()->{mode("Coach","Power");CoachInsights.player(a,a.store.player(),30);String overview=a.root.getAccessibilityPaneTitle().toString();assertTrue(overview.contains("QA Player"));assertTrue(overview.contains("Tennis"));ProfileSetup.athlete(a,a.store.player());String development=a.root.getAccessibilityPaneTitle().toString();assertFalse(overview.equals(development));CoachWorkspace.journal(a,a.store.player());assertFalse(development.equals(a.root.getAccessibilityPaneTitle().toString()));});accessibility();}
    public void testMilestonesRespectSportModeAndRotation() throws Exception {
        seed();ui(()->{JSONObject p=copy(a.store.player());SportProfiles.select(p,"Padel");a.saveRecord("players",p);Achievements.show(a);String text=visibleText(a.root);assertFalse(text.contains("Apple Watch"));assertFalse(text.toLowerCase(java.util.Locale.ROOT).contains("tennis"));assertFalse(text.contains("Practice with Purpose"));assertFalse(text.contains("Pause and Reflect"));assertTrue(text.contains("Connected Workout"));});recreateScreen();ui(()->{assertEquals("Milestones",a.screenName);mode("Player","Power");Achievements.show(a);assertTrue(visibleText(a.root).contains("Practice with Purpose"));assertTrue(visibleText(a.root).contains("Pause and Reflect"));JSONObject p=copy(a.store.player());SportProfiles.select(p,"Goalball");a.saveRecord("players",p);Achievements.show(a);String text=visibleText(a.root).toLowerCase(java.util.Locale.ROOT);assertFalse(text.contains("singles"));assertFalse(text.contains("doubles"));assertTrue(text.contains("team court story"));assertTrue(text.contains("individual court story"));});accessibility();
    }
    String visibleText(android.view.View view){StringBuilder text=new StringBuilder();if(view instanceof TextView)text.append(((TextView)view).getText()).append('\n');if(view instanceof android.view.ViewGroup){android.view.ViewGroup group=(android.view.ViewGroup)view;for(int i=0;i<group.getChildCount();i++)text.append(visibleText(group.getChildAt(i)));}return text.toString();}
    public void testPlayerAndCoachReportsRespectModeAndIncludeAllStatistics(){seed();ui(()->{
        JSONObject match=a.newRecord("matches");put(match,"status","Completed");put(match,"result","Win");put(match,"date",java.time.Instant.now().minusSeconds(3600).toString());put(match,"aces",3);put(match,"doubleFaults",2);put(match,"winners",12);put(match,"unforcedErrors",7);a.saveRecord("matches",match);
        for(String tier:new String[]{"Basic","Standard","Power"}){mode("Player",tier);a.reports();String text=visibleText(a.root);assertTrue(text.contains("Results by match format"));assertTrue(text.contains("Singles"));assertTrue(text.contains("Doubles"));assertEquals(tier.equals("Power"),text.contains("%"));assertEquals(tier.equals("Power"),text.contains("Double faults: 2 across 1 match"));assertEquals(tier.equals("Power"),text.contains("Winners: 12 across 1 match"));mode("Coach",tier);CoachInsights.player(a,a.store.player(),30);assertEquals(tier.equals("Power"),visibleText(a.root).contains("%"));}
    });accessibility();}
    public void testFormatResultsCountLinkedAndEmbeddedPracticeOnlyOnce(){seed();ui(()->{
        JSONObject session=a.newRecord("trainingSessions");put(session,"androidScheduled",false);put(session,"date","2025-06-01T12:00:00Z");put(object(session,"practiceResult"),"kind","Doubles");put(object(session,"practiceResult"),"result","Loss");a.saveRecord("trainingSessions",session);
        JSONObject linked=a.newRecord("matches");put(linked,"date","2025-06-01T12:00:00Z");put(linked,"matchType","Doubles");put(linked,"status","Completed");put(linked,"result","Win");put(linked,"trainingSessionID",session.optString("id"));a.saveRecord("matches",linked);
        JSONObject singles=a.newRecord("matches");put(singles,"date","2025-07-01T12:00:00Z");put(singles,"status","Completed");put(singles,"result","Not recorded");a.saveRecord("matches",singles);
        JSONObject other=copy(singles);put(other,"id",id());put(other,"sport","Padel");a.saveRecord("matches",other);JSONObject later=copy(singles);put(later,"id",id());put(later,"date","2026-01-01T12:00:00Z");a.saveRecord("matches",later);
        Map<String,ReportFormats.Result> totals=ReportFormats.build(a.store.data,a.store.player(),"Tennis",-2025);assertEquals(1,totals.get("Doubles").count);assertEquals(1,totals.get("Doubles").wins);assertEquals(0,totals.get("Doubles").losses);assertEquals(1,totals.get("Doubles").practice);assertEquals(1,totals.get("Singles").unknown);assertEquals(1,totals.get("Singles").count);
        try{a.store.remove("matches",linked);}catch(IOException e){throw new AssertionError(e);}totals=ReportFormats.build(a.store.data,a.store.player(),"Tennis",-2025);assertEquals(1,totals.get("Doubles").count);assertEquals(1,totals.get("Doubles").losses);
    });}
    public void testCustomProgressDoesNotIntroduceTennisFormats(){seed();ui(()->{JSONObject person=copy(a.store.player());SportProfiles.select(person,"Goalball");a.saveRecord("players",person);JSONObject event=a.newRecord("matches");CustomScore.defaults(event);put(event,"status","Completed");put(event,"result","Draw");put(event,"date",java.time.Instant.now().minusSeconds(60).toString());a.saveRecord("matches",event);a.reports();String text=visibleText(a.root);assertTrue(text.contains("Results by event format"));assertTrue(text.contains("Team events"));assertFalse(text.contains("Singles"));assertFalse(text.contains("Doubles"));Map<String,ReportFormats.Result> result=ReportFormats.build(a.store.data,a.store.player(),"Goalball",0);assertEquals(1,result.get("Team events").draws);});}
    public void testScoringWriteFailureKeepsUndoAndRetryAccurate() throws Exception {
        seed();final Store real=a.store;final Scoring[] score={null};
        ui(()->{JSONObject r=a.newRecord("matches");score[0]=new Scoring(r);score[0].point(true);score[0].point(true);a.saveRecord("matches",r);});
        File blocker=new File(a.getCacheDir(),"qa-unwritable-library-parent");try(FileOutputStream out=new FileOutputStream(blocker)){out.write(1);}
        Store failing=new Store(new android.content.ContextWrapper(a){@Override public File getFilesDir(){return blocker;}});failing.data=copy(real.data);
        for(int operation=0;operation<4;operation++){final int action=operation;ui(()->{a.store=failing;String before=score[0].match.toString();int history=score[0].history.length();assertFalse(a.saveScore(score[0],()->{switch(action){case 0:score[0].undo();break;case 1:score[0].point(false);break;case 2:score[0].startTie();break;default:score[0].finishEarly("Retired");}}));assertEquals(before,score[0].match.toString());assertEquals(history,score[0].history.length());assertFalse(score[0].complete());});getInstrumentation().sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);}
        ui(()->{a.store=real;assertTrue(a.saveScore(score[0],()->score[0].undo()));assertEquals(1,score[0].n("playerPoints"));assertEquals(1,score[0].history.length());});
        JSONObject saved=find(new Store(a).table("matches"),score[0].match.optString("id"));assertEquals(1,object(saved,"liveScore").optInt("playerPoints"));blocker.delete();
    }
    public void testExtendedScoringHistoryPersistsAndFullyUndoes() throws Exception {
        seed();final String[] match={null};ui(()->{JSONObject r=a.newRecord("matches");Scoring score=new Scoring(r);for(int i=0;i<1000;i++)score.point(i%2==0);assertFalse(score.complete());assertEquals("Deuce",score.points());assertEquals(1000,score.history.length());assertTrue(a.saveRecord("matches",r));match[0]=r.optString("id");});
        Store loaded=new Store(a);Scoring score=new Scoring(find(loaded.table("matches"),match[0]));for(int i=0;i<1000;i++)assertTrue(score.undo());assertFalse(score.undo());assertEquals(0,score.n("playerPoints"));assertEquals(0,score.n("opponentPoints"));assertEquals(0,score.history.length());loaded.saveRecord("matches",score.match);assertEquals(0,array(find(new Store(a).table("matches"),match[0]),"androidScoreHistory").length());
    }
    JSONObject athlete;
    void multiSportCoach(){
        athlete=copy(a.store.player());put(athlete,"primaryGoal","Tennis first serve");put(athlete,"developmentNotes","Tennis plan");put(athlete,"nextReviewDate","2001-01-01");
        SportProfiles.select(athlete,"Padel");put(athlete,"primaryGoal","Padel wall recovery");put(athlete,"developmentNotes","Padel plan");put(athlete,"nextReviewDate","2099-01-01");SportProfiles.select(athlete,"Tennis");a.saveRecord("players",athlete);
        JSONObject coach=profile("QA Padel coach","Coach");put(coach,"trackingMode","Power");SportProfiles.select(coach,"Padel");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));a.save();
    }
    public void testMultisportGoalsReportsAndReviewDatesStaySeparate(){seed();ui(()->{
        multiSportCoach();CoachInsights.player(a,athlete,30);assertTrue(findText(a.root,"Goal: Padel wall recovery\nPadel plan"));assertFalse(findText(a.root,"Goal: Tennis first serve\nTennis plan"));
        CoachInsights.report(a,athlete,30,CoachInsights.metrics(a.store,athlete,30,"Padel"));assertTrue(a.draft.optString("text").contains("Padel wall recovery"));assertFalse(a.draft.optString("text").contains("Tennis first serve"));
        a.home();assertFalse(findText(a.root,"Development reviews due"));
        CoachInsights.roster(a);fill("query","Tennis first serve");assertTrue(findText(a.root,"No players match this search."));fill("query","Padel wall recovery");assertTrue(findText(a.root,"Showing 1–1 of 1 players"));
    });}
    public void testDevelopmentSavePreservesOtherSportAndRecentProfileEdits() throws Exception {
        seed();ui(()->{multiSportCoach();ProfileSetup.athlete(a,athlete);findButton(a.root,"Update development plan").performClick();fill("primaryGoal","Padel controlled lob");fill("developmentNotes","Practice both corners");fill("nextReviewDate","2027-01-01");});recreateScreen();
        ui(()->{JSONObject latest=copy(find(a.store.table("players"),athlete.optString("id")));put(latest,"club","New club saved separately");a.saveRecord("players",latest);findButton(a.root,"Save development plan").performClick();JSONObject saved=find(a.store.table("players"),athlete.optString("id"));assertEquals("Tennis",ProfileSetup.sport(saved));assertEquals("Tennis first serve",saved.optString("primaryGoal"));assertEquals("Tennis plan",saved.optString("developmentNotes"));assertEquals("New club saved separately",saved.optString("club"));JSONObject padel=SportProfiles.forSport(saved,"Padel");assertEquals("Padel controlled lob",padel.optString("primaryGoal"));assertEquals("Practice both corners",padel.optString("developmentNotes"));assertEquals("2027-01-01",padel.optString("nextReviewDate"));});
    }
    public void testLargeRosterSearchPagesAndRecreation() throws Exception {
        seed();ui(()->{mode("Coach","Power");for(int i=0;i<63;i++){JSONObject p=profile(String.format(java.util.Locale.ROOT,"QA Athlete %03d",i),"Player");put(p,"coachProfileID",a.store.player().optString("id"));upsert(a.store.data,"players",p);}a.save();CoachInsights.roster(a);assertTrue(findText(a.root,"Showing 1–25 of 63 players"));findButton(a.root,"Next 25 players").performClick();assertTrue(findText(a.root,"Showing 26–50 of 63 players"));});recreateScreen();
        ui(()->{assertEquals(25,a.rosterOffset);fill("query","Athlete 062");assertTrue(findText(a.root,"Showing 1–1 of 1 players"));assertNull(findButtonPrefix(a.root,"Next "));});recreateScreen();ui(()->{assertEquals("Athlete 062",a.rosterQuery);assertTrue(findText(a.root,"Showing 1–1 of 1 players"));});accessibility();
    }
    public void testRosterMetricsScaleAndDoNotDoubleCountParticipants() throws Exception {
        seed();ui(()->{List<JSONObject> people=new ArrayList<>();for(int i=0;i<100;i++){JSONObject p=profile("QA Load "+i,"Player");people.add(p);upsert(a.store.data,"players",p);}
            for(int i=0;i<6000;i++){JSONObject r=obj();put(r,"id",id());put(r,"playerID",people.get(i%100).optString("id"));put(r,"sport","Tennis");put(r,"date",now());put(r,"status","Completed");put(r,"result",i%2==0?"Win":"Not recorded");put(r,"aces",JSONObject.NULL);array(object(r,"context"),"participantIDs").put(r.optString("playerID"));a.store.table("matches").put(r);}
            long start=SystemClock.elapsedRealtime();Map<String,CoachInsights.Metrics> summaries=CoachMetrics.roster(a.store,people,30,"Tennis");long elapsed=SystemClock.elapsedRealtime()-start;
            assertEquals(100,summaries.size());for(CoachInsights.Metrics m:summaries.values()){assertEquals(60,m.matches);assertEquals(0,m.statisticsRecorded);assertEquals(0,m.acesRecorded);}
            assertTrue("6000-record roster aggregation exceeded 3 seconds: "+elapsed,elapsed<3000);android.util.Log.i("CourtStoryAudit","100-player / 6000-match aggregation ms="+elapsed);
        });
    }
    public void testGroupSessionParticipantCountIsUnique(){seed();ui(()->{JSONObject p=a.store.player(),s=a.newRecord("trainingSessions");put(s,"androidScheduled",false);put(s,"durationMinutes",45);put(s,"date",java.time.Instant.now().minusSeconds(7200).toString());array(object(s,"context"),"participantIDs").put(p.optString("id")).put(p.optString("id"));a.store.table("trainingSessions").put(s);CoachInsights.Metrics m=CoachInsights.metrics(a.store,p,30);assertEquals(1,m.sessions);assertEquals(45,m.minutes);});}
    public void testReminderDeliveredByAndroidOpensCorrectRecord() throws Exception {
        seed();final String[] recordId={null};ui(()->{put(a.store.settings(),"matchRemindersEnabled",true);put(a.store.settings(),"reminderLeadMinutes",0);JSONObject r=a.newRecord("matches");put(r,"status","Scheduled");put(r,"date",java.time.Instant.now().minusSeconds(10).toString());put(r,"opponentName","QA Reminder rival");recordId[0]=r.optString("id");a.saveRecord("matches",r);});ReminderReceiver.awaitIdle();
        Store saved=new Store(a);ReminderPlan.Item item=ReminderPlan.records(saved.data).get(0);NotificationManager manager=a.getSystemService(NotificationManager.class);assertTrue("QA notifications must be enabled for this delivery check",manager.areNotificationsEnabled());
        try{
            ReminderReceiver.pending(a,item.key,item.text,item.table,item.id,item.when).send();
            android.service.notification.StatusBarNotification target=null;long limit=SystemClock.elapsedRealtime()+10000;
            while(target==null&&SystemClock.elapsedRealtime()<limit){for(android.service.notification.StatusBarNotification n:manager.getActiveNotifications())if(n.getId()==item.key.hashCode())target=n;if(target==null)Thread.sleep(50);}
            assertNotNull("Real Android receiver must post the reminder",target);assertTrue(target.getNotification().extras.getCharSequence(Notification.EXTRA_TEXT).toString().contains("QA Player"));
            target.getNotification().contentIntent.send();java.util.concurrent.atomic.AtomicBoolean opened=new java.util.concurrent.atomic.AtomicBoolean();long openDeadline=SystemClock.elapsedRealtime()+10000;do{getInstrumentation().waitForIdleSync();ui(()->opened.set("matches".equals(a.screenTable)&&recordId[0].equals(a.screenRecord)));if(!opened.get())Thread.sleep(50);}while(!opened.get()&&SystemClock.elapsedRealtime()<openDeadline);ui(()->{assertEquals("matches",a.screenTable);assertEquals(recordId[0],a.screenRecord);});
        }finally{manager.cancelAll();}
    }
    public void testStaleReminderCannotPostAfterDeletion() throws Exception {
        seed();final String[] key={null};final long[] when={0};ui(()->{put(a.store.settings(),"matchRemindersEnabled",true);put(a.store.settings(),"reminderLeadMinutes",0);JSONObject r=a.newRecord("matches");put(r,"status","Scheduled");put(r,"date",java.time.Instant.now().minusSeconds(10).toString());a.saveRecord("matches",r);ReminderPlan.Item item=ReminderPlan.records(a.store.data).get(0);key[0]=item.key;when[0]=item.when;try{a.store.remove("matches",r);}catch(Exception e){throw new AssertionError(e);}});ReminderReceiver.awaitIdle();assertFalse(ReminderReceiver.deliver(a,new Intent().setAction(key[0]).putExtra("scheduledFor",when[0])));
    }
    public void testReminderCancellationAndWeeklyScheduling() throws Exception {
        seed();ui(()->{put(a.store.settings(),"matchRemindersEnabled",true);put(a.store.settings(),"weeklySummaryEnabled",true);JSONObject r=a.newRecord("matches");put(r,"date",java.time.Instant.now().plusSeconds(86400).toString());a.saveRecord("matches",r);});ReminderReceiver.awaitIdle();Set<String> active=a.getSharedPreferences("alarms",0).getStringSet("ids",Collections.emptySet());assertEquals(2,active.size());assertTrue(active.contains("weekly"));ui(()->{put(a.store.settings(),"matchRemindersEnabled",false);put(a.store.settings(),"weeklySummaryEnabled",false);a.save();});ReminderReceiver.awaitIdle();assertTrue(a.getSharedPreferences("alarms",0).getStringSet("ids",Collections.emptySet()).isEmpty());
    }
    public void testLargeMediaBackupRoundTripKeepsExactBytes() throws Exception {
        seed();JSONObject person=copy(a.store.player()),media=obj();put(media,"id",id());put(media,"fileName",media.optString("id")+".bin");put(media,"title","QA Large synthetic media");put(media,"description","Generated binary fixture for backup integrity testing");put(media,"mime","video/mp4");array(person,"androidMedia").put(media);ui(()->a.saveRecord("players",person));
        File source=MediaLibrary.file(a,media.optString("fileName")),archive=new File(a.getCacheDir(),"large-media-qa.zip");java.security.MessageDigest expected=java.security.MessageDigest.getInstance("SHA-256");byte[] block=new byte[65536];new Random(27).nextBytes(block);
        try{try(OutputStream stream=new FileOutputStream(source)){for(int i=0;i<800;i++){stream.write(block);expected.update(block);}}try(OutputStream stream=new FileOutputStream(archive)){BackupArchive.write(a,copy(a.store.data),stream);}BackupArchive.Staged stage;try(InputStream stream=new FileInputStream(archive)){stage=BackupArchive.read(a,stream);}try{File restored=new File(stage.directory,media.optString("fileName"));assertEquals(52_428_800L,restored.length());java.security.MessageDigest actual=java.security.MessageDigest.getInstance("SHA-256");try(InputStream stream=new FileInputStream(restored)){int n;while((n=stream.read(block))!=-1)actual.update(block,0,n);}assertTrue(Arrays.equals(expected.digest(),actual.digest()));}finally{BackupArchive.discard(stage.directory);}}finally{source.delete();archive.delete();}
    }
}
