package com.courtstory.app;
import android.test.ActivityInstrumentationTestCase2; import com.google.android.apps.common.testing.accessibility.framework.*; import com.google.android.apps.common.testing.accessibility.framework.uielement.AccessibilityHierarchyAndroid;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Runs only on the isolated QA build applicationId; never touches the installed user library. */
@SuppressWarnings("deprecation")
public class DeviceFlowTest extends ActivityInstrumentationTestCase2<MainActivity> {
    MainActivity a;
    public DeviceFlowTest(){super(MainActivity.class);}
    @Override protected void setUp() throws Exception {super.setUp();android.content.Context c=getInstrumentation().getTargetContext();assertTrue("Tests must run in isolated QA package",c.getPackageName().endsWith(".qa"));Store s=new Store(c);s.data=newLibrary();s.save();a=getActivity();long deadline=android.os.SystemClock.uptimeMillis()+15000;while(!a.libraryReady&&android.os.SystemClock.uptimeMillis()<deadline)Thread.sleep(25);assertTrue("Library opens successfully",a.libraryReady);getInstrumentation().waitForIdleSync();}
    AccessibilityHierarchyAndroid accessibilityHierarchy(){
        java.util.concurrent.CountDownLatch drawn=new java.util.concurrent.CountDownLatch(1);
        ui(()->{android.view.View target=a.root;target.getViewTreeObserver().addOnPreDrawListener(new android.view.ViewTreeObserver.OnPreDrawListener(){public boolean onPreDraw(){target.getViewTreeObserver().removeOnPreDrawListener(this);drawn.countDown();return true;}});target.invalidate();});
        try{assertTrue("Accessibility audit requires a laid-out visible screen",drawn.await(10,java.util.concurrent.TimeUnit.SECONDS));}catch(InterruptedException e){Thread.currentThread().interrupt();throw new AssertionError(e);}
        if(android.os.Build.VERSION.SDK_INT>=34){
            // Native node queries run on the instrumentation thread so the app can answer them.
            android.app.UiAutomation automation=getInstrumentation().getUiAutomation(android.app.UiAutomation.FLAG_DONT_SUPPRESS_ACCESSIBILITY_SERVICES);
            android.view.accessibility.AccessibilityNodeInfo node=automation.getRootInActiveWindow();
            long deadline=android.os.SystemClock.uptimeMillis()+10000;
            while(node==null&&android.os.SystemClock.uptimeMillis()<deadline){android.os.SystemClock.sleep(100);node=automation.getRootInActiveWindow();}
            assertNotNull("An active accessibility window is required",node);
            assertEquals("Inspect the app, never a system dialog",a.getPackageName(),String.valueOf(node.getPackageName()));
            return AccessibilityHierarchyAndroid.newBuilder(node,a).build();
        }
        java.util.concurrent.atomic.AtomicReference<AccessibilityHierarchyAndroid> result=new java.util.concurrent.atomic.AtomicReference<>();
        ui(()->result.set(AccessibilityHierarchyAndroid.newBuilder(a.root).build()));return result.get();
    }
    void ui(Runnable task){java.util.concurrent.atomic.AtomicReference<Throwable> failure=new java.util.concurrent.atomic.AtomicReference<>();getInstrumentation().runOnMainSync(()->{try{task.run();}catch(Throwable e){failure.set(e);}});getInstrumentation().waitForIdleSync();if(failure.get()!=null)throw new AssertionError(failure.get());}
    JSONObject profile(String name,String role){JSONObject p=obj();put(p,"id",id());put(p,"name",name);put(p,"sport","Tennis");put(p,"role",role);put(p,"playerType","Sighted");return p;}
    void seed(){ui(()->{JSONObject p=profile("QA Player","Player");assertTrue(a.saveRecord("players",p));put(a.store.data,"selectedPlayerID",p.optString("id"));a.save();a.home();});}
    public void testOnboardingSportsRolesAndAccessibility(){ui(()->{a.edit("players",null,false);assertTrue(a.editing);for(String sport:ProfileSetup.SPORTS){put(a.draft,"sport",sport);ProfileSetup.form(a,a.draft);}JSONObject p=profile("QA Coach","Coach");put(p,"coachLevel","Qualified coach");a.commit("players",p);a.home();assertTrue(ProfileSetup.coach(a.store.player()));assertTrue(findText(a.root,"Coach’s court"));audit(a.root);});}
    public void testScoringAndPersistentUndo() throws Exception {seed();ui(()->{JSONObject m=a.newRecord("matches");put(m,"opponentName","QA Opponent");put(m,"matchFormat","1 set");put(m,"status","In progress");put(m,"actualStart",now());assertTrue(a.saveRecord("matches",m));a.scorer(m);Button point=findButton(a.root,"Point to QA Player");assertNotNull(point);point.performClick();assertTrue(point.isAttachedToWindow());assertSame(point,findButton(a.root,"Point to QA Player"));findButton(a.root,"Undo last point or scoring action").performClick();assertEquals(0,object(a.store.table("matches").optJSONObject(0),"liveScore").optInt("playerPoints"));audit(a.root);});Store loaded=new Store(getInstrumentation().getTargetContext());assertEquals(1,loaded.table("matches").length());assertEquals(0,object(loaded.table("matches").optJSONObject(0),"liveScore").optInt("playerPoints"));}
    public void testAllEditorsAndReports(){seed();ui(()->{for(String table:new String[]{"matches","trainingSessions","tournaments","coaches","venues","locations","tournamentTemplates"}){a.edit(table,null,false);assertTrue(a.editing);audit(a.root);}a.reports();audit(a.root);a.settings();audit(a.root);a.backup();audit(a.root);a.more();audit(a.root);});}
    public void testSaveTrainingTournamentAndLinks() throws Exception{seed();ui(()->{JSONObject t=a.newRecord("tournaments");put(t,"name","QA Tournament");a.commit("tournaments",t);JSONObject s=a.newRecord("trainingSessions");put(s,"androidScheduled",false);put(s,"durationMinutes",90);put(object(s,"context"),"tournamentID",t.optString("id"));a.commit("trainingSessions",s);JSONObject m=a.newRecord("matches");put(m,"opponentName","QA Opponent");put(m,"status","Completed");put(m,"setScores","6-4");put(m,"tournamentID",t.optString("id"));a.commit("matches",m);assertEquals(1,a.store.table("matches").length());assertEquals(1,a.store.table("trainingSessions").length());assertEquals(1,a.store.table("tournaments").length());assertNull(validate(a.store.data,true));a.detail("tournaments",t);audit(a.root);});Store loaded=new Store(getInstrumentation().getTargetContext());assertEquals(90,duration(loaded.table("trainingSessions").optJSONObject(0)));}
        public void testGoogleAccessibilityFrameworkAcrossScreens(){seed();List<Runnable> screens=java.util.Arrays.asList(a::welcome,a::home,a::track,a::more,a::settings,a::reports,a::backup,()->a.edit("players",null,false),()->a.edit("matches",null,false),()->a.edit("trainingSessions",null,false),()->a.edit("tournaments",null,false),()->Onboarding.show(a,profile("QA Player","Player"),0),()->Onboarding.show(a,profile("QA Player","Player"),1),()->Onboarding.show(a,profile("QA Player","Player"),2),()->Onboarding.show(a,profile("QA Coach","Coach"),2),()->CoachInsights.roster(a),()->CoachInsights.player(a,a.store.player(),30));int index=0;for(Runnable screen:screens){ui(screen);final int screenIndex=index++;{AccessibilityHierarchyAndroid hierarchy=accessibilityHierarchy();List<String> errors=new ArrayList<>();for(AccessibilityHierarchyCheck check:AccessibilityCheckPreset.getAccessibilityHierarchyChecksForPreset(AccessibilityCheckPreset.LATEST))for(AccessibilityHierarchyCheckResult result:check.runCheckOnHierarchy(hierarchy))if(result.getType()==AccessibilityCheckResult.AccessibilityCheckResultType.ERROR)errors.add(check.getClass().getSimpleName()+": "+result.getMessage(java.util.Locale.UK));assertTrue("Google accessibility checks, screen "+screenIndex+": "+errors,errors.isEmpty());}}}
    public void testPlayerMatchDefaultsInCoachCapture(){seed();ui(()->{JSONObject athlete=copy(a.store.player());put(athlete,"preferredMatchType","Doubles");put(athlete,"playerType","Visually impaired");put(athlete,"sightLevel","B3");put(athlete,"defaultMatchFormat","Best of 3");assertTrue(a.saveRecord("players",athlete));JSONObject own=a.newRecord("matches");assertEquals("Doubles",own.optString("matchType"));assertEquals(2,own.optInt("allowedBounces"));JSONObject coach=profile("QA Coach","Coach");put(coach,"preferredMatchType","Singles");assertTrue(a.saveRecord("players",coach));put(a.store.data,"selectedPlayerID",coach.optString("id"));JSONObject recorded=CoachWorkspace.record(a,athlete,"matches");assertEquals("Doubles",recorded.optString("matchType"));assertEquals("Best of 3",recorded.optString("matchFormat"));assertEquals(2,recorded.optInt("allowedBounces"));assertTrue(recorded.optBoolean("suddenDeathDeuce"));put(athlete,"playerType","Sighted");recorded=CoachWorkspace.record(a,athlete,"matches");assertEquals(1,recorded.optInt("allowedBounces"));assertFalse(recorded.optBoolean("suddenDeathDeuce"));});}
    public void testWelcomeRolePathsAndBack(){ui(()->{for(String role:new String[]{"Coach","Player"}){a.welcome();assertTrue(findText(a.root,"Who are you?"));assertNotNull(findButton(a.root,"Restore an Android backup"));Button choice=findButtonPrefix(a.root,"I am a "+role.toLowerCase());assertNotNull(choice);choice.performClick();assertEquals(role,a.draft.optString("role"));assertEquals(0,a.setupStep);JSONObject p=a.draft;findButton(a.root,"Continue").performClick();assertTrue(findText(a.root,role.equals("Coach")?"Your coaching profile":"Your player profile"));put(p,"name","QA "+role);findButton(a.root,"Continue").performClick();assertEquals(2,a.setupStep);a.onBackPressed();assertEquals("QA "+role,a.draft.optString("name"));assertEquals(role,a.draft.optString("role"));findButton(a.root,"Continue").performClick();put(a.draft,"androidTermsAgreed",true);findButton(a.root,"Enter my court").performClick();assertNotNull(find(a.store.table("players"),p.optString("id")));}a.welcome();findButtonPrefix(a.root,"I am a coach").performClick();a.onBackPressed();assertTrue(findText(a.root,"Who are you?"));assertFalse(a.editing);});}
    static Button findButtonPrefix(View v,String label){if(v instanceof Button&&((Button)v).getText().toString().startsWith(label))return (Button)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Button b=findButtonPrefix(g.getChildAt(i),label);if(b!=null)return b;}}return null;}
    public void testGuidedSetupAndSportForms(){ui(()->{Onboarding.start(a,"Coach");assertEquals("onboarding",a.draftTable);JSONObject p=a.draft;put(p,"sport","Pickleball");findButton(a.root,"Continue").performClick();put(p,"name","QA Pickleball Coach");put(p,"role","Coach");findButton(a.root,"Continue").performClick();put(a.draft,"androidTermsAgreed",true);findButton(a.root,"Enter my court").performClick();assertEquals("Pickleball",a.store.player().optString("sport"));assertTrue(ProfileSetup.coach(a.store.player()));assertNotNull(findButton(a.root,"My tournaments"));for(String sport:ProfileSetup.SPORTS){JSONObject match=a.newRecord("matches");put(match,"sport",sport);a.edit("matches",match,true);assertEquals(!CustomScore.custom(match)&&SportRules.pointsStyle(match),findButton(a.root,"Customise game rules — show")!=null);assertEquals(!CustomScore.custom(match)&&!SportRules.pointsStyle(match),findButton(a.root,"Scoring rules — show")!=null);}});}
    public void testCoachMetricsIncludeLinkedPlayers(){seed();ui(()->{JSONObject p=a.store.player();JSONObject coach=profile("QA Coach","Coach");assertTrue(a.saveRecord("players",coach));JSONObject session=a.newRecord("trainingSessions");put(session,"playerID",coach.optString("id"));put(session,"androidScheduled",false);put(session,"durationMinutes",75);array(object(session,"context"),"participantIDs").put(p.optString("id"));assertTrue(a.saveRecord("trainingSessions",session));JSONObject match=a.newRecord("matches");put(match,"status","Completed");put(match,"result","Win");put(match,"yourSetsWon",2);assertTrue(a.saveRecord("matches",match));CoachInsights.Metrics metrics=CoachInsights.metrics(a.store,p,30);assertEquals(1,metrics.matches);assertEquals(1,metrics.wins);assertEquals(75,metrics.minutes);assertEquals(1,metrics.sessions);assertEquals(0,metrics.statisticsRecorded);assertEquals(75,ProgressCharts.workload(a.store,p,"Tennis").get(5).minutes);assertEquals(0,CoachInsights.metrics(a.store,p,30,"Padel").matches);CoachInsights.roster(a);audit(a.root);CoachInsights.player(a,p,30);audit(a.root);});}
    public void testSeveralSportsKeepSeparateRecordsAndModes(){seed();ui(()->{JSONObject tennis=a.newRecord("matches");put(tennis,"opponentName","QA Opponent");assertTrue(a.saveRecord("matches",tennis));JSONObject p=copy(a.store.player());SportProfiles.select(p,"Padel");put(object(p,"sportModes"),"Padel","Coach");assertTrue(a.saveRecord("players",p));assertTrue(SportProfiles.plays(p,"Tennis"));assertTrue(SportProfiles.plays(p,"Padel"));assertEquals(0,a.mine("matches").size());JSONObject padel=a.newRecord("matches");assertEquals("Padel",padel.optString("sport"));put(padel,"opponentName","QA Padel opponent");assertTrue(a.saveRecord("matches",padel));SportProfiles.select(p,"Tennis");assertTrue(a.saveRecord("players",p));assertEquals(1,a.mine("matches").size());assertEquals("Tennis",a.mine("matches").get(0).optString("sport"));SportProfiles.select(p,"Padel");assertTrue(ProfileSetup.coach(p));});}
    public void testCoachCaptureUsesPlayerIdentityAndJournal(){seed();ui(()->{put(a.store.settings(),"trackingMode","Power");JSONObject athlete=a.store.player();JSONObject coach=profile("QA Coach","Coach");assertTrue(a.saveRecord("players",coach));put(a.store.data,"selectedPlayerID",coach.optString("id"));a.save();a.home();assertNotNull(findButton(a.root,"Players"));assertNull(findButton(a.root,"Track"));JSONObject match=CoachWorkspace.record(a,athlete,"matches");assertEquals(athlete.optString("id"),match.optString("playerID"));assertEquals(coach.optString("id"),match.optString("enteredByCoachID"));assertEquals("QA Player",match.optString("playerName"));CoachWorkspace.entry(a,athlete,true);for(Map<String,EditText> fields:a.boundFields.values()){if(fields.containsKey("title"))fields.get("title").setText("Serve targets");if(fields.containsKey("observation"))fields.get("observation").setText("Consistent contact point");if(fields.containsKey("successful"))fields.get("successful").setText("14");if(fields.containsKey("attempts"))fields.get("attempts").setText("20");}findButton(a.root,"Save journal entry").performClick();JSONObject saved=find(a.store.table("players"),athlete.optString("id"));assertEquals(1,array(saved,"coachingJournal").length());assertTrue(findText(a.root,"14 successful from 20 attempts • 70%\nConditions: Not recorded"));CoachWorkspace.overview(a);audit(a.root);});}
    public void testThemePersistsAndChangesAcrossScreens() throws Exception {seed();ui(()->{assertEquals(android.graphics.Color.rgb(221,255,40),a.paper);put(a.store.settings(),"theme","High Contrast");a.save();a.palette();a.home();assertEquals(android.graphics.Color.BLACK,a.paper);assertEquals(android.graphics.Color.WHITE,a.ink);put(a.store.settings(),"theme","Classic");a.save();a.palette();a.track();assertTrue(android.graphics.Color.rgb(221,255,40)!=a.paper);put(a.store.settings(),"theme","Tennis");a.save();a.palette();a.backup();assertEquals(android.graphics.Color.rgb(221,255,40),a.paper);});Store loaded=new Store(getInstrumentation().getTargetContext());assertEquals("Tennis",loaded.settings().optString("theme"));}
    public void testFullBackupIncludesMediaAndRejectsTraversal() throws Exception {seed();JSONObject p=copy(a.store.player()),m=obj();put(m,"id",id());put(m,"fileName",m.optString("id")+".bin");put(m,"mime","image/png");put(m,"title","QA serve photo");put(m,"description","Player at the contact point, racket above the shoulder.");java.io.File source=MediaLibrary.file(a,m.optString("fileName"));android.graphics.Bitmap bitmap=android.graphics.Bitmap.createBitmap(30,30,android.graphics.Bitmap.Config.ARGB_8888);try(java.io.FileOutputStream out=new java.io.FileOutputStream(source)){bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();array(p,"androidMedia").put(m);ui(()->assertTrue(a.saveRecord("players",p)));java.io.ByteArrayOutputStream bytes=new java.io.ByteArrayOutputStream();BackupArchive.write(a,copy(a.store.data),bytes);BackupArchive.Staged staged=BackupArchive.read(a,new java.io.ByteArrayInputStream(bytes.toByteArray()));assertEquals(1,BackupArchive.media(staged.library).size());assertEquals(source.length(),new java.io.File(staged.directory,m.optString("fileName")).length());BackupArchive.discard(staged.directory);ui(()->{MediaLibrary.detail(a,p,m);audit(a.root);assertTrue(findText(a.root,m.optString("description")));});java.io.ByteArrayOutputStream malicious=new java.io.ByteArrayOutputStream();try(java.util.zip.ZipOutputStream zip=new java.util.zip.ZipOutputStream(malicious)){zip.putNextEntry(new java.util.zip.ZipEntry("../outside.txt"));zip.write(1);zip.closeEntry();}try{BackupArchive.read(a,new java.io.ByteArrayInputStream(malicious.toByteArray()));fail("Unsafe archive must be rejected");}catch(java.io.IOException expected){assertNotNull(expected.getMessage());assertFalse(new java.io.File(a.getCacheDir().getParentFile(),"outside.txt").exists());}}
    public void testVisualSnapshots(){seed();List<Runnable> screens=Arrays.asList(a::home,()->Onboarding.start(a),a::backup,a::track,()->{JSONObject p=profile("Alex Morgan","Coach");a.saveRecord("players",p);put(a.store.data,"selectedPlayerID",p.optString("id"));a.home();},()->CoachInsights.roster(a));int index=0;for(Runnable screen:screens){ui(screen);final int number=index++;ui(()->{try{android.graphics.Bitmap bitmap=android.graphics.Bitmap.createBitmap(a.root.getWidth(),a.root.getHeight(),android.graphics.Bitmap.Config.ARGB_8888);a.root.draw(new android.graphics.Canvas(bitmap));try(java.io.FileOutputStream out=new java.io.FileOutputStream(new java.io.File(a.getExternalFilesDir(null),"screen-"+number+".png"))){bitmap.compress(android.graphics.Bitmap.CompressFormat.PNG,100,out);}bitmap.recycle();}catch(Exception e){throw new AssertionError(e);}});}}
    static Button findButton(View v,String label){if(v instanceof Button&&((Button)v).getText().toString().equals(label))return (Button)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Button b=findButton(g.getChildAt(i),label);if(b!=null)return b;}}return null;}
    static boolean findText(View v,String label){if(v instanceof TextView&&((TextView)v).getText().toString().equals(label))return true;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)if(findText(g.getChildAt(i),label))return true;}return false;}
    void audit(View v){if(v.getVisibility()!=View.VISIBLE)return;if(v instanceof Button){Button b=(Button)v;assertFalse("Every button must have a label",b.getText().toString().trim().isEmpty());assertTrue("Button minimum touch height",b.getMinimumHeight()>=a.dp(48));}if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)audit(g.getChildAt(i));}}
}



