package com.courtstory.app;

import org.json.*;
import java.io.*;
import java.time.Instant;
import static com.courtstory.app.Domain.*;

/** Storage, platform and health release regressions. QA package only. */
public class ReleaseAuditTest extends DeviceFlowTest {
    public void testRestoredBackupKeepsRecordsButRejectsOldWatchIdentity() throws Exception {
        seed();JSONObject backup=copy(a.store.data);String originalID=backup.optString("libraryID"),recordID=a.store.player().optString("id");String original=WatchMerge.canonical(backup);
        ui(()->{a.store.data=newLibrary();a.save();try{a.store.restore(backup);}catch(IOException e){throw new AssertionError(e);}});
        Store restored=new Store(a);assertFalse(originalID.equals(restored.data.optString("libraryID")));assertNotNull(find(restored.table("players"),recordID));assertEquals(original,WatchMerge.canonical(backup));
        try{WatchMerge.merge(restored.data,backup,backup);fail("An old watch must not merge into the restored installation");}catch(IOException expected){assertTrue(expected.getMessage().contains("different Court Story libraries"));}
    }
    public void testDeleteSelectedProfileRepairsAllReferences() throws Exception {
        seed(); JSONObject removed=copy(a.store.player());
        ui(()->{
            JSONObject survivor=profile("QA Remaining player","Player");a.saveRecord("players",survivor);
            JSONObject coach=obj();put(coach,"id",id());put(coach,"name","QA Coach");put(coach,"playerID",removed.optString("id"));a.saveRecord("coaches",coach);
            JSONObject session=a.newRecord("trainingSessions");put(session,"playerID",survivor.optString("id"));put(object(session,"practiceResult"),"partnerID",removed.optString("id"));array(object(session,"context"),"participantIDs").put(removed.optString("id"));a.saveRecord("trainingSessions",session);
            try{a.store.remove("players",removed);}catch(IOException e){throw new AssertionError(e);}
            assertEquals(survivor.optString("id"),a.store.player().optString("id"));assertNull(validate(a.store.data,false));
        });
        Store loaded=new Store(a);assertEquals(1,loaded.table("players").length());assertFalse(loaded.table("coaches").optJSONObject(0).has("playerID"));assertEquals(0,array(object(loaded.table("trainingSessions").optJSONObject(0),"context"),"participantIDs").length());
    }
    public void testAtomicBackupRecoveredAfterInterruptedWrite() throws Exception {
        seed();File base=a.store.file.getBaseFile(),backup=new File(base.getPath()+".bak");
        assertTrue(base.renameTo(backup));
        Store recovered=new Store(a);assertEquals("QA Player",playerName(recovered.player()));assertTrue(base.isFile());assertFalse(backup.exists());
    }
    public void testRepeatedScoresHaveMonotonicRevision() throws Exception {
        seed();ui(()->{JSONObject match=a.newRecord("matches");a.saveRecord("matches",match);a.scorer(match);for(int i=0;i<6;i++)findButton(a.root,"Point to QA Player").performClick();assertEquals(7,find(a.store.table("matches"),match.optString("id")).optLong("revision"));});
    }
    public void testRemovedProfileRetainsHistoryAndSurvivesReload() throws Exception {
        seed();final String[] owner={null};ui(()->{owner[0]=a.store.player().optString("id");JSONObject match=a.newRecord("matches");put(match,"status","Completed");put(match,"result","Win");a.saveRecord("matches",match);try{a.store.remove("players",a.store.player());}catch(IOException e){throw new AssertionError(e);}assertNull(a.store.player());assertNull(validate(a.store.data,false));assertNotNull(find(array(a.store.data,ProfileHistory.KEY),owner[0]));ProfileHistory.show(a);assertNotNull(findButton(a.root,"QA Player"));ProfileHistory.player(a,find(array(a.store.data,ProfileHistory.KEY),owner[0]));});
        Store loaded=new Store(a);assertEquals(1,loaded.table("matches").length());assertTrue(ProfileHistory.has(loaded.data));assertFalse(ProfileHistory.empty(loaded.data));
        ui(()->{android.os.Bundle state=new android.os.Bundle();state.putString("screenTable","removedPlayer");state.putString("screenRecord",owner[0]);assertTrue(a.restoreScreen(state));assertEquals("removedPlayer",a.screenTable);});
    }
    public void testActivePlayerRemovalIsBlockedWithoutPartialArchive(){seed();ui(()->{JSONObject match=a.newRecord("matches");put(match,"status","In progress");a.saveRecord("matches",match);try{a.store.remove("players",a.store.player());fail("Active activity must be finished");}catch(IOException expected){}assertFalse(ProfileHistory.has(a.store.data));assertNotNull(a.store.player());});}
    public void testRemovedProfileMediaRemainsReadableAndBackedUp() throws Exception {
        seed();JSONObject p=copy(a.store.player()),media=obj();put(media,"id",id());put(media,"fileName",media.optString("id")+".bin");put(media,"mime","image/png");put(media,"title","Retained serve");put(media,"description","Racket above the shoulder at contact.");File source=MediaLibrary.file(a,media.optString("fileName"));android.graphics.Bitmap image=android.graphics.Bitmap.createBitmap(8,8,android.graphics.Bitmap.Config.ARGB_8888);try(FileOutputStream output=new FileOutputStream(source)){image.compress(android.graphics.Bitmap.CompressFormat.PNG,100,output);}image.recycle();array(p,"androidMedia").put(media);ui(()->{a.saveRecord("players",p);try{a.store.remove("players",p);}catch(IOException e){throw new AssertionError(e);}MediaLibrary.detail(a,p,media);assertNull(findButton(a.root,"Edit description and feedback"));assertNotNull(findButton(a.root,"Back to player history"));});ByteArrayOutputStream bytes=new ByteArrayOutputStream();BackupArchive.write(a,copy(a.store.data),bytes);BackupArchive.Staged restored=BackupArchive.read(a,new ByteArrayInputStream(bytes.toByteArray()));assertTrue(ProfileHistory.has(restored.library));assertEquals(1,BackupArchive.media(restored.library).size());assertEquals(source.length(),new File(restored.directory,media.optString("fileName")).length());BackupArchive.discard(restored.directory);try{a.store.restore(newLibrary());fail("History is not an empty library");}catch(IOException expected){}
    }
    public void testRetainedHistoryPagesAndRestoresWithoutActiveProfile(){seed();ui(()->{JSONObject person=copy(a.store.player());for(int n=0;n<55;n++){JSONObject m=a.newRecord("matches");put(m,"status","Completed");put(m,"opponentName","History "+n);upsert(a.store.data,"matches",m);}a.save();try{a.store.remove("players",person);}catch(IOException e){throw new AssertionError(e);}ProfileHistory.activities(a,person,"matches",0);assertNotNull(findButton(a.root,"Next records"));findButton(a.root,"Next records").performClick();assertEquals(50,a.screenDays);assertNull(findButton(a.root,"Next records"));android.os.Bundle state=new android.os.Bundle();state.putString("screenTable",a.screenTable);state.putString("screenRecord",a.screenRecord);state.putInt("screenDays",50);assertTrue(a.restoreScreen(state));assertEquals(50,a.screenDays);assertNotNull(findButton(a.root,"Previous records"));});}
    JSONObject completedWorkout(){JSONObject s=a.newRecord("trainingSessions");put(s,"androidScheduled",false);put(s,"date",Instant.now().minusSeconds(7200).toString());put(s,"durationMinutes",30);put(s,"revision",7);return s;}
    public void testHealthWorkoutMappingAndIdempotentIdentity(){seed();ui(()->{for(String sport:ProfileSetup.SPORTS){JSONObject s=completedWorkout();put(s,"sport",sport);androidx.health.connect.client.records.ExerciseSessionRecord record=HealthBridge.record(s);assertEquals(1800,java.time.Duration.between(record.getStartTime(),record.getEndTime()).getSeconds());assertEquals("court-story-"+s.optString("id"),record.getMetadata().getClientRecordId());assertEquals(7,record.getMetadata().getClientRecordVersion());assertTrue(record.getTitle().contains(sport));assertEquals(record.getMetadata().getClientRecordId(),HealthBridge.record(s).getMetadata().getClientRecordId());}});}
    public void testHealthRejectsFutureUnfinishedAndOtherPlayer(){seed();ui(()->{
        JSONObject s=completedWorkout();put(s,"date",Instant.now().plusSeconds(3600).toString());try{HealthBridge.record(s);fail("Future workout rejected");}catch(IllegalArgumentException expected){assertTrue(expected.getMessage().contains("future"));}
        s=completedWorkout();put(s,"androidScheduled",true);try{HealthBridge.record(s);fail("Scheduled workout rejected");}catch(IllegalArgumentException expected){assertTrue(expected.getMessage().contains("Finish"));}
        s=completedWorkout();put(s,"playerID",id());assertFalse(HealthBridge.belongsToCurrentProfile(a,s));final String[] error={null};HealthBridge.save(a,s,ignored->fail("Must not export coached player"),message->error[0]=message);assertNotNull(error[0]);
    });}
    public void testModernBackDispatcherPreservesDraft(){seed();ui(()->{a.edit("trainingSessions",null,false);put(a.draft,"notes","QA unsaved note");a.getOnBackPressedDispatcher().onBackPressed();assertTrue(a.editing);assertEquals("QA unsaved note",a.draft.optString("notes"));});getInstrumentation().sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);}
    public void testSportPreferencesDoNotLeakBetweenSports(){seed();ui(()->{JSONObject person=copy(a.store.player());put(person,"bounceAllowance",4);put(person,"defaultMatchFormat","1 set");put(person,"primaryGoal","Tennis serve placement");put(person,"role","Coach");SportProfiles.select(person,"Badminton");assertFalse(person.has("bounceAllowance"));assertFalse(person.has("defaultMatchFormat"));assertFalse(person.has("primaryGoal"));put(person,"primaryGoal","Badminton movement");put(person,"role","Player");SportProfiles.select(person,"Tennis");assertEquals(4,person.optInt("bounceAllowance"));assertEquals("Coach",person.optString("role"));assertEquals("Tennis serve placement",person.optString("primaryGoal"));SportProfiles.select(person,"Badminton");assertEquals("Player",person.optString("role"));assertEquals("Badminton movement",person.optString("primaryGoal"));assertFalse(person.has("bounceAllowance"));});}
    public void testCoachUsesPlayersPreferencesForTheRecordedSport(){seed();ui(()->{JSONObject person=copy(a.store.player());put(person,"bounceAllowance",3);SportProfiles.select(person,"Badminton");put(person,"bounceAllowance",0);SportProfiles.select(person,"Tennis");JSONObject coach=profile("QA Multisport Coach","Coach");SportProfiles.select(coach,"Badminton");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));JSONObject record=CoachWorkspace.record(a,person,"matches");assertEquals("Badminton",record.optString("sport"));assertEquals(0,record.optInt("allowedBounces"));assertEquals(3,person.optInt("bounceAllowance"));assertEquals("Tennis",ProfileSetup.sport(person));});}
    public void testCoachTournamentMatchKeepsSubjectAndSport(){seed();ui(()->{JSONObject athlete=copy(a.store.player()),coach=profile("QA Tournament Coach","Coach");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));JSONObject tournament=CoachWorkspace.record(a,athlete,"tournaments");put(tournament,"name","QA Player Tournament");a.saveRecord("tournaments",tournament);a.detail("tournaments",tournament);findButton(a.root,"Add match to this tournament").performClick();assertEquals(athlete.optString("id"),a.draft.optString("playerID"));assertEquals(tournament.optString("sport"),a.draft.optString("sport"));put(a.draft,"opponentName","QA Rival");JSONObject match=copy(a.draft);a.commit("matches",match);a.detail("tournaments",tournament);assertNotNull(findButton(a.root,title("matches",match)+"\n"+summary("matches",find(a.store.table("matches"),match.optString("id")))));});}
    public void testBasicKeepsCoreTournamentResult(){seed();ui(()->{a.edit("tournaments",null,false);assertNotNull(AuditFlowTest.findButtonPrefix(a.root,"Tournament result"));assertNull(AuditFlowTest.findButtonPrefix(a.root,"Goals and reflection"));});}
    public void testWidgetKeepsCurrentSportAndPrioritisesActiveSession(){seed();ui(()->{JSONObject other=profile("QA Other player","Player");a.saveRecord("players",other);JSONObject wrong=a.newRecord("matches");put(wrong,"playerID",other.optString("id"));put(wrong,"status","In progress");a.saveRecord("matches",wrong);assertNull(CourtWidget.next(a.store));JSONObject active=a.newRecord("trainingSessions");put(active,"actualStart",now());put(active,"date",java.time.Instant.now().plusSeconds(3600).toString());a.saveRecord("trainingSessions",active);JSONObject scheduled=a.newRecord("matches");put(scheduled,"date",java.time.Instant.now().plusSeconds(60).toString());a.saveRecord("matches",scheduled);assertEquals(active.optString("id"),CourtWidget.next(a.store).record.optString("id"));JSONObject changed=copy(a.store.player());SportProfiles.select(changed,"Padel");a.saveRecord("players",changed);assertNull(CourtWidget.next(a.store));});}
    public void testNewTrainingParticipantsCommitWithSession(){seed();ui(()->{JSONObject session=a.newRecord("trainingSessions");put(session,"sport","Padel");TrainingLinks.addParticipant(a,session,"QA New Participant");assertEquals(1,a.store.table("players").length());assertEquals(1,array(session,"androidPendingPlayers").length());assertTrue(a.saveRecord("trainingSessions",session));assertEquals(2,a.store.table("players").length());JSONObject guest=a.store.table("players").optJSONObject(1);assertEquals(java.util.Arrays.asList("Padel"),SportProfiles.sports(guest));assertFalse(find(a.store.table("trainingSessions"),session.optString("id")).has("androidPendingPlayers"));assertNull(validate(a.store.data,false));});}
    public void testTrainingMatchLinksMoveAndUnlinkAtomically(){seed();ui(()->{JSONObject first=a.newRecord("trainingSessions"),second=a.newRecord("trainingSessions"),match=a.newRecord("matches");a.saveRecord("trainingSessions",first);a.saveRecord("trainingSessions",second);put(match,"trainingSessionID",first.optString("id"));a.saveRecord("matches",match);array(second,"androidLinkedMatchIDs").put(match.optString("id"));assertTrue(a.saveRecord("trainingSessions",second));assertEquals(second.optString("id"),find(a.store.table("matches"),match.optString("id")).optString("trainingSessionID"));put(second,"androidLinkedMatchIDs",new JSONArray());assertTrue(a.saveRecord("trainingSessions",second));assertFalse(find(a.store.table("matches"),match.optString("id")).has("trainingSessionID"));});}
    public void testInvalidTrainingLinkDoesNotLeaveOrphanParticipants(){seed();ui(()->{JSONObject session=a.newRecord("trainingSessions");TrainingLinks.addParticipant(a,session,"QA Must not save");array(session,"androidLinkedMatchIDs").put(id());try{a.store.saveRecord("trainingSessions",session);fail("Invalid link must reject the whole transaction");}catch(java.io.IOException expected){assertTrue(expected.getMessage().contains("linked match"));}assertEquals(1,a.store.table("players").length());assertEquals(0,a.store.table("trainingSessions").length());});}
    public void testQuickActionsRespectSelectedSportAndDoNotCreateRecords(){seed();ui(()->{JSONObject person=copy(a.store.player());SportProfiles.select(person,"Padel");a.saveRecord("players",person);assertTrue(QuickActions.open(a,"match"));assertEquals("Padel",a.draft.optString("sport"));assertEquals(person.optString("id"),a.draft.optString("playerID"));assertEquals(0,a.store.table("matches").length());assertTrue(QuickActions.open(a,"training"));assertEquals("Padel",a.draft.optString("sport"));assertEquals(0,a.store.table("trainingSessions").length());assertFalse(QuickActions.open(a,"unknown"));QuickActions.install(a);assertTrue(a.getSystemService(android.content.pm.ShortcutManager.class).getDynamicShortcuts().size()>0);});}
    public void testExternalActionDoesNotSilentlyDiscardEditor(){seed();ui(()->{a.edit("trainingSessions",null,false);put(a.draft,"notes","QA keep this draft");a.onNewIntent(new android.content.Intent(a,MainActivity.class).putExtra("courtAction","match"));assertEquals("trainingSessions",a.draftTable);assertEquals("QA keep this draft",a.draft.optString("notes"));});getInstrumentation().sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);}
    public void testNavigationLabelsFitWithoutBrokenWords(){seed();ui(a::home);ui(()->{for(int row=0;row<a.nav.getChildCount();row++){android.view.ViewGroup line=(android.view.ViewGroup)a.nav.getChildAt(row);for(int index=0;index<line.getChildCount();index++){android.widget.Button button=(android.widget.Button)line.getChildAt(index);assertNotNull(button.getLayout());assertEquals("Navigation label must fit: "+button.getText(),1,button.getLayout().getLineCount());}}});}
    public void testMissingDocumentProviderKeepsLibraryAndDraft(){seed();ui(()->{a.edit("trainingSessions",null,false);put(a.draft,"notes","QA unsaved session");String before=a.store.data.toString();android.content.Intent missing=new android.content.Intent(android.content.Intent.ACTION_OPEN_DOCUMENT).setType("*/*").setPackage("com.courtstory.unavailable.documentprovider");assertFalse(a.launchDocument(missing,202));assertEquals(before,a.store.data.toString());assertEquals("QA unsaved session",a.draft.optString("notes"));assertFalse(a.isFinishing());});getInstrumentation().sendKeyDownUpSync(android.view.KeyEvent.KEYCODE_BACK);}

    public void testCustomSetupHasNoTennisFormatsAndRespectsTier(){seed();ui(()->{for(String role:new String[]{"Coach","Player"})for(String mode:new String[]{"Basic","Standard","Power"}){JSONObject person=profile("QA Custom Setup",role);SportProfiles.select(person,"Goalball");put(person,"trackingMode",mode);Onboarding.show(a,person,2);assertNull(AuditFlowTest.findButtonPrefix(a.root,"Usual match format"));assertNull(AuditFlowTest.findButtonPrefix(a.root,"Usual match type"));boolean hasGoal=false;for(java.util.Map<String,android.widget.EditText> fields:a.boundFields.values())hasGoal|=fields.containsKey(role.equals("Coach")?"coachingFocus":"primaryGoal");assertEquals(!mode.equals("Basic"),hasGoal);}});}
    public void testDevelopmentPlanSessionBelongsToAthlete(){seed();ui(()->{JSONObject athlete=copy(a.store.player()),coach=profile("QA Development Coach","Coach");put(coach,"trackingMode","Power");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));ProfileSetup.athlete(a,athlete);findButton(a.root,"Plan session for this player").performClick();assertEquals(athlete.optString("id"),a.draft.optString("playerID"));assertEquals(coach.optString("id"),a.draft.optString("enteredByCoachID"));assertEquals("Tennis",a.draft.optString("sport"));});}
    public void testBasicCoachProfileKeepsGuidedGoalsHidden(){seed();ui(()->{JSONObject coach=profile("QA Basic Coach","Coach");put(coach,"trackingMode","Basic");a.saveRecord("players",coach);put(a.store.data,"selectedPlayerID",coach.optString("id"));a.edit("players",coach,false);for(java.util.Map<String,android.widget.EditText> fields:a.boundFields.values()){assertFalse(fields.containsKey("coachingFocus"));assertFalse(fields.containsKey("coachingSessionGoals"));}});}
}
