package com.courtstory.app;
import org.junit.Test;
import org.json.*;
import java.time.*;
import static com.courtstory.app.Domain.*;
import static org.junit.Assert.*;
public class CourtGlanceTest {
    final long now=Instant.parse("2026-10-08T12:00:00Z").toEpochMilli();
    JSONObject library(){JSONObject d=newLibrary(),p=obj();put(p,"id",id());put(p,"name","Coach");put(p,"role","Coach");put(p,"sport","Tennis");table(d,"players").put(p);put(d,"selectedPlayerID",p.optString("id"));return d;}
    JSONObject record(JSONObject d,String table,long time){JSONObject r=obj();put(r,"id",id());put(r,"playerID",d.optString("selectedPlayerID"));put(r,"sport","Tennis");put(r,"date",Instant.ofEpochMilli(time).toString());Domain.table(d,table).put(r);return r;}
    @Test public void weekExcludesFutureOtherSportsAndOtherPlayers(){JSONObject d=library();JSONObject r=record(d,"trainingSessions",now-86400000);put(r,"androidScheduled",false);put(r,"durationMinutes",45);JSONObject m=record(d,"matches",now-3600000);put(m,"status","Completed");put(m,"result","Win");JSONObject future=record(d,"matches",now+3600000);put(future,"status","Completed");put(future,"result","Win");JSONObject athlete=record(d,"trainingSessions",now-86400000);put(athlete,"playerID",id());put(athlete,"durationMinutes",500);JSONObject otherSport=record(d,"matches",now-1000);put(otherSport,"sport","Padel");put(otherSport,"status","Completed");CourtGlance g=CourtGlance.make(d,"week",now);assertEquals("45m",g.compact);assertTrue(g.description.contains("1 match, 1 win"));}
    @Test public void nextKeepsUntimedTodayAndSkipsTimedPast(){JSONObject d=library();JSONObject r=record(d,"matches",now-3600000);put(r,"status","Scheduled");put(r,"hasStartTime",false);assertEquals(r.optString("id"),CourtGlance.make(d,"next",now).recordID);put(r,"hasStartTime",true);assertEquals("None",CourtGlance.make(d,"next",now).compact);}
    @Test public void latestUsesCompletionTimeRatherThanScheduledOrder(){JSONObject d=library();JSONObject old=record(d,"matches",now-86400000),latest=record(d,"matches",now-172800000);put(old,"status","Completed");put(latest,"status","Completed");put(latest,"actualFinish",Instant.ofEpochMilli(now-1000).toString());assertEquals(latest.optString("id"),CourtGlance.make(d,"latest",now).recordID);}
    @Test public void startResumesRunningTrainingInsteadOfCreatingAnother(){JSONObject d=library(),r=record(d,"trainingSessions",now-3600000);put(r,"actualStart",Instant.ofEpochMilli(now-600000).toString());CourtGlance g=CourtGlance.make(d,"startTraining",now);assertEquals(r.optString("id"),g.recordID);assertEquals("10m",g.compact);JSONObject state=obj();put(state,"record",r.optString("id"));put(state,"phase","Paused");put(state,"durationSeconds",120);g=g.withWorkout(state);assertEquals("2m",g.compact);assertTrue(g.description.contains("Paused"));}
    @Test public void currentCustomSportDoesNotUseTennisPoints(){JSONObject d=library();put(table(d,"players").optJSONObject(0),"sport","Goalball");JSONObject r=record(d,"matches",now);put(r,"sport","Goalball");put(r,"status","In progress");CustomScore.defaults(r);JSONArray teams=array(r,"customTeams");put(teams.optJSONObject(0),"name","North");put(teams.optJSONObject(0),"score",4);put(teams.optJSONObject(1),"name","South");put(teams.optJSONObject(1),"score",2);CourtGlance g=CourtGlance.make(d,"current",now);assertTrue(g.description.contains("North: 4"));assertFalse(g.description.contains("Love"));}
}
