package com.courtstory.app;
import org.junit.Test;import org.json.*;import static org.junit.Assert.*;import static com.courtstory.app.Domain.*;
public class CurrentRulesTest {
 JSONObject match(String sport){JSONObject m=obj();put(m,"sport",sport);SportRules.defaults(m);return m;}
 void game(Scoring s,boolean p){for(int i=0;i<4;i++)s.point(p);}
 @Test public void racquetballCurrentRallyAndFiveGames(){JSONObject m=match("Racquetball");assertEquals("Rally points",m.optString("scoringStyle"));assertEquals(11,m.optInt("pointsTarget"));assertEquals(3,m.optInt("gamesToWin"));Scoring s=new Scoring(m);s.point(false);assertEquals(1,s.n("opponentPoints"));assertFalse(s.state.optBoolean("playerServing",true));}
 @Test public void racquetballDoublesHandoutAwardsReceivingPoint(){JSONObject m=match("Racquetball");put(m,"matchType","Doubles");Scoring s=new Scoring(m);s.point(false);assertFalse(s.state.optBoolean("playerServing",true));assertEquals(1,s.n("serverNumber"));s.point(true);assertFalse(s.state.optBoolean("playerServing",true));assertEquals(2,s.n("serverNumber"));assertEquals(1,s.n("playerPoints"));s.point(true);assertTrue(s.state.optBoolean("playerServing"));assertEquals(2,s.n("playerPoints"));}
 @Test public void padelStarAfterTwoAdvantages(){Scoring s=new Scoring(match("Padel"));for(int i=0;i<5;i++){s.point(true);s.point(false);}assertTrue(s.points().startsWith("Star point"));s.point(false);assertEquals(1,s.n("opponentGames"));s.undo();assertEquals(5,s.n("playerPoints"));assertEquals(5,s.n("opponentPoints"));}
 @Test public void padelAdvantageAndGoldenAreDistinct(){for(String rule:new String[]{"Advantage","Golden point"}){JSONObject m=match("Padel");put(m,"padelDeuceRule",rule);Scoring s=new Scoring(m);for(int i=0;i<3;i++){s.point(true);s.point(false);}s.point(true);assertEquals(rule.equals("Golden point")?1:0,s.n("playerGames"));}}
 @Test public void beachDeciderIsTenPointReplacement(){JSONObject m=match("Beach tennis");Scoring s=new Scoring(m);for(int i=0;i<6;i++)game(s,true);for(int i=0;i<6;i++)game(s,false);assertTrue(s.tie());assertTrue(s.state.optBoolean("isMatchTiebreak"));for(int i=0;i<9;i++){s.point(true);s.point(false);}s.point(true);assertFalse(s.complete());s.point(true);assertTrue(s.complete());assertEquals("6-0, 0-6, 11-9",m.optString("setScores"));s.undo();assertFalse(s.complete());assertTrue(s.tie());}
 @Test public void beachNoAdAndSetTiebreak(){Scoring s=new Scoring(match("Beach tennis"));for(int i=0;i<3;i++){s.point(true);s.point(false);}s.point(true);assertEquals(1,s.n("playerGames"));}
 void set(Scoring s,int a,int b){for(int i=0;i<Math.min(a,b);i++){s.point(true);s.point(false);}for(int i=Math.min(a,b);i<Math.max(a,b);i++)s.point(a>b);}
 @Test public void racketlonAggregateClinchNotMostSets(){Scoring s=new Scoring(match("Racketlon"));set(s,21,0);set(s,19,21);set(s,19,21);assertFalse(s.complete());for(int i=0;i<5;i++)s.point(true);assertTrue(s.complete());assertTrue(s.winner());assertEquals(1,s.n("playerSets"));assertEquals(2,s.n("opponentSets"));assertEquals("Win",s.match.optString("result"));assertEquals("21-0, 19-21, 19-21, 5-0",s.match.optString("setScores"));assertTrue(s.undo());assertFalse(s.complete());}
 @Test public void racketlonTieRequiresGummiarmAndResumeUndo(){Scoring s=new Scoring(match("Racketlon"));set(s,21,19);set(s,19,21);set(s,21,19);set(s,19,21);assertFalse(s.complete());assertTrue(s.state.optBoolean("gummiarm"));s=new Scoring(copy(s.match));s.point(false);assertTrue(s.complete());assertEquals("Loss",s.match.optString("result"));assertTrue(s.undo());assertFalse(s.complete());assertTrue(s.state.optBoolean("gummiarm"));}
 @Test public void racketlonServesAndDisciplineOrder(){Scoring s=new Scoring(match("Racketlon"));s.point(true);assertTrue(s.state.optBoolean("playerServing",true));s.point(true);assertFalse(s.state.optBoolean("playerServing",true));for(int i=2;i<21;i++)s.point(true);assertEquals(1,s.n("disciplineIndex"));assertFalse(s.state.optBoolean("gameFirstServer",true));}
 @Test public void defaultsNeverRewriteHistoricRules(){JSONObject m=match("Racquetball");put(m,"scoringStyle","Side-out");put(m,"pointsTarget",15);SportRules.defaults(m);assertEquals("Side-out",m.optString("scoringStyle"));assertEquals(15,m.optInt("pointsTarget"));}
 @Test public void recordedScoresRespectSelectedSport(){assertFalse(SportRules.validRecordedGame(match("Badminton"),6,4,0));assertTrue(SportRules.validRecordedGame(match("Badminton"),30,29,0));assertFalse(SportRules.validRecordedGame(match("Squash"),15,0,0));assertTrue(SportRules.validRecordedGame(match("Squash"),12,10,0));assertFalse(SportRules.validRecordedGame(match("Tennis"),8,2,0));assertTrue(SportRules.validRecordedGame(match("Beach tennis"),10,8,2));}
 @Test public void earlyRetirementPersistsAndUndoReopensWithoutResult(){Scoring s=new Scoring(match("Tennis"));s.point(true);s.finishEarly("Retired");s=new Scoring(copy(s.match));assertTrue(s.complete());assertEquals("Retired",s.match.optString("result"));s.point(false);assertEquals(0,s.n("opponentPoints"));s.undo();assertFalse(s.complete());assertEquals("Not recorded",s.match.optString("result"));}
 @Test public void platformSinglesUsesNoAdDoublesAllowsAdvantage(){for(String type:new String[]{"Singles","Doubles"}){JSONObject m=match("Platform tennis");put(m,"matchType",type);Scoring s=new Scoring(m);for(int i=0;i<3;i++){s.point(true);s.point(false);}s.point(true);assertEquals(type.equals("Singles")?1:0,s.n("playerGames"));}}
}
