package com.courtstory.app;
import org.junit.Test;import org.json.*;import static org.junit.Assert.*;import static com.courtstory.app.Domain.*;
public class CustomScoreTest {
 JSONObject event(){JSONObject e=obj();put(e,"sport","DEMO Unlisted sport");CustomScore.defaults(e);return e;}
 @Test public void numericFinishAndUndo(){JSONObject e=event();for(int i=0;i<10;i++)CustomScore.add(e,1,1);assertEquals("Completed",e.optString("status"));assertEquals("Loss",e.optString("result"));assertTrue(CustomScore.undo(e));assertEquals(9,array(e,"customTeams").optJSONObject(1).optInt("score"));assertEquals("In progress",e.optString("status"));}
 @Test public void multipleSidesWinnerAndTiedFinish(){JSONObject e=event(),third=obj();put(third,"name","Team 3");put(third,"score",0);array(e,"customTeams").put(third);put(e,"customOwnerSide",2);for(int i=0;i<10;i++)CustomScore.add(e,2,1);assertEquals("Win",e.optString("result"));CustomScore.undo(e);put(e,"customWinningRule","Manual finish");put(array(e,"customTeams").optJSONObject(0),"score",9);CustomScore.finish(e);assertEquals("Draw",e.optString("result"));}
 @Test public void tenGoalLeadNotFirstTen(){JSONObject e=event();put(e,"sport","Goalball");put(e,"customWinningRule","Lead by");put(array(e,"customTeams").optJSONObject(1),"score",3);for(int i=0;i<12;i++)CustomScore.add(e,0,1);assertNotEquals("Completed",e.optString("status"));CustomScore.add(e,0,1);assertEquals("Completed",e.optString("status"));}
 @Test public void rejectsDuplicateSidesAndNegativeScores(){JSONObject e=event();assertNull(CustomScore.validate(e));put(array(e,"customTeams").optJSONObject(1),"name","team 1");assertNotNull(CustomScore.validate(e));put(array(e,"customTeams").optJSONObject(1),"name","Team 2");assertFalse(CustomScore.add(e,0,-1));put(array(e,"customTeams").optJSONObject(0),"score",-1);assertNotNull(CustomScore.validate(e));}
 @Test public void clockSavedAsWallTimeAndPaused(){JSONObject e=event();put(e,"customClockRemainingMs",5000);put(e,"customClockStartedAt",System.currentTimeMillis()-2000);long left=CustomScore.remaining(copy(e));assertTrue(left>2000&&left<=3000);CustomScore.pause(e);assertFalse(e.has("customClockStartedAt"));assertEquals(CustomScore.remaining(e),CustomScore.remaining(copy(e)));}
 @Test public void unknownSportNeverGetsTennisRules(){JSONObject e=event();assertEquals("Numeric totals",e.optString("scoringStyle"));assertFalse(e.has("tieBreakRule"));assertTrue(CustomScore.custom("Goalball"));}
}
