package com.courtstory.app;
import org.junit.Test;
import org.json.*;
import java.time.*;
import static org.junit.Assert.*;
import static com.courtstory.app.Domain.*;

public class ParityScoreCalendarTest {
    @Test public void everyFocusCountsOncePerSession(){JSONObject s=obj();put(s,"focus","Serving");array(s,"additionalFocus").put(" serving ").put("Volleys").put("Not specified");assertEquals(2,TrainingProgress.focus(s).size());java.util.Map<String,Integer> totals=new java.util.LinkedHashMap<>();TrainingProgress.count(totals,s);assertEquals(Integer.valueOf(1),totals.get("Serving"));assertEquals(Integer.valueOf(1),totals.get("Volleys"));}
    @Test public void exactWorkoutDurationAndManualCorrectionRemainDistinct(){JSONObject s=obj();put(object(s,"workout"),"durationSeconds",75);assertEquals(75,durationSeconds(s));assertEquals("1 minute 15 seconds",durationText(durationSeconds(s)));put(s,"durationSource","manual");put(s,"durationMinutes",2);assertEquals(120,durationSeconds(s));assertEquals(75,object(s,"workout").optInt("durationSeconds"));}
    @Test public void liveTieBreakPointsSurviveFinishUndoAndRestart(){JSONObject m=match("");put(m,"matchFormat","1 set");Scoring scoring=new Scoring(m);for(int game=0;game<6;game++){for(int p=0;p<4;p++)scoring.point(true);for(int p=0;p<4;p++)scoring.point(false);}for(int p=0;p<7;p++)scoring.point(true);assertTrue(scoring.complete());assertEquals("Set 1: 7-0",m.optString("tiebreakScore"));assertTrue(scoring.undo());assertEquals("",m.optString("tiebreakScore"));scoring=new Scoring(copy(m));scoring.point(true);assertEquals("Set 1: 7-0",scoring.match.optString("tiebreakScore"));}
    JSONObject match(String score){JSONObject m=obj();put(m,"sport","Tennis");put(m,"matchFormat","Best of 3");put(m,"setScores",score);SportRules.defaults(m);return m;}
    @Test public void separateTieBreaksSurviveCorrections(){JSONObject m=match("7-6 (9-7), 6-7 (5-7), 6-4");assertNull(RecordedScores.apply(m));assertEquals(2,m.optInt("yourSetsWon"));assertEquals("Set 1: 9-7; Set 2: 5-7",m.optString("tiebreakScore"));put(m,"setScores","7-6, 6-7, 6-3");assertNull(RecordedScores.apply(m));assertEquals(9,array(m,"recordedSets").optJSONObject(0).optInt("yourTiebreak"));}
    @Test public void clearingScoreClearsDerivedTotals(){JSONObject m=match("6-4, 6-2");assertNull(RecordedScores.apply(m));put(m,"setScores","");put(m,"result","Not recorded");assertNull(RecordedScores.apply(m));assertEquals(0,m.optInt("yourSetsWon"));assertEquals(0,array(m,"recordedSets").length());assertEquals("Not recorded",m.optString("result"));}
    @Test public void sixAllTieBreakProducesDecidingGame(){JSONObject m=match("6-6 (8-6)");assertNull(RecordedScores.apply(m));assertEquals("7-6 (8-6)",m.optString("setScores"));}
    @Test public void contradictoryAndIncompleteTieBreaksRejected(){assertNotNull(RecordedScores.apply(match("7-6 (4-7)")));assertNotNull(RecordedScores.apply(match("7-6 (6-5)")));}
    @Test public void retirementAllowsTiedUnfinishedSet(){JSONObject m=match("6-4, 2-2");put(m,"result","Retired");assertNull(RecordedScores.apply(m));assertEquals("Retired",m.optString("result"));assertEquals(1,m.optInt("yourSetsWon"));}
    @Test public void resetCanBeUndone(){JSONObject m=match("");Scoring score=new Scoring(m);score.point(true);score.point(true);score.reset();assertEquals(0,score.n("playerPoints"));assertEquals("",m.optString("setScores"));assertTrue(score.undo());assertEquals(2,score.n("playerPoints"));}
    @Test public void extraSetAfterWinnerRejected(){assertNotNull(RecordedScores.apply(match("6-0, 6-0, 0-6")));}
    @Test public void pointSportRetainsOwnRules(){JSONObject m=obj();put(m,"setScores","21-18, 21-16");put(m,"sport","Badminton");SportRules.defaults(m);assertNull(RecordedScores.apply(m));put(m,"setScores","21-18 (7-4)");assertNotNull(RecordedScores.apply(m));}
    @Test public void allDayMatchDoesNotInventStartTime(){JSONObject m=match("");put(m,"date","2026-10-24T13:15:00Z");CalendarPlan p=CalendarPlan.make("matches",m,ZoneId.of("Europe/London"));assertTrue(p.allDay);assertEquals(Instant.parse("2026-10-24T00:00:00Z").toEpochMilli(),p.start);assertEquals(86400000L,p.end-p.start);}
    @Test public void tournamentAcrossClockChangeKeepsInclusiveDates(){JSONObject m=obj();put(m,"date","2026-10-23T23:00:00Z");put(m,"endDate","2026-10-26T00:00:00Z");CalendarPlan p=CalendarPlan.make("tournaments",m,ZoneId.of("Europe/London"));assertEquals(Instant.parse("2026-10-24T00:00:00Z").toEpochMilli(),p.start);assertEquals(Instant.parse("2026-10-27T00:00:00Z").toEpochMilli(),p.end);}
    @Test public void timedTournamentDoesNotGainAnExtraDay(){JSONObject m=obj();put(m,"date","2026-10-24T09:00:00Z");put(m,"endDate","2026-10-24T16:00:00Z");put(m,"isAllDay",false);put(m,"hasStartTime",true);CalendarPlan p=CalendarPlan.make("tournaments",m,ZoneId.of("Europe/London"));assertFalse(p.allDay);assertEquals(7*3600000L,p.end-p.start);}
    @Test public void unknownExpectedDurationUsesCalendarFallback(){JSONObject m=match("");put(m,"date","2026-10-24T09:00:00Z");put(m,"hasStartTime",true);put(m,"hasExpectedDuration",false);put(m,"expectedDurationMinutes",180);CalendarPlan p=CalendarPlan.make("matches",m,ZoneId.of("Europe/London"));assertEquals(3600000L,p.end-p.start);}
}
