package com.courtstory.app;
import org.junit.Test;
import org.json.*;
import java.time.*;
import static org.junit.Assert.*;
import static com.courtstory.app.Domain.*;

public class ReminderPlanTest {
    JSONObject fixture(){JSONObject data=newLibrary(),p=obj();put(p,"id",id());put(p,"name","Reminder test");table(data,"players").put(p);JSONObject r=obj();put(r,"id",id());put(r,"playerID",p.optString("id"));put(r,"opponentName","Test opponent");put(r,"sport","Tennis");put(r,"date","2026-10-12T10:00:00Z");put(r,"status","Scheduled");table(data,"matches").put(r);put(object(data,"settings"),"matchRemindersEnabled",true);put(object(data,"settings"),"reminderLeadMinutes",60);return data;}
    @Test public void mondayMorningIsNotSkipped(){ZonedDateTime now=ZonedDateTime.of(2026,10,12,8,0,0,0,ZoneId.of("Europe/London"));assertEquals(now.plusHours(1).toInstant().toEpochMilli(),ReminderPlan.nextWeek(now));assertEquals(now.plusWeeks(1).plusHours(1).toInstant().toEpochMilli(),ReminderPlan.nextWeek(now.plusHours(1)));}
    @Test public void weeklyFollowsLocalTimeAcrossClockChange(){ZonedDateTime now=ZonedDateTime.of(2026,10,24,12,0,0,0,ZoneId.of("Europe/London"));ZonedDateTime due=Instant.ofEpochMilli(ReminderPlan.nextWeek(now)).atZone(now.getZone());assertEquals(9,due.getHour());assertEquals(DayOfWeek.MONDAY,due.getDayOfWeek());assertEquals(ZoneOffset.UTC,due.getOffset());}
    @Test public void deletedChangedAndDisabledRecordsCannotNotify(){JSONObject data=fixture();ReminderPlan.Item item=ReminderPlan.records(data).get(0);assertNotNull(ReminderPlan.eligible(data,item.key,item.when,item.when+1000));put(table(data,"matches").optJSONObject(0),"date","2026-10-13T10:00:00Z");assertNull(ReminderPlan.eligible(data,item.key,item.when,item.when+1000));data=fixture();item=ReminderPlan.records(data).get(0);put(object(data,"settings"),"matchRemindersEnabled",false);assertNull(ReminderPlan.eligible(data,item.key,item.when,item.when+1000));put(object(data,"settings"),"matchRemindersEnabled",true);table(data,"matches").remove(0);assertNull(ReminderPlan.eligible(data,item.key,item.when,item.when+1000));}
    @Test public void remindersCannotDeliverBeforeTheirDueTime(){JSONObject data=fixture();ReminderPlan.Item item=ReminderPlan.records(data).get(0);assertNull(ReminderPlan.eligible(data,item.key,item.when,item.when-1));assertNull(ReminderPlan.eligible(data,null,item.when,item.when));}
    @Test public void completedMatchWithMissingResultStillPrompts(){JSONObject data=fixture(),r=table(data,"matches").optJSONObject(0);put(object(data,"settings"),"matchRemindersEnabled",false);put(object(data,"settings"),"matchResultRemindersEnabled",true);put(r,"status","Completed");put(r,"result","Not recorded");assertEquals(1,ReminderPlan.records(data).size());put(r,"result","Win");assertTrue(ReminderPlan.records(data).isEmpty());}
    @Test public void disabledWeeklyReminderCannotNotify(){JSONObject data=fixture();assertNull(ReminderPlan.eligible(data,"weekly",1000,2000));put(object(data,"settings"),"weeklySummaryEnabled",true);assertNotNull(ReminderPlan.eligible(data,"weekly",1000,2000));}
    @Test public void largeScheduleUsesEarliestRollingQueue(){JSONObject data=fixture(),template=table(data,"matches").optJSONObject(0);table(data,"matches").remove(0);long now=Instant.parse("2026-10-01T00:00:00Z").toEpochMilli();put(object(data,"settings"),"reminderLeadMinutes",0);for(int i=1000;i>0;i--){JSONObject r=copy(template);put(r,"id",id());put(r,"date",Instant.ofEpochMilli(now+i*60000L).toString());table(data,"matches").put(r);}java.util.List<ReminderPlan.Item> next=ReminderPlan.upcoming(data,now);assertEquals(128,next.size());assertEquals(now+60000,next.get(0).when);assertEquals(now+128*60000,next.get(127).when);next=ReminderPlan.upcoming(data,now+60000);assertEquals(now+2*60000,next.get(0).when);assertEquals(now+129*60000,next.get(127).when);}
}
