package com.courtstory.app;

import android.os.Bundle;
import android.graphics.Color;
import android.graphics.Typeface;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;
import static com.courtstory.app.Domain.*;

/** Watch presentation shares scoring, validation and record formats with the phone. */
public final class WatchActivity extends MainActivity {
    private boolean workoutReceiverRegistered;
    private final android.content.BroadcastReceiver workoutReceiver=new android.content.BroadcastReceiver(){
        @Override public void onReceive(android.content.Context context,android.content.Intent intent){
            if(store==null||editing||isFinishing()||isDestroyed())return;
            try{store=new Store(WatchActivity.this);JSONObject state=WatchTraining.state(WatchActivity.this);
                if("trainingSessions".equals(screenTable)&&screenRecord!=null&&screenRecord.equals(state.optString("record"))){JSONObject record=find(store.table("trainingSessions"),screenRecord);if(record!=null){int position=scroll.getScrollY();WatchTraining.show(WatchActivity.this,record);scroll.post(()->scroll.scrollTo(0,position));announce(state.optBoolean("error")?state.optString("message"):"Workout "+state.optString("phase").toLowerCase(java.util.Locale.UK));}}
            }catch(Exception e){announce("Workout status changed. Refresh saved records to review it.");}
        }
    };
    @Override protected void onStart(){super.onStart();androidx.core.content.ContextCompat.registerReceiver(this,workoutReceiver,new android.content.IntentFilter("com.courtstory.app.WORKOUT_STATE"),androidx.core.content.ContextCompat.RECEIVER_NOT_EXPORTED);workoutReceiverRegistered=true;}
    @Override protected void onStop(){if(workoutReceiverRegistered){unregisterReceiver(workoutReceiver);workoutReceiverRegistered=false;}super.onStop();}
    @Override void handleIntent(android.content.Intent intent){if(intent!=null&&"watchWeek".equals(intent.getStringExtra("courtAction"))&&store!=null){week();return;}super.handleIntent(intent);}
    void week(){current=this::week;CourtGlance glance=CourtGlance.make(store.data,"week",System.currentTimeMillis());page("This week",store.player()==null?"Court Story":playerName(store.player()));note(glance.description);button("More progress",this::reports);navigation("Today");}
    void watchFaces(){current=this::watchFaces;page("Watch face","Court Story at a glance");note("Edit your watch face and choose a complication position. Select Court Story, then Current activity, Next activity, This week, Latest result or Start training.");note("Summaries follow your selected profile and sport. They refresh periodically to protect battery life; tap a summary to open the latest record. Training opens your session controls and never starts sensors from the watch face.");note("Shortcuts show no personal details by default. If you enable detailed summaries, your chosen watch face receives activity information and may retain or display it while the watch is locked. Use a watch face you trust. Turning details off requests a refresh; remove the complication for immediate removal from the face.");button(getSharedPreferences("watch-glances",0).getBoolean("showDetails",false)?"Hide personal summaries":"Show detailed summaries",()->{android.content.SharedPreferences prefs=getSharedPreferences("watch-glances",0);prefs.edit().putBoolean("showDetails",!prefs.getBoolean("showDetails",false)).apply();sendBroadcast(new android.content.Intent(this,WatchGlanceReceiver.class).putExtra("privacyChanged",true));watchFaces();});navigation("More");}
    @Override void palette(){super.palette();String theme=store.settings().optString("theme","Tennis");if(theme.equals("System"))return;paper=Color.BLACK;card=theme.equals("High Contrast")?Color.BLACK:theme.equals("Classic")?Color.rgb(22,38,50):Color.rgb(23,43,32);ink=Color.WHITE;muted=theme.equals("High Contrast")?Color.WHITE:Color.rgb(211,225,210);accent=theme.equals("High Contrast")?Color.WHITE:theme.equals("Classic")?Color.rgb(124,222,255):Color.rgb(221,255,40);green=accent;}
    @Override void page(String title,String subtitle){
        if(store==null){ink=Color.WHITE;muted=Color.LTGRAY;card=Color.rgb(23,43,32);}
        editing=false;screenName=title;screenTable=null;screenRecord=null;boundFields.clear();
        root=column();root.setBackgroundColor(paper);setContentView(root);root.setAccessibilityPaneTitle("Court Story. "+title);
        scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);body=column();boolean round=getResources().getConfiguration().isScreenRound();body.setPadding(dp(round?26:14),dp(round?24:16),dp(round?26:14),dp(round?48:20));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,-1));
        TextView heading=text(title,20,true);heading.setAccessibilityHeading(true);heading.setGravity(Gravity.CENTER);body.addView(heading,lp());if(!subtitle.isEmpty())note(subtitle);
        feedback=text("",14,false);feedback.setVisibility(View.GONE);feedback.setAccessibilityLiveRegion(View.ACCESSIBILITY_LIVE_REGION_POLITE);body.addView(feedback,lp());nav=column();
        scroll.setOnGenericMotionListener((v,event)->{if(event.getAction()==MotionEvent.ACTION_SCROLL){float delta=event.getAxisValue(MotionEvent.AXIS_SCROLL);if(delta==0)delta=event.getAxisValue(MotionEvent.AXIS_VSCROLL);scroll.smoothScrollBy(0,-Math.round(delta*dp(48)));return true;}return false;});scroll.setFocusable(true);scroll.requestFocus();
    }
    @Override TextView text(String value,int size,boolean bold){TextView v=super.text(value,Math.max(14,Math.min(size,22)),bold);v.setMinHeight(dp(32));return v;}
    @Override void heading(String value){TextView v=text(value,18,true);v.setAccessibilityHeading(true);body.addView(v,lp());}
    @Override Button button(String value,Runnable action){Button b=super.button(value,action);b.setPadding(dp(8),dp(8),dp(8),dp(8));b.setTextSize(16);b.setLetterSpacing(0);b.setMinHeight(dp(48));b.setMinimumHeight(dp(48));return b;}
    @Override Button primary(String value,Runnable action){Button b=button(value,action);b.setBackground(CourtDesign.surface(accent,0,dp(24),0x44333333));b.setTextColor(Color.rgb(14,43,30));b.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return b;}
    @Override void navigation(String selected){route=selected;button("Court Story menu",this::watchMenu);}
    @Override void welcome(){current=this::welcome;page("Court Story","Your court, on your wrist.");primary("Set up this watch",()->Onboarding.start(this));button("Phone connection",()->WatchConnection.show(this));button("Terms and safe use",()->TermsPolicy.show(this,this::welcome));button("Privacy",this::privacy);}
    @Override void home(){if(store.player()==null){welcome();return;}current=this::home;page("Today",playerName(store.player())+" · "+ProfileSetup.sport(store.player()));
        for(String t:new String[]{"matches","trainingSessions"})for(JSONObject r:mine(t))if(active(r))primary("Resume "+title(t,r),()->detail(t,r));
        if(ProfileSetup.coach(store.player())){primary("Your players",()->ProfileSetup.roster(this));button("Coaching schedule",()->CoachWorkspace.schedule(this));heading("My own game");}upcoming();primary("Track",this::track);button("Live score",this::live);button("Recent activity",this::recent);button("Progress",this::reports);attention();button("Milestones",()->Achievements.show(this));navigation("Today");}
    void attention(){if(!store.settings().optBoolean("showNeedsAttention",true))return;for(String t:new String[]{"matches","trainingSessions","tournaments"})for(JSONObject r:mine(t))if(r.optBoolean("needsDetails")||t.equals("matches")&&status(t,r).equals("Completed")&&r.optString("setScores").trim().isEmpty()&&r.optString("customScoreSummary").trim().isEmpty()){heading("Needs attention");button("Complete "+title(t,r),()->edit(t,r,false));}}
    void upcoming(){for(String table:new String[]{"trainingSessions","matches","tournaments"}){if(table.equals("tournaments")&&!store.settings().optBoolean("showUpcomingTournaments",true))continue;JSONObject next=null;for(JSONObject r:mine(table)){String status=status(table,r);if((status.equals("Scheduled")||status.equals("Entered"))&&millis(r,"date")>=System.currentTimeMillis()&&(next==null||millis(r,"date")<millis(next,"date")))next=r;}if(next!=null){JSONObject r=next;heading(table.equals("trainingSessions")?"Next training":table.equals("matches")?"Next match":"Next tournament");note(summary(table,r));button("Open "+title(table,r),()->detail(table,r));}}}
    void watchMenu(){current=this::watchMenu;page("Court Story",store.player()==null?"Watch":playerName(store.player()));button("Today",this::home);if(store.player()!=null){if(ProfileSetup.coach(store.player()))button("Your players",()->ProfileSetup.roster(this));button("Track",this::track);button("Live",this::live);button("Recent",this::recent);button("Progress",this::reports);button("Milestones",()->Achievements.show(this));button("Switch player",this::choosePlayer);button("Choose sport",()->SportProfiles.choose(this));button("Player or coach mode",()->SportProfiles.mode(this));}button("Phone connection",()->WatchConnection.show(this));button("Settings and setup",this::more);button("Refresh saved records",()->{try{store=new Store(this);home();announce("Saved records refreshed");}catch(Exception e){error("Saved records could not be refreshed.");}});}
    @Override void track(){if(store.player()==null){welcome();return;}current=this::track;page("Track",ProfileSetup.sport(store.player()));primary("Training session",()->edit("trainingSessions",null,false));button("Live score a match",()->edit("matches",null,false));button("Record match result",()->{JSONObject r=newRecord("matches");put(r,"status","Completed");edit("matches",r,false);});button("Manage tournaments",()->list("tournaments"));navigation("Track");}
    @Override void detail(String table,JSONObject record){if(table.equals("trainingSessions"))WatchTraining.show(this,record);else super.detail(table,record);}
    @Override void settings(JSONObject restored){if(store.player()==null){Onboarding.start(this);return;}JSONObject settings=restored==null?copy(store.settings()):restored;if(restored==null)put(settings,"trackingMode",TrackingMode.current(store));if(!settings.has("defaultSeason"))put(settings,"defaultSeason",java.time.Year.now().getValue());current=()->settings(settings);page("Watch preferences","Court Story");editing=true;draft=settings;draftTable="settings";choice(settings,"trackingMode","Tracking mode",split("Basic|Standard|Power"));choice(settings,"theme","Theme",split("Tennis|Classic|System|High Contrast"));choice(settings,"scoreAnnouncementMode","Score announcements",split("Automatic|Reduced|Off"));toggle(settings,"hapticsEnabled","Haptic feedback",true);field(settings,"defaultSeason","Season",true);choice(settings,"defaultMatchType","Default match type",split("Singles|Doubles"));toggle(settings,"showNeedsAttention","Show needs attention",true);toggle(settings,"showUpcomingTournaments","Show upcoming tournaments",true);heading("Reminders");note("Optional reminders open their activity. Wear OS may delay them to save battery.");for(String[] f:new String[][]{{"trainingRemindersEnabled","Training reminders"},{"matchRemindersEnabled","Match reminders"},{"tournamentRemindersEnabled","Tournament reminders"},{"postSessionRemindersEnabled","Reflection reminders"},{"matchResultRemindersEnabled","Missing result reminders"},{"weeklySummaryEnabled","Weekly summary"}})toggle(settings,f[0],f[1],false);field(settings,"reminderLeadMinutes","Reminder lead time in minutes",true);field(settings,"postSessionDelayMinutes","Reflection delay in minutes",true);heading("Sounds");JSONObject sounds=object(settings,"sounds");choice(sounds,"selected","Sound",split("bounce|racketStrike|racketSwing|ballCan|applause"));toggle(sounds,"savesEnabled","Save sounds",false);toggle(sounds,"completionsEnabled","Completion sounds",true);toggle(sounds,"milestonesEnabled","Achievement sounds",true);button("Preview sound",()->sound("milestonesEnabled","tennis_bounce"));primary("Save preferences",()->{String issue=SettingsRules.validate(settings);if(issue!=null){error(issue);return;}JSONObject previous=copy(store.data);put(store.data,"settings",copy(settings));if(store.player()!=null)put(store.player(),"trackingMode",settings.optString("trackingMode","Basic"));if(save()){if(android.os.Build.VERSION.SDK_INT>=33&&anyReminders(settings)&&checkSelfPermission(android.Manifest.permission.POST_NOTIFICATIONS)!=android.content.pm.PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{android.Manifest.permission.POST_NOTIFICATIONS},301);editing=false;draft=null;palette();home();announce("Preferences saved");}else store.data=previous;});button("Cancel",()->{editing=false;draft=null;more();});}
    void live(){current=this::live;page("Live","Your active court records");boolean found=false;for(String t:new String[]{"matches","trainingSessions"})for(JSONObject r:mine(t))if(active(r)){found=true;button(title(t,r),()->detail(t,r));}if(!found)note("No activity is running.");button("Start or record activity",this::track);navigation("Live");}
    void recent(){current=this::recent;page("Recent","Your recorded court story");for(String t:new String[]{"matches","trainingSessions","tournaments"})button(t.equals("trainingSessions")?"Training":t.equals("matches")?"Matches":"Tournaments",()->list(t));navigation("Recent");}
    @Override void more(){current=this::more;page("Settings","Court Story on your watch");button("Players",()->list("players"));button("Coaches",()->list("coaches"));button("Venues",()->list("venues"));button("Tournament templates",()->list("tournamentTemplates"));button("Sounds and preferences",this::settings);button("Watch-face summaries",this::watchFaces);button("Phone connection",()->WatchConnection.show(this));button("Terms and safe use",()->TermsPolicy.show(this,this::more));button("Privacy",this::privacy);navigation("More");}
    @Override boolean restoreScreen(Bundle saved){switch(saved.getString("screenName","")){case "This week":week();return true;case "Watch face":watchFaces();return true;case "Live":live();return true;case "Recent":recent();return true;case "Court Story":watchMenu();return true;case "Phone connection":WatchConnection.show(this);return true;default:return super.restoreScreen(saved);}}
}
